import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  en: {
    home: 'Home',
    exams: 'Exams',
    tools: 'Tools',
    resources: 'Resources',
    currentAffairs: 'Current Affairs',
    blog: 'Blog',
    login: 'Login',
    register: 'Register',
    dashboard: 'Dashboard',
    profile: 'Profile',
    bookmarks: 'Bookmarks',
    notifications: 'Notifications',
    logout: 'Logout',
    search: 'Search',
    searchExams: 'Search exams by title, category...',
    browseExams: 'Browse Exams',
    allExams: 'All Exams',
    allCategories: 'All',
    openNow: 'Open Now',
    viewAll: 'View All',
    exploreExams: 'Explore Exams',
    careerGuide: 'Career Guide',
    eligibilityChecker: 'Eligibility Checker',
    mindMaps: 'Mind Maps',
    freeResources: 'Free Resources',
    examCalendar: 'Exam Calendar',
    examPriority: 'Exam Priority Matrix',
    prepRoadmap: 'Prep Roadmap',
    cutOff: 'Cut-Off Marks',
    compareExams: 'Compare Exams',
    prepTime: 'Prep Time Estimator',
    salaryCalc: 'Salary Calculator',
    about: 'About',
    aboutUs: 'About Us',
    contact: 'Contact',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    disclaimer: 'Disclaimer',
    faq: 'FAQ',
    getStarted: 'Get Started Free',
    subscribe: 'Subscribe',
    readMore: 'Read More',
    latestExams: 'Latest Exams',
    successStories: 'Success Stories',
    free: 'Free',
    students: 'Students',
    categories: 'Categories',
    examCategories: 'Exam Categories',
    language: 'Language',
    hindi: 'Hindi',
    english: 'English',
    quickLinks: 'Quick Links',
    contactNewsletter: 'Contact & Newsletter',
    weeklyUpdates: 'Get weekly exam updates',
    yourEmail: 'Your email',
    subscribedSuccess: 'Subscribed successfully!',
    copyright: 'All rights reserved. Made with purpose for India\'s future civil servants.',
    adminPanel: 'Admin Panel',
    policies: 'Policies',
    // Home page
    heroTag: 'Free Career Guidance for Government Jobs',
    heroTitle1: 'Your Path to',
    heroTitle2: 'Success',
    heroSubtitle: 'Explore 200+ government exams, check eligibility, and access free preparation resources.',
    checkEligibility: 'Check Eligibility',
    whyChoose: 'Why Choose',
    govtExamPath: 'GovtExamPath',
    whyChooseDesc: 'We provide comprehensive, accurate, and up-to-date information to help you navigate government exams.',
    freeForever: 'Free Forever',
    freeForeverDesc: 'All features completely free. No hidden charges.',
    alwaysUpdated: 'Always Updated',
    alwaysUpdatedDesc: 'Real-time updates on exam dates, results, and notifications.',
    officialSources: 'Official Sources',
    officialSourcesDesc: 'All information verified from official government sources.',
    multiLanguage: 'Multi-Language',
    multiLanguageDesc: 'Available in English, Hindi, Telugu, Kannada, Tamil & Malayalam.',
    examsCovered: 'Exams Covered',
    dailyUpdates: 'Daily Updates',
    activeStudents: 'Active Students',
    languages: 'Languages',
    topExamCategories: 'Top Exam Categories',
    whatStudentsSay: 'Why Choose GovtExamPath',
    readyToStart: 'Ready to Start Your Journey?',
    readyToStartDesc: 'Join thousands of aspirants who trust GovtExamPath for their exam preparation.',
    startExploring: 'Start Exploring',
    // Login page
    welcomeBack: 'Welcome Back',
    signInToContinue: 'Sign in to continue your exam preparation journey',
    emailAddress: 'Email Address',
    password: 'Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    signIn: 'Sign In',
    signingIn: 'Signing In...',
    orContinueWith: 'Or continue with',
    dontHaveAccount: "Don't have an account?",
    createOneFree: 'Create one free',
    loginBenefit1: 'Get personalized exam recommendations',
    loginBenefit2: 'Track your bookmarked exams and deadlines',
    loginBenefit3: 'Receive important exam notifications',
    // Register page
    createAccount: 'Create Account',
    joinCommunity: 'Join our community of government exam aspirants',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    confirmPassword: 'Confirm Password',
    reEnterPassword: 'Re-enter your password',
    agreeToTerms: 'I agree to the',
    termsAndConditions: 'Terms & Conditions',
    andThe: 'and the',
    creatingAccount: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    regBenefit1: 'Personalized career recommendations',
    regBenefit2: 'Real-time exam notifications',
    regBenefit3: 'Free study resources and mind maps',
    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    savedExams: 'Saved Exams',
    newNotifications: 'New Notifications',
    accountStatus: 'Account Status',
    activeAccount: 'Active',
    quickActions: 'Quick Actions',
    recentBookmarks: 'Recent Bookmarks',
    latestExamsForYou: 'Latest Exams For You',
    noBookmarksYet: 'No bookmarks yet',
    noExamsAvailable: 'No exams available',
    // Common
    loading: 'Loading...',
    noDataFound: 'No data found',
    tryAgain: 'Try Again',
    goBack: 'Go Back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    submit: 'Submit',
    sending: 'Sending...',
    send: 'Send',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'The page you are looking for does not exist or is under development.',
    backToHome: 'Back to Home',
    // Blog
    blogTitle: 'Blog',
    blogTitleHighlight: 'Exam Preparation Tips & Guides',
    blogSubtitle: 'Expert articles and guides for government exam preparation',
    blogSearchPlaceholder: 'Search articles...',
    blogNoResults: 'No articles found',
    blogFeatured: 'Featured',
    // Success Stories
    ssHeroTitle: 'Success',
    ssHeroHighlight: 'Stories',
    ssHeroSubtitle: 'We are collecting real success stories from our community',
    // About page
    aboutFollowInsta: 'Follow on Instagram',
    aboutSubYoutube: 'Subscribe on YouTube',
    aboutJoinTelegram: 'Join Telegram',
    aboutFollowX: 'Follow on X',
    // Contact page
    contactUs: 'Contact Us',
    contactSubtitle: 'Have a question or feedback? We\'d love to hear from you.',
    yourName: 'Your Name',
    subject: 'Subject',
    message: 'Message',
    responseTime: 'Response Time',
    location: 'Location',
    within24Hours: 'Within 24 Hours',
    // Manage Subscriptions
    manageSubscriptions: 'Manage Subscriptions',
    subscribed: 'Subscribed',
    unsubscribeAll: 'Unsubscribe All',
    subscribeAll: 'Subscribe All',
  },
  hi: {
    home: 'होम',
    exams: 'परीक्षाएं',
    tools: 'उपकरण',
    resources: 'संसाधन',
    currentAffairs: 'समसामयिकी',
    blog: 'ब्लॉग',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफाइल',
    bookmarks: 'बुकमार्क',
    notifications: 'सूचनाएं',
    logout: 'लॉगआउट',
    search: 'खोजें',
    searchExams: 'शीर्षक, श्रेणी से परीक्षा खोजें...',
    browseExams: 'परीक्षाएं ब्राउज़ करें',
    allExams: 'सभी परीक्षाएं',
    allCategories: 'सभी',
    openNow: 'अभी खुला है',
    viewAll: 'सभी देखें',
    exploreExams: 'परीक्षाएं देखें',
    careerGuide: 'करियर गाइड',
    eligibilityChecker: 'पात्रता जांचें',
    mindMaps: 'सिलेबस माइंड मैप',
    freeResources: 'मुफ्त संसाधन',
    examCalendar: 'परीक्षा कैलेंडर',
    examPriority: 'परीक्षा प्राथमिकता मैट्रिक्स',
    prepRoadmap: 'तैयारी रोडमैप',
    cutOff: 'कट-ऑफ अंक',
    compareExams: 'परीक्षाओं की तुलना',
    prepTime: 'तैयारी समय अनुमान',
    salaryCalc: 'वेतन कैलकुलेटर',
    about: 'हमारे बारे में',
    aboutUs: 'हमारे बारे में',
    contact: 'संपर्क',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    disclaimer: 'अस्वीकरण',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    getStarted: 'मुफ्त शुरू करें',
    subscribe: 'सदस्यता लें',
    readMore: 'और पढ़ें',
    latestExams: 'नवीनतम परीक्षाएं',
    successStories: 'सफलता की कहानियां',
    free: 'मुफ्त',
    students: 'छात्र',
    categories: 'श्रेणियां',
    examCategories: 'परीक्षा श्रेणियां',
    language: 'भाषा',
    hindi: 'हिन्दी',
    english: 'English',
    quickLinks: 'त्वरित लिंक',
    contactNewsletter: 'संपर्क और समाचार पत्र',
    weeklyUpdates: 'साप्ताहिक परीक्षा अपडेट पाएं',
    yourEmail: 'आपका ईमेल',
    subscribedSuccess: 'सफलतापूर्वक सदस्यता ली!',
    copyright: 'सर्वाधिकार सुरक्षित। भारत के भावी सिविल सेवकों के लिए बनाया गया।',
    adminPanel: 'एडमिन पैनल',
    policies: 'नीतियां',
    heroTag: 'सरकारी नौकरियों के लिए मुफ्त करियर मार्गदर्शन',
    heroTitle1: 'आपका रास्ता',
    heroTitle2: 'सफलता',
    heroSubtitle: '200+ सरकारी परीक्षाएं खोजें, पात्रता जांचें, और मुफ्त तैयारी संसाधन प्राप्त करें।',
    checkEligibility: 'पात्रता जांचें',
    whyChoose: 'क्यों चुनें',
    govtExamPath: 'GovtExamPath',
    whyChooseDesc: 'हम सरकारी परीक्षाओं को नेविगेट करने में आपकी मदद के लिए व्यापक, सटीक और अद्यतित जानकारी प्रदान करते हैं।',
    freeForever: 'हमेशा मुफ्त',
    freeForeverDesc: 'सभी सुविधाएं पूरी तरह मुफ्त। कोई छिपा शुल्क नहीं।',
    alwaysUpdated: 'हमेशा अपडेटेड',
    alwaysUpdatedDesc: 'परीक्षा तिथियों, परिणामों और सूचनाओं पर रीयल-टाइम अपडेट।',
    officialSources: 'आधिकारिक स्रोत',
    officialSourcesDesc: 'सभी जानकारी आधिकारिक सरकारी स्रोतों से सत्यापित।',
    multiLanguage: 'बहु-भाषा',
    multiLanguageDesc: 'अंग्रेजी, हिंदी, तेलुगु, कन्नड़, तमिल और मलयालम में उपलब्ध।',
    examsCovered: 'परीक्षाएं कवर',
    dailyUpdates: 'दैनिक अपडेट',
    activeStudents: 'सक्रिय छात्र',
    languages: 'भाषाएं',
    topExamCategories: 'शीर्ष परीक्षा श्रेणियां',
    whatStudentsSay: 'GovtExamPath क्यों चुनें',
    readyToStart: 'अपनी यात्रा शुरू करने के लिए तैयार?',
    readyToStartDesc: 'हजारों उम्मीदवारों से जुड़ें जो अपनी परीक्षा तैयारी के लिए GovtExamPath पर भरोसा करते हैं।',
    startExploring: 'खोजना शुरू करें',
    welcomeBack: 'वापसी पर स्वागत है',
    signInToContinue: 'अपनी परीक्षा तैयारी जारी रखने के लिए साइन इन करें',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    enterEmail: 'अपना ईमेल दर्ज करें',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signIn: 'साइन इन',
    signingIn: 'साइन इन हो रहा है...',
    orContinueWith: 'या इसके साथ जारी रखें',
    dontHaveAccount: 'खाता नहीं है?',
    createOneFree: 'मुफ्त बनाएं',
    loginBenefit1: 'व्यक्तिगत परीक्षा सिफारिशें प्राप्त करें',
    loginBenefit2: 'अपनी बुकमार्क की गई परीक्षाओं और डेडलाइन को ट्रैक करें',
    loginBenefit3: 'महत्वपूर्ण परीक्षा सूचनाएं प्राप्त करें',
    createAccount: 'खाता बनाएं',
    joinCommunity: 'सरकारी परीक्षा उम्मीदवारों के समुदाय से जुड़ें',
    fullName: 'पूरा नाम',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    reEnterPassword: 'पासवर्ड दोबारा दर्ज करें',
    agreeToTerms: 'मैं सहमत हूं',
    termsAndConditions: 'नियम और शर्तें',
    andThe: 'और',
    creatingAccount: 'खाता बनाया जा रहा है...',
    alreadyHaveAccount: 'पहले से खाता है?',
    signInHere: 'यहां साइन इन करें',
    regBenefit1: 'व्यक्तिगत करियर सिफारिशें',
    regBenefit2: 'रीयल-टाइम परीक्षा सूचनाएं',
    regBenefit3: 'मुफ्त अध्ययन संसाधन और माइंड मैप',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    savedExams: 'सहेजी गई परीक्षाएं',
    newNotifications: 'नई सूचनाएं',
    accountStatus: 'खाता स्थिति',
    activeAccount: 'सक्रिय',
    quickActions: 'त्वरित कार्य',
    recentBookmarks: 'हाल के बुकमार्क',
    latestExamsForYou: 'आपके लिए नवीनतम परीक्षाएं',
    noBookmarksYet: 'अभी तक कोई बुकमार्क नहीं',
    noExamsAvailable: 'कोई परीक्षा उपलब्ध नहीं',
    loading: 'लोड हो रहा है...',
    noDataFound: 'कोई डेटा नहीं मिला',
    tryAgain: 'पुनः प्रयास करें',
    goBack: 'वापस जाएं',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    submit: 'जमा करें',
    sending: 'भेजा जा रहा है...',
    send: 'भेजें',
    close: 'बंद करें',
    yes: 'हां',
    no: 'नहीं',
    pageNotFound: 'पेज नहीं मिला',
    pageNotFoundDesc: 'आप जो पेज खोज रहे हैं वह मौजूद नहीं है या विकास में है।',
    backToHome: 'होम पर वापस जाएं',
    blogTitle: 'ब्लॉग',
    blogTitleHighlight: 'परीक्षा तैयारी टिप्स और गाइड',
    blogSubtitle: 'सरकारी परीक्षा तैयारी के लिए विशेषज्ञ लेख और गाइड',
    blogSearchPlaceholder: 'लेख खोजें...',
    blogNoResults: 'कोई लेख नहीं मिला',
    blogFeatured: 'विशेष',
    ssHeroTitle: 'सफलता',
    ssHeroHighlight: 'की कहानियां',
    ssHeroSubtitle: 'हम अपने समुदाय से वास्तविक सफलता की कहानियां एकत्र कर रहे हैं',
    aboutFollowInsta: 'इंस्टाग्राम पर फॉलो करें',
    aboutSubYoutube: 'यूट्यूब पर सब्सक्राइब करें',
    aboutJoinTelegram: 'टेलीग्राम से जुड़ें',
    aboutFollowX: 'X पर फॉलो करें',
    contactUs: 'संपर्क करें',
    contactSubtitle: 'कोई सवाल या प्रतिक्रिया है? हमें सुनना अच्छा लगेगा।',
    yourName: 'आपका नाम',
    subject: 'विषय',
    message: 'संदेश',
    responseTime: 'प्रतिक्रिया समय',
    location: 'स्थान',
    within24Hours: '24 घंटे के अंदर',
    manageSubscriptions: 'सदस्यता प्रबंधित करें',
    subscribed: 'सदस्यता ली',
    unsubscribeAll: 'सभी से सदस्यता समाप्त करें',
    subscribeAll: 'सभी की सदस्यता लें',
  },
  te: {
    home: 'హోమ్',
    exams: 'పరీక్షలు',
    tools: 'సాధనాలు',
    resources: 'వనరులు',
    currentAffairs: 'కరెంట్ అఫైర్స్',
    blog: 'బ్లాగ్',
    login: 'లాగిన్',
    register: 'రిజిస్టర్',
    dashboard: 'డాష్‌బోర్డ్',
    profile: 'ప్రొఫైల్',
    bookmarks: 'బుక్‌మార్క్‌లు',
    notifications: 'నోటిఫికేషన్లు',
    logout: 'లాగ్ అవుట్',
    search: 'వెతకండి',
    searchExams: 'శీర్షిక, వర్గం ద్వారా పరీక్షలు వెతకండి...',
    browseExams: 'పరీక్షలు బ్రౌజ్ చేయండి',
    allExams: 'అన్ని పరీక్షలు',
    allCategories: 'అన్ని',
    openNow: 'ఇప్పుడు తెరిచి ఉంది',
    viewAll: 'అన్నీ చూడండి',
    exploreExams: 'పరీక్షలు అన్వేషించండి',
    careerGuide: 'కెరీర్ గైడ్',
    eligibilityChecker: 'అర్హత తనిఖీ',
    mindMaps: 'మైండ్ మ్యాప్స్',
    freeResources: 'ఉచిత వనరులు',
    examCalendar: 'పరీక్ష క్యాలెండర్',
    examPriority: 'పరీక్ష ప్రాధాన్యత మాతృక',
    prepRoadmap: 'తయారీ రోడ్‌మ్యాప్',
    cutOff: 'కట్-ఆఫ్ మార్కులు',
    compareExams: 'పరీక్షలు పోల్చండి',
    prepTime: 'తయారీ సమయ అంచనా',
    salaryCalc: 'జీతం కాల్క్యులేటర్',
    about: 'గురించి',
    aboutUs: 'మా గురించి',
    contact: 'సంప్రదించండి',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'సేవా నిబంధనలు',
    disclaimer: 'నిరాకరణ',
    faq: 'తరచుగా అడిగే ప్రశ్నలు',
    getStarted: 'ఉచితంగా ప్రారంభించండి',
    subscribe: 'సబ్‌స్క్రైబ్',
    readMore: 'మరింత చదవండి',
    latestExams: 'తాజా పరీక్షలు',
    successStories: 'విజయ గాథలు',
    free: 'ఉచితం',
    students: 'విద్యార్థులు',
    categories: 'వర్గాలు',
    examCategories: 'పరీక్ష వర్గాలు',
    language: 'భాష',
    hindi: 'హిందీ',
    english: 'English',
    quickLinks: 'త్వరిత లింకులు',
    contactNewsletter: 'సంప్రదింపు & న్యూస్‌లెటర్',
    weeklyUpdates: 'వారపు పరీక్ష అప్‌డేట్‌లు పొందండి',
    yourEmail: 'మీ ఇమెయిల్',
    subscribedSuccess: 'విజయవంతంగా సబ్‌స్క్రైబ్ చేయబడింది!',
    copyright: 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి. భారతదేశ భావి సివిల్ సర్వెంట్ల కోసం నిర్మించబడింది.',
    adminPanel: 'అడ్మిన్ ప్యానల్',
    policies: 'విధానాలు',
    heroTag: 'ప్రభుత్వ ఉద్యోగాల కోసం ఉచిత కెరీర్ మార్గదర్శకత్వం',
    heroTitle1: 'మీ మార్గం',
    heroTitle2: 'విజయం',
    heroSubtitle: '200+ ప్రభుత్వ పరీక్షలు అన్వేషించండి, అర్హత తనిఖీ చేయండి, మరియు ఉచిత తయారీ వనరులు పొందండి.',
    checkEligibility: 'అర్హత తనిఖీ చేయండి',
    whyChoose: 'ఎందుకు ఎంచుకోవాలి',
    govtExamPath: 'GovtExamPath',
    whyChooseDesc: 'ప్రభుత్వ పరీక్షలలో మీకు సహాయం చేయడానికి మేము సమగ్ర, ఖచ్చితమైన మరియు తాజా సమాచారం అందిస్తాము.',
    freeForever: 'ఎల్లప్పుడూ ఉచితం',
    freeForeverDesc: 'అన్ని ఫీచర్లు పూర్తిగా ఉచితం. దాచిన ఛార్జీలు లేవు.',
    alwaysUpdated: 'ఎల్లప్పుడూ అప్‌డేట్',
    alwaysUpdatedDesc: 'పరీక్ష తేదీలు, ఫలితాలు మరియు నోటిఫికేషన్లపై రియల్-టైమ్ అప్‌డేట్లు.',
    officialSources: 'అధికారిక మూలాలు',
    officialSourcesDesc: 'అన్ని సమాచారం అధికారిక ప్రభుత్వ మూలాల నుండి ధృవీకరించబడింది.',
    multiLanguage: 'బహుభాష',
    multiLanguageDesc: 'ఆంగ్లం, హిందీ, తెలుగు, కన్నడ, తమిళం & మలయాళంలో అందుబాటులో ఉంది.',
    examsCovered: 'పరీక్షలు కవర్',
    dailyUpdates: 'రోజువారీ అప్‌డేట్లు',
    activeStudents: 'యాక్టివ్ విద్యార్థులు',
    languages: 'భాషలు',
    topExamCategories: 'టాప్ పరీక్ష వర్గాలు',
    whatStudentsSay: 'GovtExamPath ఎందుకు ఎంచుకోవాలి',
    readyToStart: 'మీ ప్రయాణం ప్రారంభించడానికి సిద్ధంగా ఉన్నారా?',
    readyToStartDesc: 'వేలాది అభ్యర్థులతో చేరండి, వారు తమ పరీక్ష తయారీ కోసం GovtExamPath ను విశ్వసిస్తారు.',
    startExploring: 'అన్వేషించడం ప్రారంభించండి',
    welcomeBack: 'తిరిగి స్వాగతం',
    signInToContinue: 'మీ పరీక్ష తయారీ కొనసాగించడానికి సైన్ ఇన్ చేయండి',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    enterEmail: 'మీ ఇమెయిల్ నమోదు చేయండి',
    enterPassword: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    rememberMe: 'నన్ను గుర్తుంచుకో',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    signIn: 'సైన్ ఇన్',
    signingIn: 'సైన్ ఇన్ అవుతోంది...',
    orContinueWith: 'లేదా దీనితో కొనసాగించండి',
    dontHaveAccount: 'ఖాతా లేదా?',
    createOneFree: 'ఉచితంగా సృష్టించండి',
    loginBenefit1: 'వ్యక్తిగత పరీక్ష సిఫార్సులు పొందండి',
    loginBenefit2: 'మీ బుక్‌మార్క్ చేసిన పరీక్షలు మరియు గడువులను ట్రాక్ చేయండి',
    loginBenefit3: 'ముఖ్యమైన పరీక్ష నోటిఫికేషన్లు అందుకోండి',
    createAccount: 'ఖాతా సృష్టించండి',
    joinCommunity: 'ప్రభుత్వ పరీక్ష అభ్యర్థుల సమాజంలో చేరండి',
    fullName: 'పూర్తి పేరు',
    enterFullName: 'మీ పూర్తి పేరు నమోదు చేయండి',
    confirmPassword: 'పాస్‌వర్డ్ నిర్ధారించండి',
    reEnterPassword: 'పాస్‌వర్డ్ మళ్ళీ నమోదు చేయండి',
    agreeToTerms: 'నేను అంగీకరిస్తున్నాను',
    termsAndConditions: 'నిబంధనలు & షరతులు',
    andThe: 'మరియు',
    creatingAccount: 'ఖాతా సృష్టించబడుతోంది...',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    signInHere: 'ఇక్కడ సైన్ ఇన్ చేయండి',
    regBenefit1: 'వ్యక్తిగత కెరీర్ సిఫార్సులు',
    regBenefit2: 'రియల్-టైమ్ పరీక్ష నోటిఫికేషన్లు',
    regBenefit3: 'ఉచిత అధ్యయన వనరులు మరియు మైండ్ మ్యాప్‌లు',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    savedExams: 'సేవ్ చేసిన పరీక్షలు',
    newNotifications: 'కొత్త నోటిఫికేషన్లు',
    accountStatus: 'ఖాతా స్థితి',
    activeAccount: 'యాక్టివ్',
    quickActions: 'త్వరిత చర్యలు',
    recentBookmarks: 'ఇటీవలి బుక్‌మార్క్‌లు',
    latestExamsForYou: 'మీ కోసం తాజా పరీక్షలు',
    noBookmarksYet: 'ఇంకా బుక్‌మార్క్‌లు లేవు',
    noExamsAvailable: 'పరీక్షలు అందుబాటులో లేవు',
    loading: 'లోడ్ అవుతోంది...',
    noDataFound: 'డేటా కనుగొనబడలేదు',
    tryAgain: 'మళ్ళీ ప్రయత్నించండి',
    goBack: 'వెనక్కి వెళ్ళండి',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    delete: 'తొలగించండి',
    edit: 'సవరించండి',
    submit: 'సమర్పించండి',
    sending: 'పంపబడుతోంది...',
    send: 'పంపండి',
    close: 'మూసివేయండి',
    yes: 'అవును',
    no: 'కాదు',
    pageNotFound: 'పేజీ కనుగొనబడలేదు',
    pageNotFoundDesc: 'మీరు వెతుకుతున్న పేజీ ఉనికిలో లేదు లేదా అభివృద్ధిలో ఉంది.',
    backToHome: 'హోమ్‌కి తిరిగి వెళ్ళండి',
    blogTitle: 'బ్లాగ్',
    blogTitleHighlight: 'పరీక్ష తయారీ చిట్కాలు & గైడ్‌లు',
    blogSubtitle: 'ప్రభుత్వ పరీక్ష తయారీ కోసం నిపుణుల వ్యాసాలు మరియు గైడ్‌లు',
    blogSearchPlaceholder: 'వ్యాసాలు వెతకండి...',
    blogNoResults: 'వ్యాసాలు కనుగొనబడలేదు',
    blogFeatured: 'ఫీచర్డ్',
    ssHeroTitle: 'విజయ',
    ssHeroHighlight: 'గాథలు',
    ssHeroSubtitle: 'మా సమాజం నుండి నిజమైన విజయ గాథలను సేకరిస్తున్నాము',
    aboutFollowInsta: 'ఇన్‌స్టాగ్రామ్‌లో ఫాలో అవ్వండి',
    aboutSubYoutube: 'యూట్యూబ్‌లో సబ్‌స్క్రైబ్ చేయండి',
    aboutJoinTelegram: 'టెలిగ్రామ్‌లో చేరండి',
    aboutFollowX: 'X లో ఫాలో అవ్వండి',
    contactUs: 'మమ్మల్ని సంప్రదించండి',
    contactSubtitle: 'ప్రశ్న లేదా ఫీడ్‌బ్యాక్ ఉందా? మీ నుండి వినాలనుకుంటున్నాము.',
    yourName: 'మీ పేరు',
    subject: 'విషయం',
    message: 'సందేశం',
    responseTime: 'ప్రతిస్పందన సమయం',
    location: 'ప్రదేశం',
    within24Hours: '24 గంటల్లో',
    manageSubscriptions: 'సబ్‌స్క్రిప్షన్లు నిర్వహించండి',
    subscribed: 'సబ్‌స్క్రైబ్ చేయబడింది',
    unsubscribeAll: 'అన్నిటి నుండి అన్‌సబ్‌స్క్రైబ్',
    subscribeAll: 'అన్నింటికి సబ్‌స్క్రైబ్',
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    exams: 'ಪರೀಕ್ಷೆಗಳು',
    tools: 'ಸಾಧನಗಳು',
    resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    currentAffairs: 'ಪ್ರಚಲಿತ ವ್ಯವಹಾರಗಳು',
    blog: 'ಬ್ಲಾಗ್',
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    profile: 'ಪ್ರೊಫೈಲ್',
    bookmarks: 'ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    search: 'ಹುಡುಕಿ',
    searchExams: 'ಶೀರ್ಷಿಕೆ, ವರ್ಗದಿಂದ ಪರೀಕ್ಷೆಗಳನ್ನು ಹುಡುಕಿ...',
    browseExams: 'ಪರೀಕ್ಷೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    allExams: 'ಎಲ್ಲಾ ಪರೀಕ್ಷೆಗಳು',
    allCategories: 'ಎಲ್ಲಾ',
    openNow: 'ಈಗ ತೆರೆದಿದೆ',
    viewAll: 'ಎಲ್ಲಾ ನೋಡಿ',
    exploreExams: 'ಪರೀಕ್ಷೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    careerGuide: 'ಕೆರಿಯರ್ ಗೈಡ್',
    eligibilityChecker: 'ಅರ್ಹತೆ ಪರಿಶೀಲಕ',
    mindMaps: 'ಮೈಂಡ್ ಮ್ಯಾಪ್ಸ್',
    freeResources: 'ಉಚಿತ ಸಂಪನ್ಮೂಲಗಳು',
    examCalendar: 'ಪರೀಕ್ಷಾ ಕ್ಯಾಲೆಂಡರ್',
    examPriority: 'ಪರೀಕ್ಷಾ ಆದ್ಯತೆ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    prepRoadmap: 'ತಯಾರಿ ರೋಡ್‌ಮ್ಯಾಪ್',
    cutOff: 'ಕಟ್-ಆಫ್ ಅಂಕಗಳು',
    compareExams: 'ಪರೀಕ್ಷೆಗಳನ್ನು ಹೋಲಿಸಿ',
    prepTime: 'ತಯಾರಿ ಸಮಯ ಅಂದಾಜು',
    salaryCalc: 'ವೇತನ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    about: 'ಬಗ್ಗೆ',
    aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
    contact: 'ಸಂಪರ್ಕಿಸಿ',
    privacyPolicy: 'ಗೌಪ್ಯತೆ ನೀತಿ',
    termsOfService: 'ಸೇವಾ ನಿಬಂಧನೆಗಳು',
    disclaimer: 'ಹಕ್ಕು ನಿರಾಕರಣೆ',
    faq: 'ಪದೇ ಪದೇ ಕೇಳುವ ಪ್ರಶ್ನೆಗಳು',
    getStarted: 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    subscribe: 'ಚಂದಾದಾರರಾಗಿ',
    readMore: 'ಇನ್ನಷ್ಟು ಓದಿ',
    latestExams: 'ಇತ್ತೀಚಿನ ಪರೀಕ್ಷೆಗಳು',
    successStories: 'ಯಶೋಗಾಥೆಗಳು',
    free: 'ಉಚಿತ',
    students: 'ವಿದ್ಯಾರ್ಥಿಗಳು',
    categories: 'ವರ್ಗಗಳು',
    examCategories: 'ಪರೀಕ್ಷಾ ವರ್ಗಗಳು',
    language: 'ಭಾಷೆ',
    hindi: 'ಹಿಂದಿ',
    english: 'English',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    contactNewsletter: 'ಸಂಪರ್ಕ & ಸುದ್ದಿಪತ್ರ',
    weeklyUpdates: 'ವಾರದ ಪರೀಕ್ಷಾ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ',
    yourEmail: 'ನಿಮ್ಮ ಇಮೇಲ್',
    subscribedSuccess: 'ಯಶಸ್ವಿಯಾಗಿ ಚಂದಾದಾರರಾಗಿದ್ದೀರಿ!',
    copyright: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ. ಭಾರತದ ಭವಿಷ್ಯದ ನಾಗರಿಕ ಸೇವಕರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
    adminPanel: 'ಅಡ್ಮಿನ್ ಪ್ಯಾನೆಲ್',
    policies: 'ನೀತಿಗಳು',
    heroTag: 'ಸರ್ಕಾರಿ ಉದ್ಯೋಗಗಳಿಗೆ ಉಚಿತ ಕೆರಿಯರ್ ಮಾರ್ಗದರ್ಶನ',
    heroTitle1: 'ನಿಮ್ಮ ದಾರಿ',
    heroTitle2: 'ಯಶಸ್ಸು',
    heroSubtitle: '200+ ಸರ್ಕಾರಿ ಪರೀಕ್ಷೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ, ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ, ಮತ್ತು ಉಚಿತ ತಯಾರಿ ಸಂಪನ್ಮೂಲಗಳನ್ನು ಪಡೆಯಿರಿ.',
    checkEligibility: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ',
    whyChoose: 'ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು',
    govtExamPath: 'GovtExamPath',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ',
    signIn: 'ಸೈನ್ ಇನ್',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    goodMorning: 'ಶುಭೋದಯ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    pageNotFound: 'ಪುಟ ಕಂಡುಬಂದಿಲ್ಲ',
    backToHome: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    contactUs: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
  },
  ta: {
    home: 'முகப்பு',
    exams: 'தேர்வுகள்',
    tools: 'கருவிகள்',
    resources: 'வளங்கள்',
    currentAffairs: 'நடப்பு நிகழ்வுகள்',
    blog: 'வலைப்பதிவு',
    login: 'உள்நுழை',
    register: 'பதிவு',
    dashboard: 'டாஷ்போர்டு',
    profile: 'சுயவிவரம்',
    bookmarks: 'புத்தகக்குறிகள்',
    notifications: 'அறிவிப்புகள்',
    logout: 'வெளியேறு',
    search: 'தேடு',
    searchExams: 'தலைப்பு, வகை மூலம் தேர்வுகளைத் தேடுங்கள்...',
    browseExams: 'தேர்வுகளை உலாவுங்கள்',
    allExams: 'அனைத்து தேர்வுகள்',
    allCategories: 'அனைத்தும்',
    openNow: 'இப்போது திறந்துள்ளது',
    viewAll: 'அனைத்தையும் காண்க',
    exploreExams: 'தேர்வுகளை ஆராயுங்கள்',
    careerGuide: 'தொழில் வழிகாட்டி',
    eligibilityChecker: 'தகுதி சரிபார்ப்பு',
    mindMaps: 'மைண்ட் மேப்ஸ்',
    freeResources: 'இலவச வளங்கள்',
    examCalendar: 'தேர்வு நாட்காட்டி',
    examPriority: 'தேர்வு முன்னுரிமை அணி',
    prepRoadmap: 'தயாரிப்பு வழிகாட்டி',
    cutOff: 'கட்-ஆஃப் மதிப்பெண்கள்',
    compareExams: 'தேர்வுகளை ஒப்பிடுங்கள்',
    prepTime: 'தயாரிப்பு நேர மதிப்பீடு',
    salaryCalc: 'சம்பள கால்குலேட்டர்',
    about: 'பற்றி',
    aboutUs: 'எங்களைப் பற்றி',
    contact: 'தொடர்பு',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    disclaimer: 'மறுப்பு',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    getStarted: 'இலவசமாக தொடங்குங்கள்',
    subscribe: 'சந்தா',
    readMore: 'மேலும் படிக்க',
    latestExams: 'சமீபத்திய தேர்வுகள்',
    successStories: 'வெற்றிக் கதைகள்',
    free: 'இலவசம்',
    students: 'மாணவர்கள்',
    categories: 'வகைகள்',
    examCategories: 'தேர்வு வகைகள்',
    language: 'மொழி',
    quickLinks: 'விரைவு இணைப்புகள்',
    contactNewsletter: 'தொடர்பு & செய்திமடல்',
    weeklyUpdates: 'வாராந்திர தேர்வு புதுப்பிப்புகளைப் பெறுங்கள்',
    yourEmail: 'உங்கள் மின்னஞ்சல்',
    subscribedSuccess: 'வெற்றிகரமாக சந்தா செய்யப்பட்டது!',
    copyright: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. இந்தியாவின் எதிர்கால அரசு ஊழியர்களுக்காக உருவாக்கப்பட்டது.',
    adminPanel: 'நிர்வாக குழு',
    policies: 'கொள்கைகள்',
    heroTag: 'அரசு வேலைகளுக்கான இலவச தொழில் வழிகாட்டுதல்',
    heroTitle1: 'உங்கள் பாதை',
    heroTitle2: 'வெற்றி',
    heroSubtitle: '200+ அரசு தேர்வுகளை ஆராயுங்கள், தகுதியை சரிபார்க்கவும், இலவச தயாரிப்பு வளங்களைப் பெறுங்கள்.',
    checkEligibility: 'தகுதியை சரிபார்க்கவும்',
    whyChoose: 'ஏன் தேர்வு செய்ய வேண்டும்',
    govtExamPath: 'GovtExamPath',
    welcomeBack: 'மீண்டும் வரவேற்கிறோம்',
    signIn: 'உள்நுழை',
    createAccount: 'கணக்கை உருவாக்கு',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    loading: 'ஏற்றுகிறது...',
    pageNotFound: 'பக்கம் கிடைக்கவில்லை',
    backToHome: 'முகப்புக்கு திரும்பு',
    contactUs: 'எங்களை தொடர்பு கொள்ளுங்கள்',
  },
  ml: {
    home: 'ഹോം',
    exams: 'പരീക്ഷകള്‍',
    tools: 'ഉപകരണങ്ങള്‍',
    resources: 'വിഭവങ്ങള്‍',
    currentAffairs: 'സമകാലിക വിഷയങ്ങള്‍',
    blog: 'ബ്ലോഗ്',
    login: 'ലോഗിന്‍',
    register: 'രജിസ്റ്റര്‍',
    dashboard: 'ഡാഷ്‌ബോര്‍ഡ്',
    profile: 'പ്രൊഫൈല്‍',
    bookmarks: 'ബുക്ക്‌മാര്‍ക്കുകള്‍',
    notifications: 'അറിയിപ്പുകള്‍',
    logout: 'ലോഗ് ഔട്ട്',
    search: 'തിരയുക',
    searchExams: 'ശീര്‍ഷകം, വിഭാഗം പ്രകാരം പരീക്ഷകള്‍ തിരയുക...',
    browseExams: 'പരീക്ഷകള്‍ ബ്രൗസ് ചെയ്യുക',
    allExams: 'എല്ലാ പരീക്ഷകളും',
    allCategories: 'എല്ലാം',
    openNow: 'ഇപ്പോള്‍ തുറന്നിരിക്കുന്നു',
    viewAll: 'എല്ലാം കാണുക',
    exploreExams: 'പരീക്ഷകള്‍ പര്യവേക്ഷണം ചെയ്യുക',
    careerGuide: 'കരിയര്‍ ഗൈഡ്',
    eligibilityChecker: 'യോഗ്യതാ പരിശോധന',
    mindMaps: 'മൈന്‍ഡ് മാപ്പുകള്‍',
    freeResources: 'സൗജന്യ വിഭവങ്ങള്‍',
    examCalendar: 'പരീക്ഷ കലണ്ടര്‍',
    examPriority: 'പരീക്ഷ മുന്‍ഗണന മാട്രിക്സ്',
    prepRoadmap: 'തയ്യാറെടുപ്പ് റോഡ്‌മാപ്പ്',
    cutOff: 'കട്ട്-ഓഫ് മാര്‍ക്കുകള്‍',
    compareExams: 'പരീക്ഷകള്‍ താരതമ്യം ചെയ്യുക',
    prepTime: 'തയ്യാറെടുപ്പ് സമയ കണക്കാക്കല്‍',
    salaryCalc: 'ശമ്പള കാല്‍ക്കുലേറ്റര്‍',
    about: 'കുറിച്ച്',
    aboutUs: 'ഞങ്ങളെ കുറിച്ച്',
    contact: 'ബന്ധപ്പെടുക',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    termsOfService: 'സേവന നിബന്ധനകള്‍',
    disclaimer: 'നിരാകരണം',
    faq: 'പതിവ് ചോദ്യങ്ങള്‍',
    getStarted: 'സൗജന്യമായി ആരംഭിക്കുക',
    subscribe: 'സബ്‌സ്‌ക്രൈബ്',
    readMore: 'കൂടുതല്‍ വായിക്കുക',
    latestExams: 'ഏറ്റവും പുതിയ പരീക്ഷകള്‍',
    successStories: 'വിജയ കഥകള്‍',
    free: 'സൗജന്യം',
    students: 'വിദ്യാര്‍ത്ഥികള്‍',
    categories: 'വിഭാഗങ്ങള്‍',
    examCategories: 'പരീക്ഷ വിഭാഗങ്ങള്‍',
    language: 'ഭാഷ',
    quickLinks: 'ദ്രുത ലിങ്കുകള്‍',
    contactNewsletter: 'ബന്ധപ്പെടല്‍ & വാര്‍ത്താക്കുറിപ്പ്',
    weeklyUpdates: 'പ്രതിവാര പരീക്ഷ അപ്‌ഡേറ്റുകള്‍ നേടുക',
    yourEmail: 'നിങ്ങളുടെ ഇമെയില്‍',
    subscribedSuccess: 'വിജയകരമായി സബ്‌സ്‌ക്രൈബ് ചെയ്തു!',
    copyright: 'എല്ലാ അവകാശങ്ങളും സംരക്ഷിച്ചിരിക്കുന്നു. ഇന്ത്യയുടെ ഭാവി സിവില്‍ സര്‍വന്റുമാര്‍ക്കായി നിര്‍മ്മിച്ചത്.',
    adminPanel: 'അഡ്മിന്‍ പാനല്‍',
    policies: 'നയങ്ങള്‍',
    heroTag: 'സര്‍ക്കാര്‍ ജോലികള്‍ക്കായി സൗജന്യ കരിയര്‍ മാര്‍ഗ്ഗനിര്‍ദ്ദേശം',
    heroTitle1: 'നിങ്ങളുടെ വഴി',
    heroTitle2: 'വിജയം',
    heroSubtitle: '200+ സര്‍ക്കാര്‍ പരീക്ഷകള്‍ പര്യവേക്ഷണം ചെയ്യുക, യോഗ്യത പരിശോധിക്കുക, സൗജന്യ തയ്യാറെടുപ്പ് വിഭവങ്ങള്‍ നേടുക.',
    checkEligibility: 'യോഗ്യത പരിശോധിക്കുക',
    whyChoose: 'എന്തുകൊണ്ട് തിരഞ്ഞെടുക്കണം',
    govtExamPath: 'GovtExamPath',
    welcomeBack: 'തിരികെ സ്വാഗതം',
    signIn: 'സൈന്‍ ഇന്‍',
    createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    goodMorning: 'സുപ്രഭാതം',
    goodAfternoon: 'ശുഭ ഉച്ച',
    goodEvening: 'ശുഭ സന്ധ്യ',
    loading: 'ലോഡ് ചെയ്യുന്നു...',
    pageNotFound: 'പേജ് കണ്ടെത്തിയില്ല',
    backToHome: 'ഹോമിലേക്ക് മടങ്ങുക',
    contactUs: 'ഞങ്ങളെ ബന്ധപ്പെടുക',
  },
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('lang', language);
  }, [language]);

  const toggleLanguage = useCallback(() => {
    const languages = ['en', 'hi', 'te', 'kn', 'ta', 'ml'];
    setLanguage((prev) => {
      const idx = languages.indexOf(prev);
      return languages[(idx + 1) % languages.length];
    });
  }, []);

  const t = useCallback((key) => {
    const dict = translations[language] || translations.en;
    return dict[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
