import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  en: {
    home: 'Home',
    exams: 'Exams',
    tools: 'Tools',
    resources: 'Resources',
    currentAffairs: 'Current Affairs',
    blog: 'Blog',
    login: 'Login',
    register: 'Register',
    dashboard: 'Dashboard',
    profile: 'Profile',
    bookmarks: 'Bookmarks',
    notifications: 'Notifications',
    logout: 'Logout',
    search: 'Search',
    searchExams: 'Search exams by title, category...',
    browseExams: 'Browse Exams',
    allExams: 'All Exams',
    allCategories: 'All',
    openNow: 'Open Now',
    viewAll: 'View All',
    exploreExams: 'Explore Exams',
    careerGuide: 'Career Guide',
    eligibilityChecker: 'Eligibility Checker',
    mindMaps: 'Mind Maps',
    freeResources: 'Resources Hub',
    examCalendar: 'Exam Calendar',
    examPriority: 'Exam Priority Matrix',
    prepRoadmap: 'Prep Roadmap',
    cutOff: 'Cut-Off Marks',
    compareExams: 'Compare Exams',
    prepTime: 'Prep Time Estimator',
    salaryCalc: 'Salary Calculator',
    about: 'About',
    aboutUs: 'About Us',
    contact: 'Contact',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    disclaimer: 'Disclaimer',
    faq: 'FAQ',
    getStarted: 'Get Started Free',
    subscribe: 'Subscribe',
    readMore: 'Read More',
    latestExams: 'Latest Exams',
    successStories: 'Success Stories',
    free: 'Free',
    students: 'Students',
    categories: 'Categories',
    examCategories: 'Exam Categories',
    language: 'Language',
    hindi: 'Hindi',
    english: 'English',
    quickLinks: 'Quick Links',
    contactNewsletter: 'Contact & Newsletter',
    weeklyUpdates: 'Get weekly exam updates',
    yourEmail: 'Your email',
    subscribedSuccess: 'Subscribed successfully!',
    copyright: 'All rights reserved. Made with purpose for India\'s future civil servants.',
    adminPanel: 'Admin Panel',
    policies: 'Policies',
    // Home page
    homeBadge: 'Free Career Guidance for Government Jobs',
    heroTitle: 'Your Path to',
    heroSubtitle: 'Explore 200+ government exams, check eligibility, and access free preparation resources.',
    statExams: 'Exams',
    statStudents: 'Students',
    statFree: 'Free',
    closingSoon: 'Closing Soon',
    browseByCat: 'Browse by Category',
    browseByCatSub: '16 sectors, 200+ exams — find your path',
    viewAllCats: 'View all categories',
    freeToolsTitle: 'Free Tools & Features',
    freeToolsSub: 'Everything you need to find and prepare for the right government exam',
    dailyPractice: 'Daily Practice Quiz',
    todayQuiz: 'Today\'s Quick Quiz',
    checkAnswers: 'Check Answers',
    youScored: 'You scored',
    morePractice: 'More Practice',
    whatStudentsSay: 'What Students Say',
    readyToStart: 'Ready to Start Your Journey?',
    readyToStartSub: 'Join thousands of aspirants who use GovtExamPath to navigate their government exam preparation.',
    subscribedCheck: 'You\'re all set!',
    examUpdatesEmail: 'Get weekly exam updates & tips',
    featCareerGuideDesc: 'Personalized exam recommendations based on your profile',
    featEligibilityDesc: 'Instantly find exams you qualify for',
    featMindMapsDesc: 'Visual breakdowns for effective study planning',
    featResourcesDesc: 'On-site quick notes + links to official exam portals',
    featCurrentAffairsDesc: '150+ articles updated daily for all exams',
    featPriorityDesc: 'Find hidden-gem exams with low competition',
    // About page
    aboutHeroSub: 'India\'s free career guidance platform for government exams — because every aspirant deserves a clear path.',
    aboutFounded: 'Founded in 2024',
    ourMission: 'Our Mission',
    missionP1: 'GovtExamPath was born from a simple observation: millions of talented Indians miss government job opportunities simply because they lack access to clear, organized, and reliable exam information.',
    missionP2: 'We are building the most comprehensive, free, and accessible platform that guides every aspirant — from discovering the right exam to successfully applying for it.',
    whatWeOffer: 'What We Offer',
    whatWeOfferSub: 'Comprehensive tools and resources for your government exam journey',
    whyTrustUs: 'Why Trust Us',
    whyTrustUsSub: 'Built with transparency, accuracy, and your success in mind',
    ourTeam: 'Our Team',
    ourTeamSub: 'The people behind GovtExamPath',
    connectWithUs: 'Connect With Us',
    connectWithUsSub: 'Follow us on social media for daily updates',
    joinAspirants: 'Join Our Aspirant Community',
    dreamJobTitle: 'Your Dream Government Job Starts Here',
    dreamJobSub: 'Create a free account and get personalized exam recommendations, eligibility checking, and preparation resources.',
    trustOfficialSources: 'Official Sources Only',
    trustOfficialSourcesDesc: 'All exam data sourced from official government websites and notifications.',
    trustAlwaysUpdated: 'Always Updated',
    trustAlwaysUpdatedDesc: 'Our team monitors notifications daily to keep information current.',
    trustFreeForever: 'Free Forever',
    trustFreeForeverDesc: 'Core features will always remain free. No hidden charges or premium gates.',
    trustPrivacy: 'Your Privacy First',
    trustPrivacyDesc: 'We never sell your data. Minimal data collection, maximum transparency.',
    statStudentsGuided: 'Students Guided',
    statExamsCovered: 'Exams Covered',
    statUpdates: 'Daily Updates',
    learnMore: 'Learn More',
    roleCEO: 'Founder & CEO',
    roleTechLead: 'Tech Lead',
    roleContentHead: 'Content Head',
    teamBio1: 'Passionate about making government career information accessible to all.',
    teamBio2: 'Building scalable tech to empower aspirants across India.',
    teamBio3: 'Ensures every piece of content is accurate, up-to-date, and useful.',
    aboutFeat1Desc: 'AI-powered exam recommendations based on your qualifications and interests.',
    aboutFeat2Desc: 'Check your eligibility for 200+ exams instantly.',
    aboutFeat3Desc: 'Visual syllabus breakdowns for effective study planning.',
    aboutFeat4Desc: 'On-site quick notes and links to official exam portals.',
    aboutFeat5Desc: 'Daily current affairs curated for all government exams.',
    aboutFeat6Desc: 'Find hidden-gem exams with the best competition-to-vacancy ratio.',
    studyResources: 'Study Resources',
    expertBlog: 'Expert Blog',
    // Contact page
    contactTitle: 'Get in Touch',
    contactSubtitle: 'Have a question? We\'d love to hear from you. Send us a message and we\'ll respond within 24 hours.',
    contactEmailLabel: 'Email Us',
    contactResponseTime: 'Response Time',
    contactResponseTimeVal: 'Within 24 hours',
    contactLocationLabel: 'Location',
    contactSendMessage: 'Send us a Message',
    contactMessageSent: 'Message Sent!',
    contactThankYou: 'Thank you for reaching out. We\'ll get back to you within 24 hours.',
    contactYourName: 'Your Name',
    contactEnterName: 'Enter your full name',
    contactEmailAddress: 'Email Address',
    contactSubjectLabel: 'Subject',
    contactSelectTopic: 'Select a topic',
    contactGenQuestion: 'General Question',
    contactExamInfo: 'Exam Information',
    contactEligibilityQuery: 'Eligibility Query',
    contactReportBug: 'Report a Bug',
    contactFeatureRequest: 'Feature Request',
    contactFeedbackLabel: 'Feedback',
    contactMessageLabel: 'Message',
    contactTypeHere: 'Type your message here...',
    contactSending: 'Sending...',
    contactSendBtn: 'Send Message',
    // FAQ page
    faqPageTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Find answers to common questions about government exams and our platform',
    faqSearchPlaceholder: 'Search questions...',
    faqQuestionsLabel: 'questions',
    faqCategoriesLabel: 'categories',
    faqUpdatedLabel: 'Updated June 2026',
    faqCollapseAll: 'Collapse All',
    faqExpandAll: 'Expand All',
    faqNoResults: 'No matching questions found',
    faqTryDifferent: 'Try different keywords or browse categories',
    faqStillHaveQ: 'Still have questions?',
    faqStillHaveQSub: 'Can\'t find what you\'re looking for? Reach out to us.',
    faqTabAll: 'All',
    faqTabGeneral: 'General',
    faqTabEligibility: 'Eligibility',
    faqTabPrep: 'Preparation',
    faqTabApplication: 'Application',
    faqTabSpecific: 'Exam-Specific',
    faqSecGeneral: 'General Questions',
    faqSecEligibility: 'Eligibility & Age Limits',
    faqSecPreparation: 'Preparation Strategy',
    faqSecApplication: 'Application Process',
    faqSecSpecific: 'Specific Exams & Careers',
    // Login page
    loginWelcomeBack: 'Welcome back to your career journey',
    loginWelcomeDesc: 'Access your personalized dashboard, bookmarked exams, and continue your preparation with expert guidance.',
    loginFeature1: 'Track your bookmarked exams and deadlines',
    loginFeature2: 'Get personalized exam recommendations',
    loginFeature3: 'Access study resources and mind maps',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to your GovtExamPath account',
    loginPassword: 'Password',
    loginPasswordPlaceholder: 'Enter your password',
    loginRememberMe: 'Remember me',
    loginForgotPwd: 'Forgot password?',
    loginSignIn: 'Sign In',
    loginOr: 'or',
    loginNoAccount: 'Don\'t have an account?',
    loginCreateFree: 'Create one free',
    // Register page
    registerJourney: 'Begin your journey to a government career',
    registerJourneyDesc: 'Create your free account and unlock personalized exam guidance, eligibility checking, and preparation resources.',
    registerFeature1: 'Personalized career recommendations',
    registerFeature2: 'Instant eligibility checking for 200+ exams',
    registerFeature3: 'Free study resources and mind maps',
    registerFeature4: 'Real-time exam notifications',
    registerTitle: 'Create Account',
    registerSubtitle: 'Join GovtExamPath - it\'s completely free',
    registerFullName: 'Full Name',
    registerFullNamePlaceholder: 'Enter your full name',
    registerConfirmPwd: 'Confirm Password',
    registerConfirmPwdPlaceholder: 'Re-enter your password',
    registerPwdMinChars: 'Min 6 characters',
    registerAgreeTerms: 'I agree to the',
    registerTermsLink: 'Terms of Service',
    registerPrivacyLink: 'Privacy Policy',
    registerCreateBtn: 'Create Account',
    registerAlreadyHave: 'Already have an account?',
    registerSignInLink: 'Sign in',
    pwdWeak: 'Weak',
    pwdFair: 'Fair',
    pwdGood: 'Good',
    pwdStrong: 'Strong',
    pwdVeryStrong: 'Very Strong',
    // Forgot Password
    forgotPwdTitle: 'Forgot Password',
    forgotPwdSubtitle: 'Enter your email to receive a reset link',
    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    dashContinuePrep: 'Continue your exam preparation journey. Check your bookmarked exams, explore new opportunities, and stay updated with the latest notifications.',
    dashSavedExams: 'Saved Exams',
    dashNewNotifs: 'New Notifications',
    dashActiveStatus: 'Active',
    dashAccountStatus: 'Account Status',
    dashLatestExams: 'Latest Exams',
    dashCareerGuideDesc: 'Get personalized exam recommendations',
    dashEligibilityDesc: 'Check which exams you qualify for',
    dashPriorityDesc: 'Find which exams have the best competition-to-vacancy ratio',
    dashRecommended: 'Recommended Exams',
    dashRecentBookmarks: 'Recent Bookmarks',
    dashNoBookmarks: 'No bookmarked exams yet. Browse exams and bookmark the ones you\'re interested in.',
    dashBrowseExams: 'Browse Exams',
    dashRecentNotifs: 'Recent Notifications',
    dashNoNotifs: 'No notifications yet. We\'ll notify you about new exams and deadlines.',
    dashUnableLoad: 'Unable to load your dashboard',
    dashUnableLoadDesc: 'There was a problem connecting to the server. This usually happens when the backend service is unavailable.',
    dashRefresh: 'Refresh',
    dashViewAll: 'View All',
    // Bookmarks
    bookmarksTitle: 'My Bookmarks',
    bookmarksSubtitle: 'Exams you\'ve saved for later',
    bookmarksEmpty: 'No bookmarks yet',
    bookmarksEmptyDesc: 'Start bookmarking exams to keep track of the ones you\'re interested in.',
    // Profile
    profileTitle: 'My Profile',
    profileFullName: 'Full Name',
    profileSaveChanges: 'Save Changes',
    profileCancel: 'Cancel',
    profileEditProfile: 'Edit Profile',
    // Notifications
    notifTitle: 'Notifications',
    notifAllCaughtUp: 'All caught up!',
    notifUnread: 'unread notification',
    notifUnreadPlural: 'unread notifications',
    notifMarkAllRead: 'Mark all as read',
    notifFilterAll: 'All',
    notifFilterExamDates: 'Exam Dates',
    notifFilterHallTickets: 'Hall Tickets',
    notifFilterResults: 'Results',
    notifFilterAnnouncements: 'Announcements',
    notifFilterPlacements: 'Placements',
    notifFilterFeeReminders: 'Fee Reminders',
    notifFilterGeneral: 'General',
    // 404 Not Found
    notFoundPageDev: 'Page Under Development',
    notFoundPageDevDesc: 'This category page is being built. In the meantime, you can browse all exams or use the category filter.',
    notFoundBrowseAll: 'Browse All Exams',
    notFound404: 'Page Not Found',
    notFoundDesc: 'The page you\'re looking for doesn\'t exist or may have been moved.',
    notFoundBack: 'Back to Home',
    notFoundBrowse: 'Browse Exams',
    notFoundLooking: 'Looking for something specific?',
    notFoundResources: 'Resources',
    // Eligibility Checker
    eligCheckerDesc: 'Find out which government exams you\'re eligible for in seconds',
    eligYourAge: 'Your Age',
    eligEnterAge: 'Enter your age',
    eligHighestQual: 'Highest Qualification',
    eligSelectQual: 'Select Qualification',
    eligQual10: '10th Pass',
    eligQual12: '12th Pass',
    eligQualDiploma: 'Diploma (ITI/Polytechnic)',
    eligQualGrad: 'Graduation (B.A/B.Sc/B.Com/B.Tech etc.)',
    eligQualPG: 'Post Graduation (M.A/M.Sc/MBA/M.Tech etc.)',
    eligCatLabel: 'Category',
    eligCatGeneral: 'General',
    eligCatEWS: 'EWS (Economically Weaker Section)',
    eligCatOBC: 'OBC (Other Backward Classes)',
    eligCatSC: 'SC (Scheduled Caste)',
    eligCatST: 'ST (Scheduled Tribe)',
    eligCheckBtn: 'Check Eligibility',
    eligResultsFor: 'Results for: Age',
    eligEligibleLabel: 'Eligible',
    eligAlmostLabel: 'Almost Eligible',
    eligNotEligibleLabel: 'Not Eligible',
    eligGetRecommend: 'Get Personalized Recommendations from Career Guide',
    eligShowAllBtn: 'Show All',
    eligShowLess: 'Show Less',
    eligNotEligibleExams: 'Not Eligible Exams',
    // Exam Detail Page
    examTabOverview: 'Overview',
    examTabEligibility: 'Eligibility',
    examTabSyllabus: 'Syllabus',
    examTabPattern: 'Exam Pattern',
    examTabPYQ: 'Previous Year Papers',
    examTabSalary: 'Salary & Career',
    examTabApply: 'How to Apply',
    examNotFound: 'Exam not found',
    examNotFoundDesc: 'The exam you\'re looking for doesn\'t exist or has been removed.',
    examBackToExams: 'Back to Exams',
    examBack: 'Back',
    examRelated: 'Related Exams',
  },
  hi: {
    home: 'होम',
    exams: 'परीक्षाएं',
    tools: 'उपकरण',
    resources: 'संसाधन',
    currentAffairs: 'समसामयिकी',
    blog: 'ब्लॉग',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफाइल',
    bookmarks: 'बुकमार्क',
    notifications: 'सूचनाएं',
    logout: 'लॉगआउट',
    search: 'खोजें',
    searchExams: 'शीर्षक, श्रेणी से परीक्षा खोजें...',
    browseExams: 'परीक्षाएं ब्राउज़ करें',
    allExams: 'सभी परीक्षाएं',
    allCategories: 'सभी',
    openNow: 'अभी खुला है',
    viewAll: 'सभी देखें',
    exploreExams: 'परीक्षाएं देखें',
    careerGuide: 'करियर गाइड',
    eligibilityChecker: 'पात्रता जांचें',
    mindMaps: 'सिलेबस माइंड मैप',
    freeResources: 'संसाधन केंद्र',
    examCalendar: 'परीक्षा कैलेंडर',
    examPriority: 'परीक्षा प्राथमिकता मैट्रिक्स',
    prepRoadmap: 'तैयारी रोडमैप',
    cutOff: 'कट-ऑफ अंक',
    compareExams: 'परीक्षाओं की तुलना',
    prepTime: 'तैयारी समय अनुमान',
    salaryCalc: 'वेतन कैलकुलेटर',
    about: 'हमारे बारे में',
    aboutUs: 'हमारे बारे में',
    contact: 'संपर्क',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    disclaimer: 'अस्वीकरण',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    getStarted: 'मुफ्त शुरू करें',
    subscribe: 'सदस्यता लें',
    readMore: 'और पढ़ें',
    latestExams: 'नवीनतम परीक्षाएं',
    successStories: 'सफलता की कहानियां',
    free: 'मुफ्त',
    students: 'छात्र',
    categories: 'श्रेणियां',
    examCategories: 'परीक्षा श्रेणियां',
    language: 'भाषा',
    hindi: 'हिन्दी',
    english: 'English',
    quickLinks: 'त्वरित लिंक',
    contactNewsletter: 'संपर्क और समाचार पत्र',
    weeklyUpdates: 'साप्ताहिक परीक्षा अपडेट पाएं',
    yourEmail: 'आपका ईमेल',
    subscribedSuccess: 'सफलतापूर्वक सदस्यता ली!',
    copyright: 'सर्वाधिकार सुरक्षित। भारत के भावी सिविल सेवकों के लिए बनाया गया।',
    adminPanel: 'एडमिन पैनल',
    policies: 'नीतियां',
    homeBadge: 'सरकारी नौकरियों के लिए मुफ्त करियर मार्गदर्शन',
    heroTitle: 'आपका रास्ता',
    heroSubtitle: '200+ सरकारी परीक्षाओं की जानकारी, पात्रता जांच और मुफ्त तैयारी संसाधन।',
    statExams: 'परीक्षाएं',
    statStudents: 'छात्र',
    statFree: 'मुफ्त',
    closingSoon: 'जल्दी बंद हो रहा है',
    browseByCat: 'श्रेणी के अनुसार ब्राउज़ करें',
    browseByCatSub: '16 क्षेत्र, 200+ परीक्षाएं — अपना रास्ता खोजें',
    viewAllCats: 'सभी श्रेणियां देखें',
    freeToolsTitle: 'मुफ्त उपकरण और सुविधाएं',
    freeToolsSub: 'सही सरकारी परीक्षा खोजने और तैयारी करने के लिए सब कुछ',
    dailyPractice: 'दैनिक अभ्यास क्विज़',
    todayQuiz: 'आज की क्विक क्विज़',
    checkAnswers: 'उत्तर जांचें',
    youScored: 'आपने स्कोर किया',
    morePractice: 'और अभ्यास',
    whatStudentsSay: 'छात्र क्या कहते हैं',
    readyToStart: 'अपनी यात्रा शुरू करने के लिए तैयार हैं?',
    readyToStartSub: 'हजारों उम्मीदवारों से जुड़ें जो GovtExamPath का उपयोग करते हैं।',
    subscribedCheck: 'आप तैयार हैं!',
    examUpdatesEmail: 'साप्ताहिक परीक्षा अपडेट और टिप्स पाएं',
    featCareerGuideDesc: 'आपकी प्रोफ़ाइल के आधार पर व्यक्तिगत परीक्षा सिफारिशें',
    featEligibilityDesc: 'तुरंत जानें कि आप किन परीक्षाओं के योग्य हैं',
    featMindMapsDesc: 'प्रभावी अध्ययन योजना के लिए दृश्य विश्लेषण',
    featResourcesDesc: 'साइट पर त्वरित नोट्स + आधिकारिक परीक्षा पोर्टल के लिंक',
    featCurrentAffairsDesc: 'सभी परीक्षाओं के लिए 150+ दैनिक अपडेट लेख',
    featPriorityDesc: 'कम प्रतिस्पर्धा वाली छुपी हुई परीक्षाएं खोजें',
    aboutHeroSub: 'भारत का सरकारी परीक्षाओं के लिए मुफ्त करियर मार्गदर्शन मंच — क्योंकि हर उम्मीदवार एक स्पष्ट रास्ते का हकदार है।',
    aboutFounded: '2024 में स्थापित',
    ourMission: 'हमारा मिशन',
    missionP1: 'GovtExamPath एक सरल अवलोकन से पैदा हुआ: लाखों प्रतिभाशाली भारतीय सरकारी नौकरी के अवसरों से चूक जाते हैं क्योंकि उनके पास स्पष्ट, संगठित और विश्वसनीय परीक्षा जानकारी तक पहुंच नहीं है।',
    missionP2: 'हम सबसे व्यापक, मुफ्त और सुलभ मंच बना रहे हैं जो हर उम्मीदवार का मार्गदर्शन करता है।',
    whatWeOffer: 'हम क्या प्रदान करते हैं',
    whatWeOfferSub: 'आपकी सरकारी परीक्षा यात्रा के लिए व्यापक उपकरण और संसाधन',
    whyTrustUs: 'हम पर भरोसा क्यों करें',
    whyTrustUsSub: 'पारदर्शिता, सटीकता और आपकी सफलता को ध्यान में रखकर बनाया गया',
    ourTeam: 'हमारी टीम',
    ourTeamSub: 'GovtExamPath के पीछे के लोग',
    connectWithUs: 'हमसे जुड़ें',
    connectWithUsSub: 'दैनिक अपडेट के लिए सोशल मीडिया पर फॉलो करें',
    joinAspirants: 'हमारे उम्मीदवार समुदाय से जुड़ें',
    dreamJobTitle: 'आपकी सपनों की सरकारी नौकरी यहां से शुरू होती है',
    dreamJobSub: 'मुफ्त खाता बनाएं और व्यक्तिगत परीक्षा सिफारिशें, पात्रता जांच और तैयारी संसाधन प्राप्त करें।',
    trustOfficialSources: 'केवल आधिकारिक स्रोत',
    trustOfficialSourcesDesc: 'सभी परीक्षा डेटा आधिकारिक सरकारी वेबसाइटों से लिया गया है।',
    trustAlwaysUpdated: 'हमेशा अपडेटेड',
    trustAlwaysUpdatedDesc: 'हमारी टीम सूचनाओं की दैनिक निगरानी करती है।',
    trustFreeForever: 'हमेशा मुफ्त',
    trustFreeForeverDesc: 'मुख्य सुविधाएं हमेशा मुफ्त रहेंगी। कोई छिपे हुए शुल्क नहीं।',
    trustPrivacy: 'आपकी गोपनीयता पहले',
    trustPrivacyDesc: 'हम आपका डेटा कभी नहीं बेचते। न्यूनतम डेटा संग्रह, अधिकतम पारदर्शिता।',
    statStudentsGuided: 'छात्रों का मार्गदर्शन',
    statExamsCovered: 'परीक्षाएं कवर',
    statUpdates: 'दैनिक अपडेट',
    learnMore: 'और जानें',
    roleCEO: 'संस्थापक और CEO',
    roleTechLead: 'तकनीकी प्रमुख',
    roleContentHead: 'कंटेंट प्रमुख',
    teamBio1: 'सरकारी करियर जानकारी सभी के लिए सुलभ बनाने के प्रति समर्पित।',
    teamBio2: 'भारत भर के उम्मीदवारों को सशक्त बनाने के लिए स्केलेबल तकनीक बना रहे हैं।',
    teamBio3: 'सुनिश्चित करते हैं कि हर सामग्री सटीक, अद्यतित और उपयोगी हो।',
    aboutFeat1Desc: 'आपकी योग्यता और रुचियों के आधार पर AI-संचालित परीक्षा सिफारिशें।',
    aboutFeat2Desc: '200+ परीक्षाओं के लिए तुरंत अपनी पात्रता जांचें।',
    aboutFeat3Desc: 'प्रभावी अध्ययन योजना के लिए दृश्य सिलेबस विश्लेषण।',
    aboutFeat4Desc: 'साइट पर त्वरित नोट्स और आधिकारिक परीक्षा पोर्टल के लिंक।',
    aboutFeat5Desc: 'सभी सरकारी परीक्षाओं के लिए दैनिक समसामयिकी।',
    aboutFeat6Desc: 'सर्वोत्तम प्रतिस्पर्धा-से-रिक्ति अनुपात वाली छुपी हुई परीक्षाएं खोजें।',
    studyResources: 'अध्ययन सामग्री',
    expertBlog: 'विशेषज्ञ ब्लॉग',
    contactTitle: 'संपर्क करें',
    contactSubtitle: 'कोई सवाल? हमें संदेश भेजें, हम 24 घंटे में जवाब देंगे।',
    contactEmailLabel: 'ईमेल करें',
    contactResponseTime: 'जवाब का समय',
    contactResponseTimeVal: '24 घंटे के भीतर',
    contactLocationLabel: 'स्थान',
    contactSendMessage: 'हमें संदेश भेजें',
    contactMessageSent: 'संदेश भेजा गया!',
    contactThankYou: 'संपर्क करने के लिए धन्यवाद। हम 24 घंटे में जवाब देंगे।',
    contactYourName: 'आपका नाम',
    contactEnterName: 'अपना पूरा नाम दर्ज करें',
    contactEmailAddress: 'ईमेल पता',
    contactSubjectLabel: 'विषय',
    contactSelectTopic: 'विषय चुनें',
    contactGenQuestion: 'सामान्य प्रश्न',
    contactExamInfo: 'परीक्षा जानकारी',
    contactEligibilityQuery: 'पात्रता प्रश्न',
    contactReportBug: 'बग रिपोर्ट करें',
    contactFeatureRequest: 'सुविधा अनुरोध',
    contactFeedbackLabel: 'प्रतिक्रिया',
    contactMessageLabel: 'संदेश',
    contactTypeHere: 'अपना संदेश यहां लिखें...',
    contactSending: 'भेज रहे हैं...',
    contactSendBtn: 'संदेश भेजें',
    faqPageTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    faqSubtitle: 'सरकारी परीक्षाओं और हमारे मंच के बारे में सामान्य प्रश्नों के उत्तर',
    faqSearchPlaceholder: 'प्रश्न खोजें...',
    faqQuestionsLabel: 'प्रश्न',
    faqCategoriesLabel: 'श्रेणियां',
    faqUpdatedLabel: 'जून 2026 को अपडेट किया गया',
    faqCollapseAll: 'सभी बंद करें',
    faqExpandAll: 'सभी खोलें',
    faqNoResults: 'कोई मिलान प्रश्न नहीं मिला',
    faqTryDifferent: 'अलग कीवर्ड आज़माएं या श्रेणियां ब्राउज़ करें',
    faqStillHaveQ: 'अभी भी सवाल हैं?',
    faqStillHaveQSub: 'जो खोज रहे हैं वह नहीं मिला? हमसे संपर्क करें।',
    faqTabAll: 'सभी',
    faqTabGeneral: 'सामान्य',
    faqTabEligibility: 'पात्रता',
    faqTabPrep: 'तैयारी',
    faqTabApplication: 'आवेदन',
    faqTabSpecific: 'परीक्षा-विशिष्ट',
    faqSecGeneral: 'सामान्य प्रश्न',
    faqSecEligibility: 'पात्रता और आयु सीमा',
    faqSecPreparation: 'तैयारी रणनीति',
    faqSecApplication: 'आवेदन प्रक्रिया',
    faqSecSpecific: 'विशिष्ट परीक्षाएं और करियर',
    loginWelcomeBack: 'अपनी करियर यात्रा में वापस स्वागत है',
    loginWelcomeDesc: 'अपना व्यक्तिगत डैशबोर्ड, बुकमार्क परीक्षाएं एक्सेस करें और विशेषज्ञ मार्गदर्शन से तैयारी जारी रखें।',
    loginFeature1: 'अपनी बुकमार्क परीक्षाओं और समय सीमाओं को ट्रैक करें',
    loginFeature2: 'व्यक्तिगत परीक्षा सिफारिशें प्राप्त करें',
    loginFeature3: 'अध्ययन सामग्री और माइंड मैप एक्सेस करें',
    loginTitle: 'वापस स्वागत है',
    loginSubtitle: 'अपने GovtExamPath खाते में साइन इन करें',
    loginPassword: 'पासवर्ड',
    loginPasswordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    loginRememberMe: 'मुझे याद रखें',
    loginForgotPwd: 'पासवर्ड भूल गए?',
    loginSignIn: 'साइन इन',
    loginOr: 'या',
    loginNoAccount: 'खाता नहीं है?',
    loginCreateFree: 'मुफ्त खाता बनाएं',
    registerJourney: 'सरकारी करियर की यात्रा शुरू करें',
    registerJourneyDesc: 'अपना मुफ्त खाता बनाएं और व्यक्तिगत परीक्षा मार्गदर्शन, पात्रता जांच और तैयारी संसाधन अनलॉक करें।',
    registerFeature1: 'व्यक्तिगत करियर सिफारिशें',
    registerFeature2: '200+ परीक्षाओं के लिए तत्काल पात्रता जांच',
    registerFeature3: 'मुफ्त अध्ययन सामग्री और माइंड मैप',
    registerFeature4: 'रीयल-टाइम परीक्षा सूचनाएं',
    registerTitle: 'खाता बनाएं',
    registerSubtitle: 'GovtExamPath से जुड़ें - यह पूरी तरह मुफ्त है',
    registerFullName: 'पूरा नाम',
    registerFullNamePlaceholder: 'अपना पूरा नाम दर्ज करें',
    registerConfirmPwd: 'पासवर्ड की पुष्टि करें',
    registerConfirmPwdPlaceholder: 'पासवर्ड फिर से दर्ज करें',
    registerPwdMinChars: 'कम से कम 6 अक्षर',
    registerAgreeTerms: 'मैं सहमत हूं',
    registerTermsLink: 'सेवा की शर्तें',
    registerPrivacyLink: 'गोपनीयता नीति',
    registerCreateBtn: 'खाता बनाएं',
    registerAlreadyHave: 'पहले से खाता है?',
    registerSignInLink: 'साइन इन करें',
    pwdWeak: 'कमजोर',
    pwdFair: 'ठीक',
    pwdGood: 'अच्छा',
    pwdStrong: 'मजबूत',
    pwdVeryStrong: 'बहुत मजबूत',
    forgotPwdTitle: 'पासवर्ड भूल गए',
    forgotPwdSubtitle: 'रीसेट लिंक प्राप्त करने के लिए अपना ईमेल दर्ज करें',
    goodMorning: 'सुप्रभात',
    goodAfternoon: 'नमस्कार',
    goodEvening: 'शुभ संध्या',
    dashContinuePrep: 'अपनी परीक्षा तैयारी यात्रा जारी रखें। बुकमार्क परीक्षाएं जांचें, नए अवसर खोजें और नवीनतम सूचनाओं से अपडेट रहें।',
    dashSavedExams: 'सेव्ड परीक्षाएं',
    dashNewNotifs: 'नई सूचनाएं',
    dashActiveStatus: 'सक्रिय',
    dashAccountStatus: 'खाता स्थिति',
    dashLatestExams: 'नवीनतम परीक्षाएं',
    dashCareerGuideDesc: 'व्यक्तिगत परीक्षा सिफारिशें प्राप्त करें',
    dashEligibilityDesc: 'जांचें कि आप किन परीक्षाओं के योग्य हैं',
    dashPriorityDesc: 'सर्वोत्तम प्रतिस्पर्धा-से-रिक्ति अनुपात वाली परीक्षाएं खोजें',
    dashRecommended: 'अनुशंसित परीक्षाएं',
    dashRecentBookmarks: 'हाल के बुकमार्क',
    dashNoBookmarks: 'अभी तक कोई बुकमार्क नहीं। परीक्षाएं ब्राउज़ करें और जो पसंद हैं उन्हें बुकमार्क करें।',
    dashBrowseExams: 'परीक्षाएं ब्राउज़ करें',
    dashRecentNotifs: 'हाल की सूचनाएं',
    dashNoNotifs: 'अभी तक कोई सूचना नहीं। नई परीक्षाओं और समय सीमाओं के बारे में सूचित करेंगे।',
    dashUnableLoad: 'डैशबोर्ड लोड करने में असमर्थ',
    dashUnableLoadDesc: 'सर्वर से कनेक्ट करने में समस्या हुई। यह आमतौर पर बैकएंड सेवा अनुपलब्ध होने पर होता है।',
    dashRefresh: 'रीफ्रेश',
    dashViewAll: 'सभी देखें',
    bookmarksTitle: 'मेरे बुकमार्क',
    bookmarksSubtitle: 'बाद के लिए सेव की गई परीक्षाएं',
    bookmarksEmpty: 'अभी तक कोई बुकमार्क नहीं',
    bookmarksEmptyDesc: 'जिन परीक्षाओं में रुचि है उन्हें ट्रैक करने के लिए बुकमार्क करें।',
    profileTitle: 'मेरी प्रोफाइल',
    profileFullName: 'पूरा नाम',
    profileSaveChanges: 'बदलाव सेव करें',
    profileCancel: 'रद्द करें',
    profileEditProfile: 'प्रोफाइल संपादित करें',
    notifTitle: 'सूचनाएं',
    notifAllCaughtUp: 'सब अपडेट हैं!',
    notifUnread: 'अपठित सूचना',
    notifUnreadPlural: 'अपठित सूचनाएं',
    notifMarkAllRead: 'सभी को पढ़ा गया चिह्नित करें',
    notifFilterAll: 'सभी',
    notifFilterExamDates: 'परीक्षा तिथियां',
    notifFilterHallTickets: 'हॉल टिकट',
    notifFilterResults: 'परिणाम',
    notifFilterAnnouncements: 'घोषणाएं',
    notifFilterPlacements: 'प्लेसमेंट',
    notifFilterFeeReminders: 'शुल्क रिमाइंडर',
    notifFilterGeneral: 'सामान्य',
    notFoundPageDev: 'पेज विकास में है',
    notFoundPageDevDesc: 'यह श्रेणी पेज बनाया जा रहा है। इस बीच, सभी परीक्षाएं ब्राउज़ करें।',
    notFoundBrowseAll: 'सभी परीक्षाएं ब्राउज़ करें',
    notFound404: 'पेज नहीं मिला',
    notFoundDesc: 'जो पेज आप खोज रहे हैं वह मौजूद नहीं है या हटा दिया गया है।',
    notFoundBack: 'होम पर वापस',
    notFoundBrowse: 'परीक्षाएं ब्राउज़ करें',
    notFoundLooking: 'कुछ विशेष खोज रहे हैं?',
    notFoundResources: 'संसाधन',
    eligCheckerDesc: 'सेकंडों में जानें कि आप किन सरकारी परीक्षाओं के पात्र हैं',
    eligYourAge: 'आपकी आयु',
    eligEnterAge: 'अपनी आयु दर्ज करें',
    eligHighestQual: 'उच्चतम योग्यता',
    eligSelectQual: 'योग्यता चुनें',
    eligQual10: '10वीं पास',
    eligQual12: '12वीं पास',
    eligQualDiploma: 'डिप्लोमा (ITI/पॉलिटेक्निक)',
    eligQualGrad: 'स्नातक (B.A/B.Sc/B.Com/B.Tech आदि)',
    eligQualPG: 'स्नातकोत्तर (M.A/M.Sc/MBA/M.Tech आदि)',
    eligCatLabel: 'श्रेणी',
    eligCatGeneral: 'सामान्य',
    eligCatEWS: 'EWS (आर्थिक रूप से कमजोर वर्ग)',
    eligCatOBC: 'OBC (अन्य पिछड़ा वर्ग)',
    eligCatSC: 'SC (अनुसूचित जाति)',
    eligCatST: 'ST (अनुसूचित जनजाति)',
    eligCheckBtn: 'पात्रता जांचें',
    eligResultsFor: 'परिणाम: आयु',
    eligEligibleLabel: 'पात्र',
    eligAlmostLabel: 'लगभग पात्र',
    eligNotEligibleLabel: 'अपात्र',
    eligGetRecommend: 'करियर गाइड से व्यक्तिगत सिफारिशें प्राप्त करें',
    eligShowAllBtn: 'सभी दिखाएं',
    eligShowLess: 'कम दिखाएं',
    eligNotEligibleExams: 'अपात्र परीक्षाएं',
    examTabOverview: 'अवलोकन',
    examTabEligibility: 'पात्रता',
    examTabSyllabus: 'सिलेबस',
    examTabPattern: 'परीक्षा पैटर्न',
    examTabPYQ: 'पिछले वर्ष के प्रश्नपत्र',
    examTabSalary: 'वेतन और करियर',
    examTabApply: 'आवेदन कैसे करें',
    examNotFound: 'परीक्षा नहीं मिली',
    examNotFoundDesc: 'जो परीक्षा आप खोज रहे हैं वह मौजूद नहीं है या हटा दी गई है।',
    examBackToExams: 'परीक्षाओं पर वापस',
    examBack: 'वापस',
    examRelated: 'संबंधित परीक्षाएं',
  },
  te: {
    home: 'హోమ్',
    exams: 'పరీక్షలు',
    tools: 'సాధనాలు',
    resources: 'వనరులు',
    currentAffairs: 'కరెంట్ అఫైర్స్',
    blog: 'బ్లాగ్',
    login: 'లాగిన్',
    register: 'రిజిస్టర్',
    dashboard: 'డాష్‌బోర్డ్',
    profile: 'ప్రొఫైల్',
    bookmarks: 'బుక్‌మార్క్‌లు',
    notifications: 'నోటిఫికేషన్లు',
    logout: 'లాగౌట్',
    search: 'వెతకండి',
    searchExams: 'శీర్షిక, వర్గం ద్వారా పరీక్షలు వెతకండి...',
    browseExams: 'పరీక్షలు బ్రౌజ్ చేయండి',
    allExams: 'అన్ని పరీక్షలు',
    allCategories: 'అన్ని',
    openNow: 'ఇప్పుడు ఓపెన్',
    viewAll: 'అన్నీ చూడండి',
    exploreExams: 'పరీక్షలు అన్వేషించండి',
    careerGuide: 'కెరీర్ గైడ్',
    eligibilityChecker: 'అర్హత తనిఖీ',
    mindMaps: 'మైండ్ మ్యాప్స్',
    freeResources: 'వనరుల కేంద్రం',
    examCalendar: 'పరీక్ష క్యాలెండర్',
    examPriority: 'పరీక్ష ప్రాధాన్యత మ్యాట్రిక్స్',
    prepRoadmap: 'తయారీ రోడ్‌మ్యాప్',
    cutOff: 'కట్-ఆఫ్ మార్కులు',
    compareExams: 'పరీక్షలు పోల్చండి',
    prepTime: 'తయారీ సమయ అంచనా',
    salaryCalc: 'జీతం కాల్క్యులేటర్',
    about: 'మా గురించి',
    aboutUs: 'మా గురించి',
    contact: 'సంప్రదించండి',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'సేవా నిబంధనలు',
    disclaimer: 'నిరాకరణ',
    faq: 'తరచుగా అడిగే ప్రశ్నలు',
    getStarted: 'ఉచితంగా ప్రారంభించండి',
    subscribe: 'సబ్‌స్క్రైబ్',
    readMore: 'మరింత చదవండి',
    latestExams: 'తాజా పరీక్షలు',
    successStories: 'విజయ గాథలు',
    free: 'ఉచితం',
    students: 'విద్యార్థులు',
    categories: 'వర్గాలు',
    examCategories: 'పరీక్ష వర్గాలు',
    language: 'భాష',
    hindi: 'హిందీ',
    english: 'English',
    quickLinks: 'త్వరిత లింకులు',
    contactNewsletter: 'సంప్రదింపు & న్యూస్‌లెటర్',
    weeklyUpdates: 'వారపు పరీక్ష అప్‌డేట్లు పొందండి',
    yourEmail: 'మీ ఇమెయిల్',
    subscribedSuccess: 'విజయవంతంగా సబ్‌స్క్రైబ్ చేసారు!',
    copyright: 'అన్ని హక్కులు సురక్షితం. భారతదేశ భవిష్యత్ సివిల్ సర్వెంట్ల కోసం నిర్మించబడింది.',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    policies: 'విధానాలు',
    homeBadge: 'ప్రభుత్వ ఉద్యోగాలకు ఉచిత కెరీర్ మార్గదర్శకత్వం',
    heroTitle: 'మీ మార్గం',
    heroSubtitle: '200+ ప్రభుత్వ పరీక్షలు, అర్హత తనిఖీ మరియు ఉచిత తయారీ వనరులు.',
    statExams: 'పరీక్షలు',
    statStudents: 'విద్యార్థులు',
    statFree: 'ఉచితం',
    closingSoon: 'త్వరలో మూసివేయబడుతోంది',
    browseByCat: 'వర్గం ప్రకారం బ్రౌజ్ చేయండి',
    browseByCatSub: '16 రంగాలు, 200+ పరీక్షలు — మీ మార్గం కనుగొనండి',
    viewAllCats: 'అన్ని వర్గాలు చూడండి',
    freeToolsTitle: 'ఉచిత సాధనాలు & ఫీచర్లు',
    freeToolsSub: 'సరైన ప్రభుత్వ పరీక్ష కనుగొనడానికి మీకు కావలసినదంతా',
    dailyPractice: 'రోజువారీ ప్రాక్టీస్ క్విజ్',
    todayQuiz: 'నేటి క్విక్ క్విజ్',
    checkAnswers: 'సమాధానాలు తనిఖీ చేయండి',
    youScored: 'మీ స్కోరు',
    morePractice: 'మరింత ప్రాక్టీస్',
    whatStudentsSay: 'విద్యార్థులు ఏమంటున్నారు',
    readyToStart: 'మీ ప్రయాణం ప్రారంభించడానికి సిద్ధంగా ఉన్నారా?',
    readyToStartSub: 'GovtExamPath ఉపయోగించే వేలాది ఆశావహులతో చేరండి.',
    subscribedCheck: 'మీరు సిద్ధంగా ఉన్నారు!',
    examUpdatesEmail: 'వారపు పరీక్ష అప్‌డేట్లు & చిట్కాలు పొందండి',
    featCareerGuideDesc: 'మీ ప్రొఫైల్ ఆధారంగా వ్యక్తిగత పరీక్ష సిఫార్సులు',
    featEligibilityDesc: 'మీరు ఏ పరీక్షలకు అర్హులో తెలుసుకోండి',
    featMindMapsDesc: 'సమర్థ అధ్యయన ప్రణాళిక కోసం దృశ్య విశ్లేషణ',
    featResourcesDesc: 'సైట్‌లో త్వరిత నోట్స్ + అధికారిక పరీక్ష పోర్టల్ లింకులు',
    featCurrentAffairsDesc: 'అన్ని పరీక్షలకు 150+ రోజువారీ నవీకరణ వ్యాసాలు',
    featPriorityDesc: 'తక్కువ పోటీ ఉన్న దాచిన పరీక్షలు కనుగొనండి',
    aboutHeroSub: 'భారతదేశపు ప్రభుత్వ పరీక్షల కోసం ఉచిత కెరీర్ మార్గదర్శక వేదిక.',
    aboutFounded: '2024లో స్థాపించబడింది',
    ourMission: 'మా మిషన్',
    missionP1: 'లక్షల మంది భారతీయులు స్పష్టమైన పరీక్ష సమాచారం అందుబాటులో లేకపోవడం వల్ల ప్రభుత్వ ఉద్యోగ అవకాశాలను కోల్పోతున్నారు.',
    missionP2: 'ప్రతి ఆశావహుడికి మార్గదర్శకత్వం చేసే సమగ్ర, ఉచిత వేదికను నిర్మిస్తున్నాము.',
    whatWeOffer: 'మేము ఏమి అందిస్తాము',
    whatWeOfferSub: 'మీ ప్రభుత్వ పరీక్ష ప్రయాణానికి సమగ్ర సాధనాలు',
    whyTrustUs: 'మాపై ఎందుకు నమ్మకం',
    whyTrustUsSub: 'పారదర్శకత, ఖచ్చితత్వం మరియు మీ విజయం దృష్టిలో పెట్టుకుని నిర్మించబడింది',
    ourTeam: 'మా టీమ్',
    ourTeamSub: 'GovtExamPath వెనుక ఉన్న వ్యక్తులు',
    connectWithUs: 'మాతో కనెక్ట్ అవ్వండి',
    connectWithUsSub: 'రోజువారీ అప్‌డేట్ల కోసం మమ్మల్ని ఫాలో చేయండి',
    joinAspirants: 'మా ఆశావహుల సమాజంలో చేరండి',
    dreamJobTitle: 'మీ కల ప్రభుత్వ ఉద్యోగం ఇక్కడ మొదలవుతుంది',
    dreamJobSub: 'ఉచిత ఖాతా సృష్టించండి మరియు వ్యక్తిగత పరీక్ష సిఫార్సులు పొందండి.',
    trustOfficialSources: 'అధికారిక మూలాలు మాత్రమే',
    trustOfficialSourcesDesc: 'అన్ని పరీక్ష డేటా అధికారిక ప్రభుత్వ వెబ్‌సైట్ల నుండి సేకరించబడింది.',
    trustAlwaysUpdated: 'ఎల్లప్పుడూ నవీకరించబడింది',
    trustAlwaysUpdatedDesc: 'మా బృందం రోజువారీ నోటిఫికేషన్లను పర్యవేక్షిస్తుంది.',
    trustFreeForever: 'ఎల్లప్పుడూ ఉచితం',
    trustFreeForeverDesc: 'ప్రధాన ఫీచర్లు ఎల్లప్పుడూ ఉచితంగా ఉంటాయి. దాచిన ఛార్జీలు లేవు.',
    trustPrivacy: 'మీ గోప్యత మొదట',
    trustPrivacyDesc: 'మేము మీ డేటాను ఎప్పుడూ విక్రయించము.',
    statStudentsGuided: 'మార్గదర్శకత్వం పొందిన విద్యార్థులు',
    statExamsCovered: 'కవర్ చేయబడిన పరీక్షలు',
    statUpdates: 'రోజువారీ అప్‌డేట్లు',
    learnMore: 'మరింత తెలుసుకోండి',
    roleCEO: 'వ్యవస్థాపకుడు & CEO',
    roleTechLead: 'టెక్ లీడ్',
    roleContentHead: 'కంటెంట్ హెడ్',
    teamBio1: 'ప్రభుత్వ కెరీర్ సమాచారాన్ని అందరికీ అందుబాటులో చేయడం పట్ల అంకితభావం.',
    teamBio2: 'భారతదేశమంతటా ఆశావహులకు స్కేలబుల్ టెక్నాలజీ నిర్మిస్తున్నారు.',
    teamBio3: 'ప్రతి కంటెంట్ ఖచ్చితమైనది, తాజాది మరియు ఉపయోగకరమైనదని నిర్ధారిస్తారు.',
    aboutFeat1Desc: 'మీ అర్హతల ఆధారంగా AI-ఆధారిత పరీక్ష సిఫార్సులు.',
    aboutFeat2Desc: '200+ పరీక్షలకు మీ అర్హతను తక్షణమే తనిఖీ చేయండి.',
    aboutFeat3Desc: 'సమర్థ అధ్యయన ప్రణాళిక కోసం దృశ్య సిలబస్ విశ్లేషణ.',
    aboutFeat4Desc: 'సైట్‌లో త్వరిత నోట్స్ మరియు అధికారిక పరీక్ష పోర్టల్ లింకులు.',
    aboutFeat5Desc: 'అన్ని ప్రభుత్వ పరీక్షలకు రోజువారీ కరెంట్ అఫైర్స్.',
    aboutFeat6Desc: 'ఉత్తమ పోటీ-నుండి-ఖాళీ నిష్పత్తి ఉన్న దాచిన పరీక్షలు కనుగొనండి.',
    studyResources: 'అధ్యయన వనరులు',
    expertBlog: 'నిపుణుల బ్లాగ్',
    contactTitle: 'సంప్రదించండి',
    contactSubtitle: 'ప్రశ్న ఉందా? మాకు సందేశం పంపండి, 24 గంటల్లో సమాధానం ఇస్తాము.',
    contactEmailLabel: 'ఇమెయిల్ చేయండి',
    contactResponseTime: 'సమాధాన సమయం',
    contactResponseTimeVal: '24 గంటల్లో',
    contactLocationLabel: 'లొకేషన్',
    contactSendMessage: 'సందేశం పంపండి',
    contactMessageSent: 'సందేశం పంపబడింది!',
    contactThankYou: 'సంప్రదించినందుకు ధన్యవాదాలు. 24 గంటల్లో సమాధానం ఇస్తాము.',
    contactYourName: 'మీ పేరు',
    contactEnterName: 'మీ పూర్తి పేరు నమోదు చేయండి',
    contactEmailAddress: 'ఇమెయిల్ చిరునామా',
    contactSubjectLabel: 'విషయం',
    contactSelectTopic: 'అంశం ఎంచుకోండి',
    contactGenQuestion: 'సాధారణ ప్రశ్న',
    contactExamInfo: 'పరీక్ష సమాచారం',
    contactEligibilityQuery: 'అర్హత ప్రశ్న',
    contactReportBug: 'బగ్ రిపోర్ట్ చేయండి',
    contactFeatureRequest: 'ఫీచర్ అభ్యర్థన',
    contactFeedbackLabel: 'ఫీడ్‌బ్యాక్',
    contactMessageLabel: 'సందేశం',
    contactTypeHere: 'మీ సందేశం ఇక్కడ టైప్ చేయండి...',
    contactSending: 'పంపుతోంది...',
    contactSendBtn: 'సందేశం పంపండి',
    faqPageTitle: 'తరచుగా అడిగే ప్రశ్నలు',
    faqSubtitle: 'ప్రభుత్వ పరీక్షలు మరియు మా వేదిక గురించి సాధారణ ప్రశ్నలకు సమాధానాలు',
    faqSearchPlaceholder: 'ప్రశ్నలు వెతకండి...',
    faqQuestionsLabel: 'ప్రశ్నలు',
    faqCategoriesLabel: 'వర్గాలు',
    faqUpdatedLabel: 'జూన్ 2026 నవీకరించబడింది',
    faqCollapseAll: 'అన్నీ మూయండి',
    faqExpandAll: 'అన్నీ తెరవండి',
    faqNoResults: 'సరిపోలే ప్రశ్నలు కనుగొనబడలేదు',
    faqTryDifferent: 'వేరే కీవర్డ్‌లు ప్రయత్నించండి',
    faqStillHaveQ: 'ఇంకా ప్రశ్నలు ఉన్నాయా?',
    faqStillHaveQSub: 'కనుగొనలేకపోతున్నారా? మమ్మల్ని సంప్రదించండి.',
    faqTabAll: 'అన్ని',
    faqTabGeneral: 'సాధారణ',
    faqTabEligibility: 'అర్హత',
    faqTabPrep: 'తయారీ',
    faqTabApplication: 'దరఖాస్తు',
    faqTabSpecific: 'పరీక్ష-నిర్దిష్ట',
    faqSecGeneral: 'సాధారణ ప్రశ్నలు',
    faqSecEligibility: 'అర్హత & వయో పరిమితులు',
    faqSecPreparation: 'తయారీ వ్యూహం',
    faqSecApplication: 'దరఖాస్తు ప్రక్రియ',
    faqSecSpecific: 'నిర్దిష్ట పరీక్షలు & కెరీర్లు',
    loginWelcomeBack: 'మీ కెరీర్ ప్రయాణంలో తిరిగి స్వాగతం',
    loginWelcomeDesc: 'మీ వ్యక్తిగత డాష్‌బోర్డ్, బుక్‌మార్క్ పరీక్షలను యాక్సెస్ చేయండి.',
    loginFeature1: 'మీ బుక్‌మార్క్ పరీక్షలు మరియు గడువులను ట్రాక్ చేయండి',
    loginFeature2: 'వ్యక్తిగత పరీక్ష సిఫార్సులు పొందండి',
    loginFeature3: 'అధ్యయన వనరులు మరియు మైండ్ మ్యాప్‌లను యాక్సెస్ చేయండి',
    loginTitle: 'తిరిగి స్వాగతం',
    loginSubtitle: 'మీ GovtExamPath ఖాతాలో సైన్ ఇన్ చేయండి',
    loginPassword: 'పాస్‌వర్డ్',
    loginPasswordPlaceholder: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    loginRememberMe: 'నన్ను గుర్తుంచుకో',
    loginForgotPwd: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    loginSignIn: 'సైన్ ఇన్',
    loginOr: 'లేదా',
    loginNoAccount: 'ఖాతా లేదా?',
    loginCreateFree: 'ఉచితంగా ఒకటి సృష్టించండి',
    registerJourney: 'ప్రభుత్వ కెరీర్ ప్రయాణం ప్రారంభించండి',
    registerJourneyDesc: 'మీ ఉచిత ఖాతాను సృష్టించి వ్యక్తిగత పరీక్ష మార్గదర్శకత్వం అన్‌లాక్ చేయండి.',
    registerFeature1: 'వ్యక్తిగత కెరీర్ సిఫార్సులు',
    registerFeature2: '200+ పరీక్షలకు తక్షణ అర్హత తనిఖీ',
    registerFeature3: 'ఉచిత అధ్యయన వనరులు మరియు మైండ్ మ్యాప్‌లు',
    registerFeature4: 'రియల్-టైమ్ పరీక్ష నోటిఫికేషన్లు',
    registerTitle: 'ఖాతా సృష్టించండి',
    registerSubtitle: 'GovtExamPath లో చేరండి - ఇది పూర్తిగా ఉచితం',
    registerFullName: 'పూర్తి పేరు',
    registerFullNamePlaceholder: 'మీ పూర్తి పేరు నమోదు చేయండి',
    registerConfirmPwd: 'పాస్‌వర్డ్ నిర్ధారించండి',
    registerConfirmPwdPlaceholder: 'పాస్‌వర్డ్ మళ్ళీ నమోదు చేయండి',
    registerPwdMinChars: 'కనీసం 6 అక్షరాలు',
    registerAgreeTerms: 'నేను అంగీకరిస్తున్నాను',
    registerTermsLink: 'సేవా నిబంధనలు',
    registerPrivacyLink: 'గోప్యతా విధానం',
    registerCreateBtn: 'ఖాతా సృష్టించండి',
    registerAlreadyHave: 'ఇప్పటికే ఖాతా ఉందా?',
    registerSignInLink: 'సైన్ ఇన్ చేయండి',
    pwdWeak: 'బలహీనం',
    pwdFair: 'సరే',
    pwdGood: 'మంచిది',
    pwdStrong: 'బలమైనది',
    pwdVeryStrong: 'చాలా బలమైనది',
    forgotPwdTitle: 'పాస్‌వర్డ్ మర్చిపోయారా',
    forgotPwdSubtitle: 'రీసెట్ లింక్ పొందడానికి మీ ఇమెయిల్ నమోదు చేయండి',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    dashContinuePrep: 'మీ పరీక్ష తయారీ ప్రయాణం కొనసాగించండి.',
    dashSavedExams: 'సేవ్ చేసిన పరీక్షలు',
    dashNewNotifs: 'కొత్త నోటిఫికేషన్లు',
    dashActiveStatus: 'యాక్టివ్',
    dashAccountStatus: 'ఖాతా స్థితి',
    dashLatestExams: 'తాజా పరీక్షలు',
    dashCareerGuideDesc: 'వ్యక్తిగత పరీక్ష సిఫార్సులు పొందండి',
    dashEligibilityDesc: 'మీరు ఏ పరీక్షలకు అర్హులో తనిఖీ చేయండి',
    dashPriorityDesc: 'ఉత్తమ పోటీ-నుండి-ఖాళీ నిష్పత్తి ఉన్న పరీక్షలు కనుగొనండి',
    dashRecommended: 'సిఫార్సు చేయబడిన పరీక్షలు',
    dashRecentBookmarks: 'ఇటీవలి బుక్‌మార్క్‌లు',
    dashNoBookmarks: 'ఇంకా బుక్‌మార్క్‌లు లేవు. పరీక్షలు బ్రౌజ్ చేసి బుక్‌మార్క్ చేయండి.',
    dashBrowseExams: 'పరీక్షలు బ్రౌజ్ చేయండి',
    dashRecentNotifs: 'ఇటీవలి నోటిఫికేషన్లు',
    dashNoNotifs: 'ఇంకా నోటిఫికేషన్లు లేవు. కొత్త పరీక్షలు మరియు గడువుల గురించి తెలియజేస్తాము.',
    dashUnableLoad: 'డాష్‌బోర్డ్ లోడ్ చేయలేకపోయాము',
    dashUnableLoadDesc: 'సర్వర్‌కు కనెక్ట్ చేయడంలో సమస్య.',
    dashRefresh: 'రిఫ్రెష్',
    dashViewAll: 'అన్నీ చూడండి',
    bookmarksTitle: 'నా బుక్‌మార్క్‌లు',
    bookmarksSubtitle: 'తర్వాత కోసం సేవ్ చేసిన పరీక్షలు',
    bookmarksEmpty: 'ఇంకా బుక్‌మార్క్‌లు లేవు',
    bookmarksEmptyDesc: 'ఆసక్తి ఉన్న పరీక్షలను ట్రాక్ చేయడానికి బుక్‌మార్క్ చేయండి.',
    profileTitle: 'నా ప్రొఫైల్',
    profileFullName: 'పూర్తి పేరు',
    profileSaveChanges: 'మార్పులు సేవ్ చేయండి',
    profileCancel: 'రద్దు',
    profileEditProfile: 'ప్రొఫైల్ ఎడిట్ చేయండి',
    notifTitle: 'నోటిఫికేషన్లు',
    notifAllCaughtUp: 'అన్నీ అప్‌డేట్!',
    notifUnread: 'చదవని నోటిఫికేషన్',
    notifUnreadPlural: 'చదవని నోటిఫికేషన్లు',
    notifMarkAllRead: 'అన్నీ చదివినట్లు మార్క్ చేయండి',
    notifFilterAll: 'అన్ని',
    notifFilterExamDates: 'పరీక్ష తేదీలు',
    notifFilterHallTickets: 'హాల్ టిక్కెట్లు',
    notifFilterResults: 'ఫలితాలు',
    notifFilterAnnouncements: 'ప్రకటనలు',
    notifFilterPlacements: 'ప్లేస్‌మెంట్లు',
    notifFilterFeeReminders: 'ఫీజు రిమైండర్లు',
    notifFilterGeneral: 'సాధారణ',
    notFoundPageDev: 'పేజీ అభివృద్ధిలో ఉంది',
    notFoundPageDevDesc: 'ఈ వర్గ పేజీ నిర్మించబడుతోంది. ఈ సమయంలో, అన్ని పరీక్షలు బ్రౌజ్ చేయండి.',
    notFoundBrowseAll: 'అన్ని పరీక్షలు బ్రౌజ్ చేయండి',
    notFound404: 'పేజీ కనుగొనబడలేదు',
    notFoundDesc: 'మీరు వెతుకుతున్న పేజీ ఉనికిలో లేదు.',
    notFoundBack: 'హోమ్‌కు తిరిగి',
    notFoundBrowse: 'పరీక్షలు బ్రౌజ్ చేయండి',
    notFoundLooking: 'ఏదైనా నిర్దిష్టంగా వెతుకుతున్నారా?',
    notFoundResources: 'వనరులు',
    eligCheckerDesc: 'సెకన్లలో మీరు ఏ ప్రభుత్వ పరీక్షలకు అర్హులో తెలుసుకోండి',
    eligYourAge: 'మీ వయసు',
    eligEnterAge: 'మీ వయసు నమోదు చేయండి',
    eligHighestQual: 'అత్యున్నత అర్హత',
    eligSelectQual: 'అర్హత ఎంచుకోండి',
    eligQual10: '10వ తరగతి పాస్',
    eligQual12: '12వ తరగతి పాస్',
    eligQualDiploma: 'డిప్లొమా (ITI/పాలిటెక్నిక్)',
    eligQualGrad: 'గ్రాడ్యుయేషన్ (B.A/B.Sc/B.Com/B.Tech మొ.)',
    eligQualPG: 'పోస్ట్ గ్రాడ్యుయేషన్ (M.A/M.Sc/MBA/M.Tech మొ.)',
    eligCatLabel: 'వర్గం',
    eligCatGeneral: 'జనరల్',
    eligCatEWS: 'EWS (ఆర్థికంగా బలహీన వర్గం)',
    eligCatOBC: 'OBC (ఇతర వెనుకబడిన తరగతులు)',
    eligCatSC: 'SC (షెడ్యూల్డ్ కాస్ట్)',
    eligCatST: 'ST (షెడ్యూల్డ్ ట్రైబ్)',
    eligCheckBtn: 'అర్హత తనిఖీ చేయండి',
    eligResultsFor: 'ఫలితాలు: వయసు',
    eligEligibleLabel: 'అర్హులు',
    eligAlmostLabel: 'దాదాపు అర్హులు',
    eligNotEligibleLabel: 'అనర్హులు',
    eligGetRecommend: 'కెరీర్ గైడ్ నుండి వ్యక్తిగత సిఫార్సులు పొందండి',
    eligShowAllBtn: 'అన్నీ చూపించు',
    eligShowLess: 'తక్కువ చూపించు',
    eligNotEligibleExams: 'అనర్హ పరీక్షలు',
    examTabOverview: 'అవలోకనం',
    examTabEligibility: 'అర్హత',
    examTabSyllabus: 'సిలబస్',
    examTabPattern: 'పరీక్ష పద్ధతి',
    examTabPYQ: 'గత సంవత్సరం ప్రశ్నపత్రాలు',
    examTabSalary: 'జీతం & కెరీర్',
    examTabApply: 'దరఖాస్తు ఎలా చేయాలి',
    examNotFound: 'పరీక్ష కనుగొనబడలేదు',
    examNotFoundDesc: 'మీరు వెతుకుతున్న పరీక్ష ఉనికిలో లేదు లేదా తొలగించబడింది.',
    examBackToExams: 'పరీక్షలకు తిరిగి',
    examBack: 'వెనుకకు',
    examRelated: 'సంబంధిత పరీక్షలు',
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    exams: 'ಪರೀಕ್ಷೆಗಳು',
    tools: 'ಉಪಕರಣಗಳು',
    resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    currentAffairs: 'ಪ್ರಚಲಿತ ವಿದ್ಯಮಾನಗಳು',
    blog: 'ಬ್ಲಾಗ್',
    login: 'ಲಾಗಿನ್',
    register: 'ನೋಂದಣಿ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    profile: 'ಪ್ರೊಫೈಲ್',
    bookmarks: 'ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    logout: 'ಲಾಗೌಟ್',
    search: 'ಹುಡುಕಿ',
    searchExams: 'ಶೀರ್ಷಿಕೆ, ವರ್ಗದಿಂದ ಪರೀಕ್ಷೆಗಳನ್ನು ಹುಡುಕಿ...',
    browseExams: 'ಪರೀಕ್ಷೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    allExams: 'ಎಲ್ಲಾ ಪರೀಕ್ಷೆಗಳು',
    allCategories: 'ಎಲ್ಲಾ',
    openNow: 'ಈಗ ತೆರೆದಿದೆ',
    viewAll: 'ಎಲ್ಲಾ ನೋಡಿ',
    exploreExams: 'ಪರೀಕ್ಷೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    careerGuide: 'ಕೆರಿಯರ್ ಗೈಡ್',
    eligibilityChecker: 'ಅರ್ಹತೆ ಪರಿಶೀಲಕ',
    mindMaps: 'ಮೈಂಡ್ ಮ್ಯಾಪ್ಸ್',
    freeResources: 'ಸಂಪನ್ಮೂಲ ಕೇಂದ್ರ',
    examCalendar: 'ಪರೀಕ್ಷೆ ಕ್ಯಾಲೆಂಡರ್',
    examPriority: 'ಪರೀಕ್ಷೆ ಆದ್ಯತೆ ಮ್ಯಾಟ್ರಿಕ್ಸ್',
    about: 'ನಮ್ಮ ಬಗ್ಗೆ',
    aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
    contact: 'ಸಂಪರ್ಕಿಸಿ',
    faq: 'FAQ',
    getStarted: 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    subscribe: 'ಸಬ್‌ಸ್ಕ್ರೈಬ್',
    readMore: 'ಇನ್ನಷ್ಟು ಓದಿ',
    free: 'ಉಚಿತ',
    students: 'ವಿದ್ಯಾರ್ಥಿಗಳು',
    categories: 'ವರ್ಗಗಳು',
    quickLinks: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    weeklyUpdates: 'ವಾರದ ಪರೀಕ್ಷೆ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ',
    yourEmail: 'ನಿಮ್ಮ ಇಮೇಲ್',
    copyright: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ. ಭಾರತದ ಭವಿಷ್ಯದ ನಾಗರಿಕ ಸೇವಕರಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
    homeBadge: 'ಸರ್ಕಾರಿ ಉದ್ಯೋಗಗಳಿಗೆ ಉಚಿತ ಕೆರಿಯರ್ ಮಾರ್ಗದರ್ಶನ',
    heroTitle: 'ನಿಮ್ಮ ಮಾರ್ಗ',
    heroSubtitle: '200+ ಸರ್ಕಾರಿ ಪರೀಕ್ಷೆಗಳು, ಅರ್ಹತೆ ಪರಿಶೀಲನೆ ಮತ್ತು ಉಚಿತ ತಯಾರಿ ಸಂಪನ್ಮೂಲಗಳು.',
    statExams: 'ಪರೀಕ್ಷೆಗಳು',
    statStudents: 'ವಿದ್ಯಾರ್ಥಿಗಳು',
    statFree: 'ಉಚಿತ',
    closingSoon: 'ಶೀಘ್ರದಲ್ಲೇ ಮುಕ್ತಾಯ',
    browseByCat: 'ವರ್ಗದ ಪ್ರಕಾರ ಬ್ರೌಸ್ ಮಾಡಿ',
    browseByCatSub: '16 ಕ್ಷೇತ್ರಗಳು, 200+ ಪರೀಕ್ಷೆಗಳು — ನಿಮ್ಮ ಮಾರ್ಗ ಹುಡುಕಿ',
    viewAllCats: 'ಎಲ್ಲಾ ವರ್ಗಗಳನ್ನು ನೋಡಿ',
    freeToolsTitle: 'ಉಚಿತ ಉಪಕರಣಗಳು & ವೈಶಿಷ್ಟ್ಯಗಳು',
    freeToolsSub: 'ಸರಿಯಾದ ಸರ್ಕಾರಿ ಪರೀಕ್ಷೆ ಕಂಡುಕೊಳ್ಳಲು ನಿಮಗೆ ಬೇಕಾದ ಎಲ್ಲವೂ',
    featCareerGuideDesc: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಆಧಾರಿತ ವೈಯಕ್ತಿಕ ಪರೀಕ್ಷೆ ಶಿಫಾರಸುಗಳು',
    featEligibilityDesc: 'ನೀವು ಯಾವ ಪರೀಕ್ಷೆಗಳಿಗೆ ಅರ್ಹರು ಎಂದು ತಿಳಿಯಿರಿ',
    featMindMapsDesc: 'ಪರಿಣಾಮಕಾರಿ ಅಧ್ಯಯನ ಯೋಜನೆಗೆ ದೃಶ್ಯ ವಿಶ್ಲೇಷಣೆ',
    featResourcesDesc: 'ಸೈಟ್‌ನಲ್ಲಿ ತ್ವರಿತ ಟಿಪ್ಪಣಿಗಳು + ಅಧಿಕೃತ ಪರೀಕ್ಷೆ ಪೋರ್ಟಲ್ ಲಿಂಕ್‌ಗಳು',
    featCurrentAffairsDesc: 'ಎಲ್ಲಾ ಪರೀಕ್ಷೆಗಳಿಗೆ 150+ ದೈನಿಕ ನವೀಕರಣ ಲೇಖನಗಳು',
    featPriorityDesc: 'ಕಡಿಮೆ ಸ್ಪರ್ಧೆ ಇರುವ ಗುಪ್ತ ಪರೀಕ್ಷೆಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ',
    ourMission: 'ನಮ್ಮ ಮಿಷನ್',
    whatWeOffer: 'ನಾವು ಏನು ನೀಡುತ್ತೇವೆ',
    whyTrustUs: 'ನಮ್ಮನ್ನು ಏಕೆ ನಂಬಬೇಕು',
    ourTeam: 'ನಮ್ಮ ತಂಡ',
    connectWithUs: 'ನಮ್ಮೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ',
    contactTitle: 'ಸಂಪರ್ಕಿಸಿ',
    contactSubtitle: 'ಪ್ರಶ್ನೆ ಇದೆಯೇ? ನಮಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ.',
    contactEmailLabel: 'ಇಮೇಲ್ ಮಾಡಿ',
    contactSendMessage: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    contactMessageSent: 'ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ!',
    contactThankYou: 'ಸಂಪರ್ಕಿಸಿದ್ದಕ್ಕೆ ಧನ್ಯವಾದಗಳು. 24 ಗಂಟೆಗಳಲ್ಲಿ ಉತ್ತರಿಸುತ್ತೇವೆ.',
    contactYourName: 'ನಿಮ್ಮ ಹೆಸರು',
    contactEnterName: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    contactEmailAddress: 'ಇಮೇಲ್ ವಿಳಾಸ',
    contactSubjectLabel: 'ವಿಷಯ',
    contactSelectTopic: 'ವಿಷಯ ಆಯ್ಕೆಮಾಡಿ',
    contactGenQuestion: 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆ',
    contactExamInfo: 'ಪರೀಕ್ಷೆ ಮಾಹಿತಿ',
    contactEligibilityQuery: 'ಅರ್ಹತೆ ಪ್ರಶ್ನೆ',
    contactReportBug: 'ಬಗ್ ವರದಿ ಮಾಡಿ',
    contactFeatureRequest: 'ವೈಶಿಷ್ಟ್ಯ ವಿನಂತಿ',
    contactFeedbackLabel: 'ಪ್ರತಿಕ್ರಿಯೆ',
    contactMessageLabel: 'ಸಂದೇಶ',
    contactTypeHere: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
    contactSending: 'ಕಳುಹಿಸುತ್ತಿದೆ...',
    contactSendBtn: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
    contactResponseTime: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯ',
    contactResponseTimeVal: '24 ಗಂಟೆಗಳಲ್ಲಿ',
    contactLocationLabel: 'ಸ್ಥಳ',
    faqPageTitle: 'ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು',
    faqSubtitle: 'ಸರ್ಕಾರಿ ಪರೀಕ್ಷೆಗಳು ಮತ್ತು ನಮ್ಮ ವೇದಿಕೆ ಬಗ್ಗೆ ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಗಳು',
    faqSearchPlaceholder: 'ಪ್ರಶ್ನೆಗಳನ್ನು ಹುಡುಕಿ...',
    faqTabAll: 'ಎಲ್ಲಾ',
    faqTabGeneral: 'ಸಾಮಾನ್ಯ',
    faqTabEligibility: 'ಅರ್ಹತೆ',
    faqTabPrep: 'ತಯಾರಿ',
    faqTabApplication: 'ಅರ್ಜಿ',
    faqTabSpecific: 'ಪರೀಕ್ಷೆ-ನಿರ್ದಿಷ್ಟ',
    faqSecGeneral: 'ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು',
    faqSecEligibility: 'ಅರ್ಹತೆ & ವಯಸ್ಸಿನ ಮಿತಿಗಳು',
    faqSecPreparation: 'ತಯಾರಿ ಕಾರ್ಯತಂತ್ರ',
    faqSecApplication: 'ಅರ್ಜಿ ಪ್ರಕ್ರಿಯೆ',
    faqSecSpecific: 'ನಿರ್ದಿಷ್ಟ ಪರೀಕ್ಷೆಗಳು & ವೃತ್ತಿಜೀವನ',
    faqQuestionsLabel: 'ಪ್ರಶ್ನೆಗಳು',
    faqCategoriesLabel: 'ವರ್ಗಗಳು',
    faqCollapseAll: 'ಎಲ್ಲಾ ಮುಚ್ಚಿ',
    faqExpandAll: 'ಎಲ್ಲಾ ತೆರೆಯಿರಿ',
    faqNoResults: 'ಹೊಂದಾಣಿಕೆಯ ಪ್ರಶ್ನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    faqStillHaveQ: 'ಇನ್ನೂ ಪ್ರಶ್ನೆಗಳಿವೆಯೇ?',
    loginWelcomeBack: 'ನಿಮ್ಮ ಕೆರಿಯರ್ ಪ್ರಯಾಣಕ್ಕೆ ಮರಳಿ ಸ್ವಾಗತ',
    loginWelcomeDesc: 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಮತ್ತು ಬುಕ್‌ಮಾರ್ಕ್ ಪರೀಕ್ಷೆಗಳನ್ನು ಪ್ರವೇಶಿಸಿ.',
    loginFeature1: 'ನಿಮ್ಮ ಬುಕ್‌ಮಾರ್ಕ್ ಪರೀಕ್ಷೆಗಳು ಮತ್ತು ಗಡುವುಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    loginFeature2: 'ವೈಯಕ್ತಿಕ ಪರೀಕ್ಷೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ',
    loginFeature3: 'ಅಧ್ಯಯನ ಸಂಪನ್ಮೂಲಗಳು ಮತ್ತು ಮೈಂಡ್ ಮ್ಯಾಪ್ಸ್ ಪ್ರವೇಶಿಸಿ',
    loginTitle: 'ಮರಳಿ ಸ್ವಾಗತ',
    loginSubtitle: 'ನಿಮ್ಮ GovtExamPath ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    loginPassword: 'ಪಾಸ್‌ವರ್ಡ್',
    loginPasswordPlaceholder: 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    loginRememberMe: 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    loginForgotPwd: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
    loginSignIn: 'ಸೈನ್ ಇನ್',
    loginOr: 'ಅಥವಾ',
    loginNoAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    loginCreateFree: 'ಉಚಿತವಾಗಿ ಸೃಷ್ಟಿಸಿ',
    registerJourney: 'ಸರ್ಕಾರಿ ಕೆರಿಯರ್ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ',
    registerJourneyDesc: 'ನಿಮ್ಮ ಉಚಿತ ಖಾತೆ ಸೃಷ್ಟಿಸಿ ಮತ್ತು ವೈಯಕ್ತಿಕ ಮಾರ್ಗದರ್ಶನ ಅನ್‌ಲಾಕ್ ಮಾಡಿ.',
    registerFeature1: 'ವೈಯಕ್ತಿಕ ಕೆರಿಯರ್ ಶಿಫಾರಸುಗಳು',
    registerFeature2: '200+ ಪರೀಕ್ಷೆಗಳಿಗೆ ತ್ವರಿತ ಅರ್ಹತೆ ಪರಿಶೀಲನೆ',
    registerFeature3: 'ಉಚಿತ ಅಧ್ಯಯನ ಸಂಪನ್ಮೂಲಗಳು ಮತ್ತು ಮೈಂಡ್ ಮ್ಯಾಪ್ಸ್',
    registerFeature4: 'ರಿಯಲ್-ಟೈಮ್ ಪರೀಕ್ಷೆ ಅಧಿಸೂಚನೆಗಳು',
    registerTitle: 'ಖಾತೆ ಸೃಷ್ಟಿಸಿ',
    registerSubtitle: 'GovtExamPath ಗೆ ಸೇರಿ - ಇದು ಸಂಪೂರ್ಣ ಉಚಿತ',
    registerFullName: 'ಪೂರ್ಣ ಹೆಸರು',
    registerFullNamePlaceholder: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    registerConfirmPwd: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    registerConfirmPwdPlaceholder: 'ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತೆ ನಮೂದಿಸಿ',
    registerPwdMinChars: 'ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು',
    registerAgreeTerms: 'ನಾನು ಒಪ್ಪುತ್ತೇನೆ',
    registerTermsLink: 'ಸೇವಾ ನಿಯಮಗಳು',
    registerPrivacyLink: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    registerCreateBtn: 'ಖಾತೆ ಸೃಷ್ಟಿಸಿ',
    registerAlreadyHave: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    registerSignInLink: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    pwdWeak: 'ದುರ್ಬಲ',
    pwdFair: 'ಸರಿ',
    pwdGood: 'ಉತ್ತಮ',
    pwdStrong: 'ಬಲವಾದ',
    pwdVeryStrong: 'ತುಂಬಾ ಬಲವಾದ',
    forgotPwdTitle: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ',
    forgotPwdSubtitle: 'ರೀಸೆಟ್ ಲಿಂಕ್ ಪಡೆಯಲು ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    goodMorning: 'ಶುಭೋದಯ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    dashContinuePrep: 'ನಿಮ್ಮ ಪರೀಕ್ಷೆ ತಯಾರಿ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಿ.',
    dashSavedExams: 'ಉಳಿಸಿದ ಪರೀಕ್ಷೆಗಳು',
    dashNewNotifs: 'ಹೊಸ ಅಧಿಸೂಚನೆಗಳು',
    dashActiveStatus: 'ಸಕ್ರಿಯ',
    dashAccountStatus: 'ಖಾತೆ ಸ್ಥಿತಿ',
    dashLatestExams: 'ತಾಜಾ ಪರೀಕ್ಷೆಗಳು',
    dashRecommended: 'ಶಿಫಾರಸು ಪರೀಕ್ಷೆಗಳು',
    dashRecentBookmarks: 'ಇತ್ತೀಚಿನ ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು',
    dashNoBookmarks: 'ಇನ್ನೂ ಬುಕ್‌ಮಾರ್ಕ್ ಇಲ್ಲ. ಪರೀಕ್ಷೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ ಮತ್ತು ಬುಕ್‌ಮಾರ್ಕ್ ಮಾಡಿ.',
    dashBrowseExams: 'ಪರೀಕ್ಷೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    dashRecentNotifs: 'ಇತ್ತೀಚಿನ ಅಧಿಸೂಚನೆಗಳು',
    dashNoNotifs: 'ಇನ್ನೂ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ.',
    dashUnableLoad: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ',
    dashRefresh: 'ರಿಫ್ರೆಶ್',
    dashViewAll: 'ಎಲ್ಲಾ ನೋಡಿ',
    bookmarksTitle: 'ನನ್ನ ಬುಕ್‌ಮಾರ್ಕ್‌ಗಳು',
    bookmarksSubtitle: 'ನಂತರಕ್ಕೆ ಉಳಿಸಿದ ಪರೀಕ್ಷೆಗಳು',
    bookmarksEmpty: 'ಇನ್ನೂ ಬುಕ್‌ಮಾರ್ಕ್ ಇಲ್ಲ',
    bookmarksEmptyDesc: 'ಆಸಕ್ತಿಯ ಪರೀಕ್ಷೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಬುಕ್‌ಮಾರ್ಕ್ ಮಾಡಿ.',
    profileTitle: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    profileFullName: 'ಪೂರ್ಣ ಹೆಸರು',
    profileSaveChanges: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    profileCancel: 'ರದ್ದುಮಾಡಿ',
    profileEditProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    notifTitle: 'ಅಧಿಸೂಚನೆಗಳು',
    notifAllCaughtUp: 'ಎಲ್ಲಾ ಅಪ್‌ಡೇಟ್!',
    notifMarkAllRead: 'ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ',
    notifFilterAll: 'ಎಲ್ಲಾ',
    notifFilterExamDates: 'ಪರೀಕ್ಷೆ ದಿನಾಂಕಗಳು',
    notifFilterHallTickets: 'ಹಾಲ್ ಟಿಕೆಟ್‌ಗಳು',
    notifFilterResults: 'ಫಲಿತಾಂಶಗಳು',
    notifFilterAnnouncements: 'ಘೋಷಣೆಗಳು',
    notifFilterGeneral: 'ಸಾಮಾನ್ಯ',
    notFoundPageDev: 'ಪುಟ ಅಭಿವೃದ್ಧಿಯಲ್ಲಿದೆ',
    notFoundBrowseAll: 'ಎಲ್ಲಾ ಪರೀಕ್ಷೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    notFound404: 'ಪುಟ ಕಂಡುಬಂದಿಲ್ಲ',
    notFoundDesc: 'ನೀವು ಹುಡುಕುತ್ತಿರುವ ಪುಟ ಅಸ್ತಿತ್ವದಲ್ಲಿಲ್ಲ.',
    notFoundBack: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    notFoundBrowse: 'ಪರೀಕ್ಷೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    notFoundLooking: 'ನಿರ್ದಿಷ್ಟವಾಗಿ ಏನನ್ನಾದರೂ ಹುಡುಕುತ್ತಿದ್ದೀರಾ?',
    notFoundResources: 'ಸಂಪನ್ಮೂಲಗಳು',
    eligCheckerDesc: 'ಸೆಕೆಂಡುಗಳಲ್ಲಿ ನೀವು ಯಾವ ಸರ್ಕಾರಿ ಪರೀಕ್ಷೆಗಳಿಗೆ ಅರ್ಹರು ಎಂದು ತಿಳಿಯಿರಿ',
    eligYourAge: 'ನಿಮ್ಮ ವಯಸ್ಸು',
    eligEnterAge: 'ನಿಮ್ಮ ವಯಸ್ಸನ್ನು ನಮೂದಿಸಿ',
    eligHighestQual: 'ಅತ್ಯುನ್ನತ ಅರ್ಹತೆ',
    eligSelectQual: 'ಅರ್ಹತೆ ಆಯ್ಕೆಮಾಡಿ',
    eligCheckBtn: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ',
    eligEligibleLabel: 'ಅರ್ಹರು',
    eligAlmostLabel: 'ಬಹುತೇಕ ಅರ್ಹರು',
    eligNotEligibleLabel: 'ಅನರ್ಹರು',
    eligGetRecommend: 'ಕೆರಿಯರ್ ಗೈಡ್‌ನಿಂದ ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ',
    eligShowAllBtn: 'ಎಲ್ಲಾ ತೋರಿಸಿ',
    eligShowLess: 'ಕಡಿಮೆ ತೋರಿಸಿ',
    examTabOverview: 'ಅವಲೋಕನ',
    examTabEligibility: 'ಅರ್ಹತೆ',
    examTabSyllabus: 'ಪಠ್ಯಕ್ರಮ',
    examTabPattern: 'ಪರೀಕ್ಷೆ ಮಾದರಿ',
    examTabPYQ: 'ಹಿಂದಿನ ವರ್ಷದ ಪ್ರಶ್ನೆಪತ್ರಿಕೆಗಳು',
    examTabSalary: 'ವೇತನ & ವೃತ್ತಿ',
    examTabApply: 'ಅರ್ಜಿ ಹೇಗೆ',
    examNotFound: 'ಪರೀಕ್ಷೆ ಕಂಡುಬಂದಿಲ್ಲ',
    examBackToExams: 'ಪರೀಕ್ಷೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ',
    examBack: 'ಹಿಂದೆ',
    examRelated: 'ಸಂಬಂಧಿತ ಪರೀಕ್ಷೆಗಳು',
  },
  ta: {
    home: 'முகப்பு',
    exams: 'தேர்வுகள்',
    tools: 'கருவிகள்',
    resources: 'வளங்கள்',
    currentAffairs: 'நடப்பு நிகழ்வுகள்',
    blog: 'வலைப்பதிவு',
    login: 'உள்நுழைவு',
    register: 'பதிவு',
    dashboard: 'டாஷ்போர்டு',
    profile: 'சுயவிவரம்',
    bookmarks: 'புக்மார்க்குகள்',
    notifications: 'அறிவிப்புகள்',
    logout: 'வெளியேறு',
    search: 'தேடு',
    searchExams: 'தலைப்பு, வகை மூலம் தேர்வுகளைத் தேடுங்கள்...',
    browseExams: 'தேர்வுகளை உலாவுங்கள்',
    allExams: 'அனைத்து தேர்வுகள்',
    allCategories: 'அனைத்தும்',
    openNow: 'இப்போது திறந்துள்ளது',
    viewAll: 'அனைத்தையும் காண்க',
    exploreExams: 'தேர்வுகளை ஆராயுங்கள்',
    careerGuide: 'வாழ்க்கை வழிகாட்டி',
    eligibilityChecker: 'தகுதி சோதனை',
    mindMaps: 'மைண்ட் மேப்ஸ்',
    freeResources: 'வள மையம்',
    examCalendar: 'தேர்வு நாட்காட்டி',
    examPriority: 'தேர்வு முன்னுரிமை அணி',
    about: 'எங்களைப் பற்றி',
    aboutUs: 'எங்களைப் பற்றி',
    contact: 'தொடர்பு கொள்க',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    getStarted: 'இலவசமாக தொடங்குங்கள்',
    subscribe: 'சந்தா செலுத்துங்கள்',
    readMore: 'மேலும் படிக்க',
    free: 'இலவசம்',
    students: 'மாணவர்கள்',
    categories: 'வகைகள்',
    quickLinks: 'விரைவு இணைப்புகள்',
    weeklyUpdates: 'வாராந்திர தேர்வு புதுப்பிப்புகளைப் பெறுங்கள்',
    yourEmail: 'உங்கள் மின்னஞ்சல்',
    copyright: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை. இந்தியாவின் எதிர்கால அரசு ஊழியர்களுக்காக உருவாக்கப்பட்டது.',
    homeBadge: 'அரசு வேலைகளுக்கு இலவச வாழ்க்கை வழிகாட்டுதல்',
    heroTitle: 'உங்கள் பாதை',
    heroSubtitle: '200+ அரசு தேர்வுகள், தகுதி சோதனை மற்றும் இலவச தயாரிப்பு வளங்கள்.',
    statExams: 'தேர்வுகள்',
    statStudents: 'மாணவர்கள்',
    statFree: 'இலவசம்',
    closingSoon: 'விரைவில் மூடப்படுகிறது',
    browseByCat: 'வகை வாரியாக உலாவுங்கள்',
    browseByCatSub: '16 துறைகள், 200+ தேர்வுகள் — உங்கள் பாதையைக் கண்டறியுங்கள்',
    viewAllCats: 'அனைத்து வகைகளையும் காண்க',
    freeToolsTitle: 'இலவச கருவிகள் & அம்சங்கள்',
    freeToolsSub: 'சரியான அரசு தேர்வைக் கண்டறிய உங்களுக்குத் தேவையான அனைத்தும்',
    featCareerGuideDesc: 'உங்கள் சுயவிவரத்தின் அடிப்படையில் தனிப்பயன் தேர்வு பரிந்துரைகள்',
    featEligibilityDesc: 'நீங்கள் எந்த தேர்வுகளுக்கு தகுதி பெற்றுள்ளீர்கள் என்று உடனடியாக அறியுங்கள்',
    featMindMapsDesc: 'பயனுள்ள படிப்பு திட்டமிடலுக்கு காட்சி பகுப்பாய்வு',
    featResourcesDesc: 'தளத்தில் விரைவு குறிப்புகள் + அதிகாரப்பூர்வ தேர்வு போர்டல் இணைப்புகள்',
    featCurrentAffairsDesc: 'அனைத்து தேர்வுகளுக்கும் 150+ தினசரி புதுப்பிப்பு கட்டுரைகள்',
    featPriorityDesc: 'குறைந்த போட்டி உள்ள மறைந்திருக்கும் தேர்வுகளைக் கண்டறியுங்கள்',
    ourMission: 'எங்கள் நோக்கம்',
    whatWeOffer: 'நாங்கள் என்ன வழங்குகிறோம்',
    whyTrustUs: 'எங்களை ஏன் நம்ப வேண்டும்',
    ourTeam: 'எங்கள் குழு',
    connectWithUs: 'எங்களுடன் இணையுங்கள்',
    contactTitle: 'தொடர்பு கொள்க',
    contactSubtitle: 'கேள்வி உள்ளதா? எங்களுக்கு செய்தி அனுப்புங்கள்.',
    contactEmailLabel: 'மின்னஞ்சல் அனுப்புங்கள்',
    contactSendMessage: 'செய்தி அனுப்புங்கள்',
    contactMessageSent: 'செய்தி அனுப்பப்பட்டது!',
    contactThankYou: 'தொடர்பு கொண்டதற்கு நன்றி. 24 மணி நேரத்தில் பதிலளிப்போம்.',
    contactYourName: 'உங்கள் பெயர்',
    contactEnterName: 'உங்கள் முழு பெயரை உள்ளிடுங்கள்',
    contactEmailAddress: 'மின்னஞ்சல் முகவரி',
    contactSubjectLabel: 'பொருள்',
    contactSelectTopic: 'தலைப்பைத் தேர்ந்தெடுக்கவும்',
    contactGenQuestion: 'பொது கேள்வி',
    contactExamInfo: 'தேர்வு தகவல்',
    contactEligibilityQuery: 'தகுதி கேள்வி',
    contactReportBug: 'பிழை புகார்',
    contactFeatureRequest: 'அம்ச கோரிக்கை',
    contactFeedbackLabel: 'கருத்து',
    contactMessageLabel: 'செய்தி',
    contactTypeHere: 'உங்கள் செய்தியை இங்கே தட்டச்சு செய்யுங்கள்...',
    contactSending: 'அனுப்புகிறது...',
    contactSendBtn: 'செய்தி அனுப்புங்கள்',
    contactResponseTime: 'பதில் நேரம்',
    contactResponseTimeVal: '24 மணி நேரத்தில்',
    contactLocationLabel: 'இடம்',
    faqPageTitle: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faqSubtitle: 'அரசு தேர்வுகள் மற்றும் எங்கள் தளம் பற்றிய பொது கேள்விகளுக்கு பதில்கள்',
    faqSearchPlaceholder: 'கேள்விகளைத் தேடுங்கள்...',
    faqTabAll: 'அனைத்தும்',
    faqTabGeneral: 'பொது',
    faqTabEligibility: 'தகுதி',
    faqTabPrep: 'தயாரிப்பு',
    faqTabApplication: 'விண்ணப்பம்',
    faqTabSpecific: 'தேர்வு-குறிப்பிட்ட',
    faqSecGeneral: 'பொது கேள்விகள்',
    faqSecEligibility: 'தகுதி & வயது வரம்புகள்',
    faqSecPreparation: 'தயாரிப்பு உத்தி',
    faqSecApplication: 'விண்ணப்ப செயல்முறை',
    faqSecSpecific: 'குறிப்பிட்ட தேர்வுகள் & வாழ்க்கை',
    loginWelcomeBack: 'உங்கள் வாழ்க்கை பயணத்திற்கு மீண்டும் வரவேற்கிறோம்',
    loginWelcomeDesc: 'உங்கள் தனிப்பயன் டாஷ்போர்டு, புக்மார்க் தேர்வுகளை அணுகுங்கள்.',
    loginFeature1: 'உங்கள் புக்மார்க் தேர்வுகள் மற்றும் காலக்கெடுவைக் கண்காணிக்கவும்',
    loginFeature2: 'தனிப்பயன் தேர்வு பரிந்துரைகளைப் பெறுங்கள்',
    loginFeature3: 'படிப்பு வளங்கள் மற்றும் மைண்ட் மேப்களை அணுகுங்கள்',
    loginTitle: 'மீண்டும் வரவேற்கிறோம்',
    loginSubtitle: 'உங்கள் GovtExamPath கணக்கில் உள்நுழையுங்கள்',
    loginPassword: 'கடவுச்சொல்',
    loginPasswordPlaceholder: 'உங்கள் கடவுச்சொல்லை உள்ளிடுங்கள்',
    loginRememberMe: 'என்னை நினைவில் வை',
    loginForgotPwd: 'கடவுச்சொல் மறந்துவிட்டதா?',
    loginSignIn: 'உள்நுழைக',
    loginOr: 'அல்லது',
    loginNoAccount: 'கணக்கு இல்லையா?',
    loginCreateFree: 'இலவசமாக உருவாக்குங்கள்',
    registerJourney: 'அரசு வாழ்க்கை பயணத்தைத் தொடங்குங்கள்',
    registerJourneyDesc: 'உங்கள் இலவச கணக்கை உருவாக்கி தனிப்பயன் வழிகாட்டுதலை திறக்கவும்.',
    registerTitle: 'கணக்கு உருவாக்குங்கள்',
    registerSubtitle: 'GovtExamPath இல் சேருங்கள் - இது முற்றிலும் இலவசம்',
    registerFullName: 'முழு பெயர்',
    registerFullNamePlaceholder: 'உங்கள் முழு பெயரை உள்ளிடுங்கள்',
    registerConfirmPwd: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    registerConfirmPwdPlaceholder: 'கடவுச்சொல்லை மீண்டும் உள்ளிடுங்கள்',
    registerPwdMinChars: 'குறைந்தபட்சம் 6 எழுத்துகள்',
    registerAgreeTerms: 'நான் ஒப்புக்கொள்கிறேன்',
    registerTermsLink: 'சேவை விதிமுறைகள்',
    registerPrivacyLink: 'தனியுரிமைக் கொள்கை',
    registerCreateBtn: 'கணக்கு உருவாக்குங்கள்',
    registerAlreadyHave: 'ஏற்கனவே கணக்கு உள்ளதா?',
    registerSignInLink: 'உள்நுழையுங்கள்',
    pwdWeak: 'பலவீனம்',
    pwdFair: 'சரி',
    pwdGood: 'நல்லது',
    pwdStrong: 'வலுவான',
    pwdVeryStrong: 'மிகவும் வலுவான',
    forgotPwdTitle: 'கடவுச்சொல் மறந்துவிட்டதா',
    forgotPwdSubtitle: 'மீட்டமை இணைப்பைப் பெற உங்கள் மின்னஞ்சலை உள்ளிடுங்கள்',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    dashContinuePrep: 'உங்கள் தேர்வு தயாரிப்பு பயணத்தைத் தொடரவும்.',
    dashSavedExams: 'சேமிக்கப்பட்ட தேர்வுகள்',
    dashNewNotifs: 'புதிய அறிவிப்புகள்',
    dashActiveStatus: 'செயலில்',
    dashAccountStatus: 'கணக்கு நிலை',
    dashLatestExams: 'சமீபத்திய தேர்வுகள்',
    dashRecommended: 'பரிந்துரைக்கப்பட்ட தேர்வுகள்',
    dashRecentBookmarks: 'சமீபத்திய புக்மார்க்குகள்',
    dashNoBookmarks: 'இன்னும் புக்மார்க்குகள் இல்லை. தேர்வுகளை உலாவி புக்மார்க் செய்யுங்கள்.',
    dashBrowseExams: 'தேர்வுகளை உலாவுங்கள்',
    dashRecentNotifs: 'சமீபத்திய அறிவிப்புகள்',
    dashNoNotifs: 'இன்னும் அறிவிப்புகள் இல்லை.',
    dashUnableLoad: 'டாஷ்போர்டை ஏற்ற இயலவில்லை',
    dashRefresh: 'புதுப்பி',
    dashViewAll: 'அனைத்தையும் காண்க',
    bookmarksTitle: 'எனது புக்மார்க்குகள்',
    bookmarksSubtitle: 'பின்னர் பார்க்க சேமிக்கப்பட்ட தேர்வுகள்',
    bookmarksEmpty: 'இன்னும் புக்மார்க்குகள் இல்லை',
    bookmarksEmptyDesc: 'ஆர்வமுள்ள தேர்வுகளைக் கண்காணிக்க புக்மார்க் செய்யுங்கள்.',
    profileTitle: 'என் சுயவிவரம்',
    profileFullName: 'முழு பெயர்',
    profileSaveChanges: 'மாற்றங்களைச் சேமி',
    profileCancel: 'ரத்து',
    profileEditProfile: 'சுயவிவரத்தைத் திருத்து',
    notifTitle: 'அறிவிப்புகள்',
    notifAllCaughtUp: 'அனைத்தும் புதுப்பிக்கப்பட்டது!',
    notifMarkAllRead: 'அனைத்தையும் படித்ததாகக் குறி',
    notifFilterAll: 'அனைத்தும்',
    notifFilterExamDates: 'தேர்வு தேதிகள்',
    notifFilterHallTickets: 'ஹால் டிக்கெட்டுகள்',
    notifFilterResults: 'முடிவுகள்',
    notifFilterAnnouncements: 'அறிவிப்புகள்',
    notifFilterGeneral: 'பொது',
    notFoundPageDev: 'பக்கம் உருவாக்கத்தில் உள்ளது',
    notFoundBrowseAll: 'அனைத்து தேர்வுகளையும் உலாவுங்கள்',
    notFound404: 'பக்கம் காணப்படவில்லை',
    notFoundDesc: 'நீங்கள் தேடும் பக்கம் இல்லை.',
    notFoundBack: 'முகப்புக்குத் திரும்பு',
    notFoundBrowse: 'தேர்வுகளை உலாவுங்கள்',
    notFoundLooking: 'குறிப்பிட்ட ஒன்றைத் தேடுகிறீர்களா?',
    notFoundResources: 'வளங்கள்',
    eligCheckerDesc: 'நொடிகளில் எந்த அரசு தேர்வுகளுக்கு தகுதி உள்ளது என்று அறியுங்கள்',
    eligYourAge: 'உங்கள் வயது',
    eligEnterAge: 'உங்கள் வயதை உள்ளிடுங்கள்',
    eligHighestQual: 'உயர்ந்த தகுதி',
    eligSelectQual: 'தகுதியைத் தேர்ந்தெடுக்கவும்',
    eligCheckBtn: 'தகுதி சோதிக்கவும்',
    eligEligibleLabel: 'தகுதியானவர்',
    eligAlmostLabel: 'கிட்டத்தட்ட தகுதியானவர்',
    eligNotEligibleLabel: 'தகுதியற்றவர்',
    eligGetRecommend: 'வாழ்க்கை வழிகாட்டியிலிருந்து தனிப்பயன் பரிந்துரைகளைப் பெறுங்கள்',
    eligShowAllBtn: 'அனைத்தையும் காட்டு',
    eligShowLess: 'குறைவாகக் காட்டு',
    examTabOverview: 'கண்ணோட்டம்',
    examTabEligibility: 'தகுதி',
    examTabSyllabus: 'பாடத்திட்டம்',
    examTabPattern: 'தேர்வு முறை',
    examTabPYQ: 'முந்தைய ஆண்டு வினாத்தாள்கள்',
    examTabSalary: 'சம்பளம் & வாழ்க்கை',
    examTabApply: 'விண்ணப்பிப்பது எப்படி',
    examNotFound: 'தேர்வு காணப்படவில்லை',
    examBackToExams: 'தேர்வுகளுக்குத் திரும்பு',
    examBack: 'பின்',
    examRelated: 'தொடர்புடைய தேர்வுகள்',
  },
  ml: {
    home: 'ഹോം',
    exams: 'പരീക്ഷകൾ',
    tools: 'ഉപകരണങ്ങൾ',
    resources: 'വിഭവങ്ങൾ',
    currentAffairs: 'സമകാലിക വിഷയങ്ങൾ',
    blog: 'ബ്ലോഗ്',
    login: 'ലോഗിൻ',
    register: 'രജിസ്റ്റർ',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    profile: 'പ്രൊഫൈൽ',
    bookmarks: 'ബുക്ക്‌മാർക്കുകൾ',
    notifications: 'അറിയിപ്പുകൾ',
    logout: 'ലോഗൗട്ട്',
    search: 'തിരയുക',
    searchExams: 'ശീർഷകം, വിഭാഗം പ്രകാരം പരീക്ഷകൾ തിരയുക...',
    browseExams: 'പരീക്ഷകൾ ബ്രൗസ് ചെയ്യുക',
    allExams: 'എല്ലാ പരീക്ഷകളും',
    allCategories: 'എല്ലാം',
    openNow: 'ഇപ്പോൾ തുറന്നിരിക്കുന്നു',
    viewAll: 'എല്ലാം കാണുക',
    exploreExams: 'പരീക്ഷകൾ പര്യവേക്ഷണം ചെയ്യുക',
    careerGuide: 'കരിയർ ഗൈഡ്',
    eligibilityChecker: 'യോഗ്യത പരിശോധന',
    mindMaps: 'മൈൻഡ് മാപ്പുകൾ',
    freeResources: 'വിഭവ കേന്ദ്രം',
    examCalendar: 'പരീക്ഷ കലണ്ടർ',
    examPriority: 'പരീക്ഷ മുൻഗണന മാട്രിക്സ്',
    about: 'ഞങ്ങളെ കുറിച്ച്',
    aboutUs: 'ഞങ്ങളെ കുറിച്ച്',
    contact: 'ബന്ധപ്പെടുക',
    faq: 'FAQ',
    getStarted: 'സൗജന്യമായി ആരംഭിക്കുക',
    subscribe: 'സബ്‌സ്ക്രൈബ്',
    readMore: 'കൂടുതൽ വായിക്കുക',
    free: 'സൗജന്യം',
    students: 'വിദ്യാർത്ഥികൾ',
    categories: 'വിഭാഗങ്ങൾ',
    quickLinks: 'ദ്രുത ലിങ്കുകൾ',
    weeklyUpdates: 'പ്രതിവാര പരീക്ഷ അപ്‌ഡേറ്റുകൾ നേടുക',
    yourEmail: 'നിങ്ങളുടെ ഇമെയിൽ',
    copyright: 'എല്ലാ അവകാശങ്ങളും സംരക്ഷിച്ചിരിക്കുന്നു. ഇന്ത്യയുടെ ഭാവി സിവിൽ സർവന്റുമാർക്കായി നിർമ്മിച്ചത്.',
    homeBadge: 'സർക്കാർ ജോലികൾക്ക് സൗജന്യ കരിയർ മാർഗനിർദേശം',
    heroTitle: 'നിങ്ങളുടെ പാത',
    heroSubtitle: '200+ സർക്കാർ പരീക്ഷകൾ, യോഗ്യത പരിശോധന, സൗജന്യ തയ്യാറെടുപ്പ് വിഭവങ്ങൾ.',
    statExams: 'പരീക്ഷകൾ',
    statStudents: 'വിദ്യാർത്ഥികൾ',
    statFree: 'സൗജന്യം',
    closingSoon: 'ഉടൻ അവസാനിക്കും',
    browseByCat: 'വിഭാഗം അനുസരിച്ച് ബ്രൗസ് ചെയ്യുക',
    browseByCatSub: '16 മേഖലകൾ, 200+ പരീക്ഷകൾ — നിങ്ങളുടെ പാത കണ്ടെത്തുക',
    viewAllCats: 'എല്ലാ വിഭാഗങ്ങളും കാണുക',
    freeToolsTitle: 'സൗജന്യ ഉപകരണങ്ങൾ & ഫീച്ചറുകൾ',
    freeToolsSub: 'ശരിയായ സർക്കാർ പരീക്ഷ കണ്ടെത്താൻ നിങ്ങൾക്ക് ആവശ്യമായ എല്ലാം',
    featCareerGuideDesc: 'നിങ്ങളുടെ പ്രൊഫൈൽ അടിസ്ഥാനമാക്കി വ്യക്തിഗത പരീക്ഷ ശുപാർശകൾ',
    featEligibilityDesc: 'ഏത് പരീക്ഷകൾക്ക് യോഗ്യതയുണ്ടെന്ന് ഉടൻ അറിയുക',
    featMindMapsDesc: 'ഫലപ്രദമായ പഠന ആസൂത്രണത്തിന് ദൃശ്യ വിശകലനം',
    featResourcesDesc: 'സൈറ്റിൽ ദ്രുത കുറിപ്പുകൾ + ഔദ്യോഗിക പരീക്ഷ പോർട്ടൽ ലിങ്കുകൾ',
    featCurrentAffairsDesc: 'എല്ലാ പരീക്ഷകൾക്കും 150+ ദൈനംദിന അപ്‌ഡേറ്റ് ലേഖനങ്ങൾ',
    featPriorityDesc: 'കുറഞ്ഞ മത്സരമുള്ള മറഞ്ഞിരിക്കുന്ന പരീക്ഷകൾ കണ്ടെത്തുക',
    ourMission: 'ഞങ്ങളുടെ ദൗത്യം',
    whatWeOffer: 'ഞങ്ങൾ എന്ത് വാഗ്ദാനം ചെയ്യുന്നു',
    whyTrustUs: 'ഞങ്ങളെ എന്തുകൊണ്ട് വിശ്വസിക്കണം',
    ourTeam: 'ഞങ്ങളുടെ ടീം',
    connectWithUs: 'ഞങ്ങളുമായി ബന്ധപ്പെടുക',
    contactTitle: 'ബന്ധപ്പെടുക',
    contactSubtitle: 'ചോദ്യമുണ്ടോ? ഞങ്ങൾക്ക് സന്ദേശം അയയ്ക്കുക.',
    contactEmailLabel: 'ഇമെയിൽ അയയ്ക്കുക',
    contactSendMessage: 'സന്ദേശം അയയ്ക്കുക',
    contactMessageSent: 'സന്ദേശം അയച്ചു!',
    contactThankYou: 'ബന്ധപ്പെട്ടതിന് നന്ദി. 24 മണിക്കൂറിനുള്ളിൽ മറുപടി നൽകും.',
    contactYourName: 'നിങ്ങളുടെ പേര്',
    contactEnterName: 'നിങ്ങളുടെ മുഴുവൻ പേര് നൽകുക',
    contactEmailAddress: 'ഇമെയിൽ വിലാസം',
    contactSubjectLabel: 'വിഷയം',
    contactSelectTopic: 'വിഷയം തിരഞ്ഞെടുക്കുക',
    contactGenQuestion: 'പൊതു ചോദ്യം',
    contactExamInfo: 'പരീക്ഷ വിവരങ്ങൾ',
    contactEligibilityQuery: 'യോഗ്യത ചോദ്യം',
    contactReportBug: 'ബഗ് റിപ്പോർട്ട്',
    contactFeatureRequest: 'ഫീച്ചർ അഭ്യർത്ഥന',
    contactFeedbackLabel: 'ഫീഡ്ബാക്ക്',
    contactMessageLabel: 'സന്ദേശം',
    contactTypeHere: 'നിങ്ങളുടെ സന്ദേശം ഇവിടെ ടൈപ്പ് ചെയ്യുക...',
    contactSending: 'അയയ്ക്കുന്നു...',
    contactSendBtn: 'സന്ദേശം അയയ്ക്കുക',
    contactResponseTime: 'പ്രതികരണ സമയം',
    contactResponseTimeVal: '24 മണിക്കൂറിനുള്ളിൽ',
    contactLocationLabel: 'സ്ഥലം',
    faqPageTitle: 'പതിവ് ചോദ്യങ്ങൾ',
    faqSubtitle: 'സർക്കാർ പരീക്ഷകളെയും ഞങ്ങളുടെ പ്ലാറ്റ്‌ഫോമിനെയും കുറിച്ചുള്ള സാധാരണ ചോദ്യങ്ങൾക്ക് ഉത്തരങ്ങൾ',
    faqSearchPlaceholder: 'ചോദ്യങ്ങൾ തിരയുക...',
    faqTabAll: 'എല്ലാം',
    faqTabGeneral: 'പൊതു',
    faqTabEligibility: 'യോഗ്യത',
    faqTabPrep: 'തയ്യാറെടുപ്പ്',
    faqTabApplication: 'അപേക്ഷ',
    faqTabSpecific: 'പരീക്ഷ-നിർദ്ദിഷ്ട',
    faqSecGeneral: 'പൊതു ചോദ്യങ്ങൾ',
    faqSecEligibility: 'യോഗ്യത & പ്രായപരിധി',
    faqSecPreparation: 'തയ്യാറെടുപ്പ് തന്ത്രം',
    faqSecApplication: 'അപേക്ഷ പ്രക്രിയ',
    faqSecSpecific: 'നിർദ്ദിഷ്ട പരീക്ഷകൾ & കരിയർ',
    loginWelcomeBack: 'നിങ്ങളുടെ കരിയർ യാത്രയിലേക്ക് തിരിച്ചെത്തിയതിന് സ്വാഗതം',
    loginWelcomeDesc: 'നിങ്ങളുടെ വ്യക്തിഗത ഡാഷ്‌ബോർഡ്, ബുക്ക്‌മാർക്ക് പരീക്ഷകൾ ആക്‌സസ് ചെയ്യുക.',
    loginFeature1: 'നിങ്ങളുടെ ബുക്ക്‌മാർക്ക് പരീക്ഷകളും സമയപരിധികളും ട്രാക്ക് ചെയ്യുക',
    loginFeature2: 'വ്യക്തിഗത പരീക്ഷ ശുപാർശകൾ നേടുക',
    loginFeature3: 'പഠന വിഭവങ്ങളും മൈൻഡ് മാപ്പുകളും ആക്‌സസ് ചെയ്യുക',
    loginTitle: 'തിരിച്ചെത്തിയതിന് സ്വാഗതം',
    loginSubtitle: 'നിങ്ങളുടെ GovtExamPath അക്കൗണ്ടിലേക്ക് സൈൻ ഇൻ ചെയ്യുക',
    loginPassword: 'പാസ്‌വേഡ്',
    loginPasswordPlaceholder: 'നിങ്ങളുടെ പാസ്‌വേഡ് നൽകുക',
    loginRememberMe: 'എന്നെ ഓർക്കുക',
    loginForgotPwd: 'പാസ്‌വേഡ് മറന്നോ?',
    loginSignIn: 'സൈൻ ഇൻ',
    loginOr: 'അല്ലെങ്കിൽ',
    loginNoAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    loginCreateFree: 'സൗജന്യമായി സൃഷ്ടിക്കുക',
    registerJourney: 'സർക്കാർ കരിയർ യാത്ര ആരംഭിക്കുക',
    registerJourneyDesc: 'നിങ്ങളുടെ സൗജന്യ അക്കൗണ്ട് സൃഷ്ടിച്ച് വ്യക്തിഗത മാർഗനിർദേശം അൺലോക്ക് ചെയ്യുക.',
    registerTitle: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    registerSubtitle: 'GovtExamPath ൽ ചേരുക - ഇത് പൂർണ്ണമായും സൗജന്യമാണ്',
    registerFullName: 'മുഴുവൻ പേര്',
    registerFullNamePlaceholder: 'നിങ്ങളുടെ മുഴുവൻ പേര് നൽകുക',
    registerConfirmPwd: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    registerConfirmPwdPlaceholder: 'പാസ്‌വേഡ് വീണ്ടും നൽകുക',
    registerPwdMinChars: 'കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ',
    registerAgreeTerms: 'ഞാൻ സമ്മതിക്കുന്നു',
    registerTermsLink: 'സേവന നിബന്ധനകൾ',
    registerPrivacyLink: 'സ്വകാര്യതാ നയം',
    registerCreateBtn: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    registerAlreadyHave: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    registerSignInLink: 'സൈൻ ഇൻ ചെയ്യുക',
    pwdWeak: 'ദുർബലം',
    pwdFair: 'ശരി',
    pwdGood: 'നല്ലത്',
    pwdStrong: 'ശക്തമായത്',
    pwdVeryStrong: 'വളരെ ശക്തമായത്',
    forgotPwdTitle: 'പാസ്‌വേഡ് മറന്നോ',
    forgotPwdSubtitle: 'റീസെറ്റ് ലിങ്ക് ലഭിക്കാൻ നിങ്ങളുടെ ഇമെയിൽ നൽകുക',
    goodMorning: 'സുപ്രഭാതം',
    goodAfternoon: 'ശുഭ ഉച്ചനേരം',
    goodEvening: 'ശുഭ സന്ധ്യ',
    dashContinuePrep: 'നിങ്ങളുടെ പരീക്ഷ തയ്യാറെടുപ്പ് യാത്ര തുടരുക.',
    dashSavedExams: 'സേവ് ചെയ്ത പരീക്ഷകൾ',
    dashNewNotifs: 'പുതിയ അറിയിപ്പുകൾ',
    dashActiveStatus: 'സജീവം',
    dashAccountStatus: 'അക്കൗണ്ട് സ്ഥിതി',
    dashLatestExams: 'ഏറ്റവും പുതിയ പരീക്ഷകൾ',
    dashRecommended: 'ശുപാർശ ചെയ്ത പരീക്ഷകൾ',
    dashRecentBookmarks: 'സമീപകാല ബുക്ക്‌മാർക്കുകൾ',
    dashNoBookmarks: 'ഇതുവരെ ബുക്ക്‌മാർക്കുകൾ ഇല്ല. പരീക്ഷകൾ ബ്രൗസ് ചെയ്ത് ബുക്ക്‌മാർക്ക് ചെയ്യുക.',
    dashBrowseExams: 'പരീക്ഷകൾ ബ്രൗസ് ചെയ്യുക',
    dashRecentNotifs: 'സമീപകാല അറിയിപ്പുകൾ',
    dashNoNotifs: 'ഇതുവരെ അറിയിപ്പുകളില്ല.',
    dashUnableLoad: 'ഡാഷ്‌ബോർഡ് ലോഡ് ചെയ്യാനായില്ല',
    dashRefresh: 'പുതുക്കുക',
    dashViewAll: 'എല്ലാം കാണുക',
    bookmarksTitle: 'എന്റെ ബുക്ക്‌മാർക്കുകൾ',
    bookmarksSubtitle: 'പിന്നീട് കാണാൻ സേവ് ചെയ്ത പരീക്ഷകൾ',
    bookmarksEmpty: 'ഇതുവരെ ബുക്ക്‌മാർക്കുകൾ ഇല്ല',
    bookmarksEmptyDesc: 'താൽപ്പര്യമുള്ള പരീക്ഷകൾ ട്രാക്ക് ചെയ്യാൻ ബുക്ക്‌മാർക്ക് ചെയ്യുക.',
    profileTitle: 'എന്റെ പ്രൊഫൈൽ',
    profileFullName: 'മുഴുവൻ പേര്',
    profileSaveChanges: 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
    profileCancel: 'റദ്ദാക്കുക',
    profileEditProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
    notifTitle: 'അറിയിപ്പുകൾ',
    notifAllCaughtUp: 'എല്ലാം അപ്‌ഡേറ്റ്!',
    notifMarkAllRead: 'എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക',
    notifFilterAll: 'എല്ലാം',
    notifFilterExamDates: 'പരീക്ഷ തീയതികൾ',
    notifFilterHallTickets: 'ഹാൾ ടിക്കറ്റുകൾ',
    notifFilterResults: 'ഫലങ്ങൾ',
    notifFilterAnnouncements: 'അറിയിപ്പുകൾ',
    notifFilterGeneral: 'പൊതു',
    notFoundPageDev: 'പേജ് വികസനത്തിലാണ്',
    notFoundBrowseAll: 'എല്ലാ പരീക്ഷകളും ബ്രൗസ് ചെയ്യുക',
    notFound404: 'പേജ് കണ്ടെത്തിയില്ല',
    notFoundDesc: 'നിങ്ങൾ തിരയുന്ന പേജ് നിലവിലില്ല.',
    notFoundBack: 'ഹോമിലേക്ക് മടങ്ങുക',
    notFoundBrowse: 'പരീക്ഷകൾ ബ്രൗസ് ചെയ്യുക',
    notFoundLooking: 'എന്തെങ്കിലും പ്രത്യേകമായി തിരയുകയാണോ?',
    notFoundResources: 'വിഭവങ്ങൾ',
    eligCheckerDesc: 'നിമിഷങ്ങൾക്കുള്ളിൽ ഏത് സർക്കാർ പരീക്ഷകൾക്ക് യോഗ്യതയുണ്ടെന്ന് അറിയുക',
    eligYourAge: 'നിങ്ങളുടെ പ്രായം',
    eligEnterAge: 'നിങ്ങളുടെ പ്രായം നൽകുക',
    eligHighestQual: 'ഉയർന്ന യോഗ്യത',
    eligSelectQual: 'യോഗ്യത തിരഞ്ഞെടുക്കുക',
    eligCheckBtn: 'യോഗ്യത പരിശോധിക്കുക',
    eligEligibleLabel: 'യോഗ്യൻ',
    eligAlmostLabel: 'ഏതാണ്ട് യോഗ്യൻ',
    eligNotEligibleLabel: 'അയോഗ്യൻ',
    eligGetRecommend: 'കരിയർ ഗൈഡിൽ നിന്ന് വ്യക്തിഗത ശുപാർശകൾ നേടുക',
    eligShowAllBtn: 'എല്ലാം കാണിക്കുക',
    eligShowLess: 'കുറച്ച് കാണിക്കുക',
    examTabOverview: 'അവലോകനം',
    examTabEligibility: 'യോഗ്യത',
    examTabSyllabus: 'സിലബസ്',
    examTabPattern: 'പരീക്ഷ പാറ്റേൺ',
    examTabPYQ: 'മുൻ വർഷ ചോദ്യപേപ്പറുകൾ',
    examTabSalary: 'ശമ്പളം & കരിയർ',
    examTabApply: 'അപേക്ഷിക്കുന്നതെങ്ങനെ',
    examNotFound: 'പരീക്ഷ കണ്ടെത്തിയില്ല',
    examBackToExams: 'പരീക്ഷകളിലേക്ക് മടങ്ങുക',
    examBack: 'പിന്നിലേക്ക്',
    examRelated: 'ബന്ധപ്പെട്ട പരീക്ഷകൾ',
  },
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('lang', language);
  }, [language]);

  const toggleLanguage = useCallback(() => {
    const langs = ['en', 'hi', 'te', 'kn', 'ta', 'ml'];
    setLanguage((prev) => {
      const idx = langs.indexOf(prev);
      return langs[(idx + 1) % langs.length];
    });
  }, []);

  const t = useCallback((key) => {
    const dict = translations[language] || translations.en;
    return dict[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
