import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  en: {
    home: 'Home',
    exams: 'Exams',
    tools: 'Tools',
    resources: 'Resources',
    currentAffairs: 'Current Affairs',
    blog: 'Blog',
    login: 'Login',
    register: 'Register',
    dashboard: 'Dashboard',
    profile: 'Profile',
    bookmarks: 'Bookmarks',
    notifications: 'Notifications',
    logout: 'Logout',
    search: 'Search',
    searchExams: 'Search exams by title, category...',
    browseExams: 'Browse Exams',
    allExams: 'All Exams',
    allCategories: 'All',
    openNow: 'Open Now',
    viewAll: 'View All',
    exploreExams: 'Explore Exams',
    careerGuide: 'Career Guide',
    eligibilityChecker: 'Eligibility Checker',
    mindMaps: 'Mind Maps',
    freeResources: 'Free Resources',
    examCalendar: 'Exam Calendar',
    examPriority: 'Exam Priority Matrix',
    prepRoadmap: 'Prep Roadmap',
    cutOff: 'Cut-Off Marks',
    compareExams: 'Compare Exams',
    prepTime: 'Prep Time Estimator',
    salaryCalc: 'Salary Calculator',
    about: 'About',
    aboutUs: 'About Us',
    contact: 'Contact',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    disclaimer: 'Disclaimer',
    faq: 'FAQ',
    getStarted: 'Get Started Free',
    subscribe: 'Subscribe',
    readMore: 'Read More',
    latestExams: 'Latest Exams',
    successStories: 'Success Stories',
    free: 'Free',
    students: 'Students',
    categories: 'Categories',
    examCategories: 'Exam Categories',
    language: 'Language',
    hindi: 'Hindi',
    english: 'English',
    quickLinks: 'Quick Links',
    contactNewsletter: 'Contact & Newsletter',
    weeklyUpdates: 'Get weekly exam updates',
    yourEmail: 'Your email',
    subscribedSuccess: 'Subscribed successfully!',
    copyright: 'All rights reserved. Made with purpose for India\'s future civil servants.',
    adminPanel: 'Admin Panel',
    policies: 'Policies',
    // Home page
    heroTag: 'Free Career Guidance for Government Jobs',
    heroTitle1: 'Your Path to',
    heroTitle2: 'Success',
    heroSubtitle: 'Explore 500+ government exams, check eligibility, and access free preparation resources.',
    checkEligibility: 'Check Eligibility',
    whyChoose: 'Why Choose',
    govtExamPath: 'GovtExamPath',
    whyChooseDesc: 'We provide comprehensive, accurate, and up-to-date information to help you navigate government exams.',
    freeForever: 'Free Forever',
    freeForeverDesc: 'All features completely free. No hidden charges.',
    alwaysUpdated: 'Always Updated',
    alwaysUpdatedDesc: 'Real-time updates on exam dates, results, and notifications.',
    officialSources: 'Official Sources',
    officialSourcesDesc: 'All information verified from official government sources.',
    multiLanguage: 'Multi-Language',
    multiLanguageDesc: 'Available in English, Hindi & Telugu.',
    examsCovered: 'Exams Covered',
    dailyUpdates: 'Daily Updates',
    activeStudents: 'Active Students',
    languages: 'Languages',
    topExamCategories: 'Top Exam Categories',
    whatStudentsSay: 'Why Choose GovtExamPath',
    readyToStart: 'Ready to Start Your Journey?',
    readyToStartDesc: 'Join thousands of aspirants who trust GovtExamPath for their exam preparation.',
    startExploring: 'Start Exploring',
    // Login page
    welcomeBack: 'Welcome Back',
    signInToContinue: 'Sign in to continue your exam preparation journey',
    emailAddress: 'Email Address',
    password: 'Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    signIn: 'Sign In',
    signingIn: 'Signing In...',
    orContinueWith: 'Or continue with',
    dontHaveAccount: "Don't have an account?",
    createOneFree: 'Create one free',
    loginBenefit1: 'Get personalized exam recommendations',
    loginBenefit2: 'Track your bookmarked exams and deadlines',
    loginBenefit3: 'Receive important exam notifications',
    // Register page
    createAccount: 'Create Account',
    joinCommunity: 'Join our community of government exam aspirants',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    confirmPassword: 'Confirm Password',
    reEnterPassword: 'Re-enter your password',
    agreeToTerms: 'I agree to the',
    termsAndConditions: 'Terms & Conditions',
    andThe: 'and the',
    creatingAccount: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    regBenefit1: 'Personalized career recommendations',
    regBenefit2: 'Real-time exam notifications',
    regBenefit3: 'Free study resources and mind maps',
    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    savedExams: 'Saved Exams',
    newNotifications: 'New Notifications',
    accountStatus: 'Account Status',
    activeAccount: 'Active',
    quickActions: 'Quick Actions',
    recentBookmarks: 'Recent Bookmarks',
    latestExamsForYou: 'Latest Exams For You',
    noBookmarksYet: 'No bookmarks yet',
    noExamsAvailable: 'No exams available',
    // Common
    loading: 'Loading...',
    noDataFound: 'No data found',
    tryAgain: 'Try Again',
    goBack: 'Go Back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    submit: 'Submit',
    sending: 'Sending...',
    send: 'Send',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'The page you are looking for does not exist or is under development.',
    backToHome: 'Back to Home',
    // Blog
    blogTitle: 'Blog',
    blogTitleHighlight: 'Exam Preparation Tips & Guides',
    blogSubtitle: 'Expert articles and guides for government exam preparation',
    blogSearchPlaceholder: 'Search articles...',
    blogNoResults: 'No articles found',
    blogFeatured: 'Featured',
    blogCatAll: 'All',
    blogCatStrategy: 'Strategy',
    blogCatExamGuide: 'Exam Guide',
    blogCatTips: 'Tips',
    blogCatCurrentAffairs: 'Current Affairs',
    blogCatCareer: 'Career',
    // Success Stories
    ssHeroTitle: 'Success',
    ssHeroHighlight: 'Stories',
    ssHeroSubtitle: 'We are collecting real success stories from our community',
    // About page
    aboutHeroSub: 'Free career guidance platform for government exam aspirants across India.',
    aboutFounded: 'Founded in 2026',
    ourMission: 'Our Mission',
    missionP1: 'GovtExamPath was created with a simple goal — to make government exam information accessible, accurate, and free for every aspirant in India.',
    missionP2: 'We believe that financial constraints should never prevent talented individuals from accessing quality career guidance. Our platform provides verified exam notifications, eligibility tools, preparation resources, and career insights — all completely free.',
    whatWeOffer: 'What We Offer',
    whatWeOfferSub: 'Comprehensive tools and resources designed for government exam aspirants.',
    learnMore: 'Learn More',
    expertBlog: 'Expert Blog',
    aboutFeat1Desc: 'AI-powered career guidance to help you find the best government exams matching your profile.',
    aboutFeat2Desc: 'Instantly check your eligibility for 500+ government exams based on your qualifications.',
    aboutFeat3Desc: 'Visual mind maps for exam syllabi, preparation strategies, and topic connections.',
    aboutFeat4Desc: 'Curated study materials, previous year papers, and preparation notes for all major exams.',
    aboutFeat5Desc: 'In-depth articles on exam strategies, preparation tips, and career guidance from experts.',
    aboutFeat6Desc: 'Daily current affairs updates essential for government exam preparation.',
    whyTrustUs: 'Why Trust Us',
    whyTrustUsSub: 'Built on principles of accuracy, transparency, and accessibility.',
    trustOfficialSources: 'Official Sources',
    trustOfficialSourcesDesc: 'All information is sourced and verified from official government websites and notifications.',
    trustAlwaysUpdated: 'Always Updated',
    trustAlwaysUpdatedDesc: 'Our data is regularly updated to reflect the latest exam dates, vacancies, and notifications.',
    trustFreeForever: 'Free Forever',
    trustFreeForeverDesc: 'Every feature on GovtExamPath is completely free. No premium plans, no hidden charges.',
    trustPrivacy: 'Privacy First',
    trustPrivacyDesc: 'We do not sell your data. Zero third-party trackers. Your privacy is our priority.',
    ourTeam: 'Our Team',
    ourTeamSub: 'The people behind GovtExamPath.',
    roleCEO: 'Founder & CEO',
    roleTechLead: 'Tech Lead',
    roleContentHead: 'Content Head',
    teamBio1: 'Passionate about making government exam preparation accessible to all aspirants across India.',
    teamBio2: 'Building scalable and reliable technology to serve millions of aspirants.',
    teamBio3: 'Ensuring accurate, well-researched content for every exam on the platform.',
    connectWithUs: 'Connect With Us',
    connectWithUsSub: 'Follow us on social media for daily updates and exam notifications.',
    statStudentsGuided: 'Students Guided',
    statExamsCovered: 'Exams Covered',
    statUpdates: 'Updates',
    dreamJobTitle: 'Start Your Journey to a Government Career',
    dreamJobSub: 'Join thousands of aspirants who trust GovtExamPath for their exam preparation.',
    unavailable: 'Not Available',
    aboutFollowInsta: 'Follow on Instagram',
    aboutSubYoutube: 'Subscribe on YouTube',
    aboutJoinTelegram: 'Join Telegram',
    aboutFollowX: 'Follow on X',
    // Contact page
    contactUs: 'Contact Us',
    contactSubtitle: 'Have a question or feedback? We\'d love to hear from you.',
    yourName: 'Your Name',
    subject: 'Subject',
    message: 'Message',
    responseTime: 'Response Time',
    location: 'Location',
    within24Hours: 'Within 24 Hours',
    // Manage Subscriptions
    manageSubscriptions: 'Manage Subscriptions',
    subscribed: 'Subscribed',
    unsubscribeAll: 'Unsubscribe All',
    subscribeAll: 'Subscribe All',
    // Common / Shared
    upcoming: 'Upcoming',
    closed: 'Closed',
    showing: 'Showing',
    noResultsFound: 'No results found',
    clearAllFilters: 'Clear all filters',
    visitOfficialSite: 'Visit Official Site',
    downloadPDF: 'Download PDF',
    print: 'Print',
    allStates: 'All States',
    apply: 'Apply',
    applyNow: 'Apply Now',
    examDate: 'Exam Date',
    resultDate: 'Result Date',
    viewDetails: 'View Details',
    status: 'Status',
    category: 'Category',
    selectExam: 'Select Exam',
    weeks: 'weeks',
    week: 'Week',
    months: 'months',
    month: 'month',
    hours: 'hours',
    days: 'days',
    of: 'of',
    done: 'Done',
    // Exams page
    browseExamsDesc: 'Find government exam notifications that match your career goals',
    examSearchPlaceholder: 'Search exams by title, category, conducting body...',
    // Exam Detail tabs
    examTabOverview: 'Overview',
    examTabEligibility: 'Eligibility',
    examTabSyllabus: 'Syllabus',
    examTabPattern: 'Exam Pattern',
    examTabPYQ: 'Previous Year Papers',
    examTabSalary: 'Salary & Career',
    examTabApply: 'How to Apply',
    lastDateApply: 'Last Date to Apply',
    // Exam Calendar
    examCalendarTitle: 'Exam Calendar',
    examCalendarDesc: 'Upcoming government exam dates, application deadlines, and schedules at a glance',
    searchExamsByName: 'Search exams by name...',
    tentativeDatesNote: 'All dates are tentative and subject to change. Always verify from the official notification.',
    noExamsFound: 'No exams found',
    noExamsFoundDesc: 'No upcoming exam dates match your filters. Try adjusting the category or search term.',
    lastDateToApply: 'Last Date to Apply',
    addToGoogleCal: 'Add to Google Calendar',
    downloadICS: 'Download calendar file',
    setReminder: 'Set reminder',
    removeReminder: 'Remove reminder',
    stayUpdated: 'Stay Updated',
    // Resources
    studyResources: 'Study Resources Hub',
    studyResourcesDesc: 'On-site quick-reference notes and curated links for your preparation',
    searchResources: 'Search by title, exam, keyword...',
    // Current Affairs
    currentAffairsDesc: 'Stay updated with the latest events and news',
    dailyDigest: 'Daily Digest',
    searchCurrentAffairs: 'Search current affairs...',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    downloadDigest: 'Download Weekly Digest',
    // AI Guide
    careerGuideDesc: 'Get personalized career guidance based on your profile',
    // Results
    latestResults: 'Latest Government Exam Results',
    latestResultsDesc: 'Check result status and official links for all major exams',
    howToCheckResult: 'How to Check Your Result',
    checkResult: 'Check Result',
    // Admit Card
    admitCards: 'Government Exam Admit Cards',
    admitCardsDesc: 'Track admit card release dates and download links',
    howToDownload: 'How to Download',
    examDayChecklist: 'Exam Day Checklist',
    downloadAdmitCard: 'Download Admit Card',
    // Answer Keys
    answerKeysTitle: 'Government Exam Answer Keys',
    answerKeysDesc: 'Track answer key release dates and objection process',
    // Cut-Off
    cutOffTitle: 'Cut-Off Marks',
    cutOffDesc: 'Browse previous year cut-off marks for all major exams',
    officialCutOff: 'Official Cut-Off',
    // Mind Maps
    syllabusMindMaps: 'Syllabus Mind Maps',
    mindMapsDesc: 'Interactive flow-chart breakdowns for all major government exams',
    // Compare Exams
    compareExamsTitle: 'Compare Government Exams Side by Side',
    compareExamsDesc: 'Select 2 or 3 exams to compare eligibility, salary, syllabus, and more',
    selectExamsToCompare: 'Select exams to compare',
    popularComparisons: 'Popular Comparisons',
    // Salary Calculator
    salaryCalcTitle: 'Government Job Salary Calculator',
    selectPost: 'Select Post',
    cityType: 'City Type (for HRA)',
    monthlyBreakdown: 'Monthly Salary Breakdown',
    basicPay: 'Basic Pay',
    dearnessAllowance: 'Dearness Allowance',
    houseRentAllowance: 'House Rent Allowance',
    transportAllowance: 'Transport Allowance (with DA)',
    grossSalary: 'Gross Salary',
    npsDeduction: 'NPS Deduction (10%)',
    estimatedTax: 'Estimated Tax',
    estimatedTakeHome: 'Estimated Take-Home',
    annualGrossCTC: 'Annual Gross (CTC)',
    annualTakeHome: 'Annual Take-Home',
    disclaimerTitle: 'Disclaimer',
    salaryDisclaimer: 'These are estimated figures based on 7th CPC pay matrix and expected 8th CPC fitment factor of 2.57x. Actual salary may vary based on posting location, additional allowances, and individual tax slabs.',
    // Prep Time Estimator
    prepTimeTitle: 'Preparation Time Estimator',
    educationLevel: 'Your Education Level',
    hoursAvailable: 'Hours Available Per Day',
    workingProfessional: 'Working Professional?',
    estimateTime: 'Estimate Preparation Time',
    recommendedTime: 'months of focused preparation recommended',
    // Exam Priority Matrix
    examPriorityTitle: 'Exam Priority Matrix',
    examPriorityDesc: 'Which Government Exam Should You Target?',
    filterByQualification: 'Filter by qualification',
    allLevels: 'All Levels',
    // Community
    communityTitle: 'Community Discussion Forum',
    communityDesc: 'Connect with fellow aspirants, share strategies, and discuss exams',
    searchDiscussions: 'Search discussions...',
    askQuestion: 'Ask a Question',
    discussions: 'discussions',
    // Prep Roadmap
    prepRoadmapTitle: 'Preparation Roadmap Generator',
    prepRoadmapDesc: 'Get a personalized week-by-week study plan tailored to your exam',
    targetExam: 'Target Exam',
    selectTargetExam: 'Select your target exam',
    monthsAvailable: 'Months Available',
    selectDuration: 'Select preparation duration',
    studyHoursPerDay: 'Study Hours Per Day',
    selectDailyHours: 'Select daily study hours',
    generateRoadmap: 'Generate Roadmap',
    generateNewRoadmap: 'Generate New Roadmap',
    downloadPrint: 'Download / Print',
    topics: 'Topics',
    dailyHours: 'Daily Hours',
    markComplete: 'Mark Complete',
    completed: 'Completed',
    weeksCompleted: 'weeks completed',
    howItWorks: 'How It Works',
    setDuration: 'Set Duration',
    getRoadmap: 'Get Roadmap',
    supportedExams: 'Supported Exams',
    roadmapDisclaimer: 'This roadmap is generated as a guideline. Adjust the plan based on your strengths, weaknesses, and coaching guidance.',
    progressSavedLocally: 'Progress is saved locally in your browser.',
    // Home page extras
    closingSoon: 'Closing Soon',
    browseByCategory: 'Browse by',
    categoryHighlight: 'Category',
    categoriesSubtext: '16 sectors, 500+ exams — find your path',
    viewAllCategories: 'View all categories',
    freeToolsTo: 'Free Tools to',
    succeed: 'Succeed',
    freeToolsDesc: 'Everything you need for government exam preparation',
    govtExamsCovered: 'Government Exams Covered',
    dailyCAUpdates: 'Daily Current Affairs Updates',
    freeStudyResources: 'Free Study Resources',
    joinCTA: 'Join thousands of aspirants using GovtExamPath to crack government exams.',
    subscribedMsg: 'Subscribed! Check your inbox.',
    emailPlaceholder: 'Get exam updates via email',
    // BlogPost
    share: 'Share',
    tags: 'Tags:',
    relatedArticles: 'Related Articles',
    relatedExams: 'Related Exams',
    relatedExamsDesc: 'Explore exam pages related to this article',
    // CurrentAffairs extras
    updatedDaily: 'Updated Daily',
    articles: 'articles',
    todayTopStories: "Today's top stories for exam aspirants",
    topStory: 'TOP STORY',
    trending: 'TRENDING',
    newBadge: 'NEW',
    importantFor: 'Important for:',
    readOn: 'Read on',
    showingArticles: 'Showing',
    articleCount: 'article',
    articlesCount: 'articles',
    inCategory: 'in',
    forPeriod: 'for',
    noCAFound: 'No current affairs found matching your filters.',
    weeklyDigest: 'Weekly Digest',
    // CutOff extras
    cutOffDisclaimer: 'Cut-off marks are based on previous year data and may vary. Check official websites for latest cut-offs.',
    searchCutOff: 'Search by exam name or conducting body...',
    noExamsMatchSearch: 'No exams found matching your search.',
    previousYearCutOff: 'Previous Year Cut-Off (Approx.)',
    // ExamCalendar extras
    examsAcrossMonths: 'exams across',
    monthsLabel: 'months',
    noUpcomingExams: 'There are no upcoming exam dates to display at this time.',
    // Results extras
    searchResultsPlaceholder: 'Search by exam name or conducting body...',
    noExamsMatchResult: 'No exams found matching your search.',
    // Admit Card extras
    admitCardSearchPlaceholder: 'Search by exam name...',
    // Community extras
    replies: 'replies',
    joinDiscussion: 'Join Discussion',
    comingSoon: 'Coming Soon',
    communityComingSoon: 'Community features are being built. Share strategies and discuss exams with fellow aspirants.',
    // Compare Exams extras
    selectExam1: 'Select Exam 1',
    selectExam2: 'Select Exam 2',
    noExamsToCompare: 'No exams found',
    // Salary Calculator extras
    salaryCalcDesc: 'Estimate your monthly take-home salary for any government post under the 7th and expected 8th Pay Commission',
    payCommission8th: '8th Pay Commission (Expected)',
    payCommission7th: '7th CPC (Current)',
    payCommission8thExpected: '8th CPC (Expected)',
    fitmentFactor: 'Fitment factor 2.57x — expected from January 2027',
    // Prep Time extras
    prepTimeDesc: 'Find out how long you need to prepare for your target exam',
    graduate: 'Graduate',
    postGraduate: 'Post Graduate',
    twelfthPass: '12th Pass',
    tenthPass: '10th Pass',
    eligibilityCheckerDesc: 'Instantly find exams you qualify for',
    freeResourcesDesc: '60+ study materials, papers & book lists',
    aboutThisSection: 'About this section',
    onSiteNotes: 'On-Site Notes',
    officialGuidesAndPYQs: 'Official Guides & PYQs',
    allTypes: 'All Types',
    noResourcesFound: 'No resources found matching your filters.',
    collapseNotes: 'Collapse Notes',
    readNotesHere: 'Read Notes Here',
    viewOnGovtExamPath: 'View on GovtExamPath',
    officialGuideLabel: 'Official Guide',
    prevYearPapers: 'Prev. Year Papers',
    bookList: 'Book List',
    howToUseResources: 'How to Use This Resources Hub',
    clickToExpand: 'Click on any node to expand or collapse its topics',
    howToUseMindMaps: 'How to Use Syllabus Mind Maps',
    joinAspirants: 'Join 10,000+ Aspirants',
    discussionCategories: 'Discussion Categories',
    popularDiscussions: 'Popular Discussions',
    showAll: 'Show All',
    noDiscussionsFound: 'No discussions found',
    tryDifferentFilter: 'Try a different category or search term.',
    pinned: 'Pinned',
    yourPost: 'Your Post',
    reply: 'reply',
    joinOurCommunities: 'Join Our Communities',
    members: 'members',
    joinNow: 'Join Now',
    shareYourDoubt: 'Share your doubt with the community',
    yourQuestion: 'Your Question',
    questionPlaceholder: 'Type your question here...',
    postsSavedLocally: 'Posts are saved locally. Community backend coming soon!',
    postQuestion: 'Post Question',
    startExamPrep: 'Start Your Exam Preparation Today',
    startExamPrepDesc: 'Use our free tools to find exams that match your profile, build a study plan, and connect with fellow aspirants.',
    showLess: 'Show Less',
    pdfDialogOpened: 'PDF print dialog opened. Choose "Save as PDF" to download.',
    popupBlocked: 'Pop-up blocked. Please allow pop-ups and try again.',
    downloadFailed: 'Download failed. Please try again.',
    todaysTopStories: "Today's top stories for exam aspirants",
    smartExamSelection: 'Smart Exam Selection',
    examsCompared: 'Exams Compared',
    priorityQuadrants: 'Priority Quadrants',
    hiddenGems: 'Hidden Gems',
    eyeOpener: "Eye-Opener: The Numbers Don't Lie",
    whatMostChoose: 'What most people choose',
    competitionRatio: 'competition ratio',
    insteadTry: 'Instead try',
    whatSmartChoose: 'What smart aspirants choose',
    vacancies: 'Vacancies',
    applicants: 'Applicants',
    competition: 'Competition',
    startingSalary: 'Starting Salary',
    prepTimeLabel: 'Prep Time',
    whySkipped: 'Why Most Aspirants Skip This Exam',
    realityCheck: 'Reality Check',
    keyAdvantages: 'Key Advantages',
    ourTake: 'Our take',
    checkEligibilityBtn: 'Check Eligibility',
    estimatePrepTime: 'Estimate Prep Time',
    viewFullDetails: 'View Full Details',
    noExamsMatch: 'No exams match this qualification level',
    competitionLandscape: 'Competition Landscape',
    competitionLandscapeDesc: 'Applicants-per-seat ratio for major exams (lower is better for you)',
    bestSalaryRatio: 'Best Salary-to-Competition Ratio',
    bestSalaryRatioDesc: 'Exams where you get the highest pay for the lowest competition',
    selectExamLabel: 'Select Exam',
    searchExamsPlaceholder: 'Search exams by name or category...',
    examCategoryLabel: 'Exam Category',
    relevantBackground: 'Relevant Background',
    selectYourBackground: 'Select Your Background',
    selectEducationLevel: 'Select Education Level',
    estimatedTimeline: 'Estimated preparation timeline based on your profile',
    focusedPrep: 'of focused preparation recommended',
    confidenceLabel: 'Confidence',
    prepTimeline: 'Preparation Timeline',
    tipsFor: 'Tips for',
    examsLabel: 'Exams',
    startPreparing: 'Start Preparing',
    avgPrepTime: 'Average Preparation Time for',
    popularExams: 'Popular Exams',
    prepDisclaimer: 'These estimates are indicative and based on general preparation patterns. Actual preparation time may vary based on individual learning speed, study methodology, coaching support, and other factors.',
    noExamsFoundDropdown: 'No exams found',
    // EligibilityChecker extras
    eligTitle: 'Eligibility',
    eligTitleHighlight: 'Checker',
    eligOutOf: 'Out of',
    eligExamsChecked: 'government exams checked, you are eligible for',
    eligExamsLabel: 'exams',
    eligAgeLabel: 'Age',
    eligQualLabel: 'Qual',
    eligAttemptsLabel: 'Attempts',
    eligNationalityLabel: 'Nationality',
    eligRelaxationLabel: 'relaxation',
    eligPhysicalLabel: 'Physical',
    eligUnderstandingTitle: 'Understanding Eligibility Criteria for Government Exams',
    eligAgeLimitsTitle: 'Age Limits Across Major Exams',
    eligExamSector: 'Exam Sector',
    eligRepExam: 'Representative Exam',
    eligMinAge: 'Min Age',
    eligMaxAgeGen: 'Max Age (General)',
    eligKeyNotes: 'Key Notes',
    eligEduQualTitle: 'Educational Qualification Requirements',
    eligAgeRelaxTitle: 'Age Relaxation Rules',
    eligMythsTitle: 'Common Eligibility Myths Debunked',
    // PrepRoadmap extras
    phaseTipFoundation: 'Build strong basics now — they pay dividends in every phase ahead. Focus on understanding concepts, not memorizing.',
    phaseTipAdvanced: 'You have the basics — now go deeper. Connect topics across subjects and practice application-level questions.',
    phaseTipRevision: 'Revisit everything systematically. Use previous year papers to identify weak areas and fill knowledge gaps.',
    phaseTipSprint: 'Trust your preparation. Focus on time management, stay calm, and do targeted revision of high-yield topics.',
    monthLabel: 'month',
    hoursLabel: 'hours',
    printBtn: 'Print',
    downloadPdfBtn: 'Download PDF',
    weeksLabel: 'weeks',
    weekLabel: 'Week',
    doneLabel: 'Done',
    ofTotalTime: 'of total time',
    milestoneLabel: 'Milestone',
    resourcesLabel: 'Resources',
    selectExamDesc: 'Choose from 13+ government exams with detailed syllabus data',
    setDurationDesc: 'Pick your available preparation time from 1 to 24 months',
    dailyHoursDesc: 'Tell us how many hours you can dedicate each day',
    getRoadmapDesc: 'Receive a week-by-week plan with topics, resources & tracking',
    // AIGuide extras
    enterYourAge: 'Enter your age...',
    typeYourMessage: 'Type your message...',
    eligCheckerLink: 'Eligibility Checker',
    checkEligibilityLink: 'Check exam eligibility',
    mindMapsLink: 'Mind Maps',
    exploreSyllabiLink: 'Explore exam syllabi',
    resourcesLink: 'Resources',
    studyMaterialsLink: 'Study materials',
    // Profile page
    profileTitle: 'My Profile',
    profileFullName: 'Full Name',
    profileEditProfile: 'Edit Profile',
    profileSaveChanges: 'Save Changes',
    profileCancel: 'Cancel',
    contactEmailAddress: 'Email Address',
    // ForgotPassword
    forgotPwdTitle: 'Forgot Password',
    forgotPwdSubtitle: 'Enter your email and we\'ll send you a reset link',
    // EligibilityChecker form
    eligCheckerDesc: 'Check which government exams you\'re eligible for based on your age, education, and category',
    eligYourAge: 'Your Age',
    eligEnterAge: 'Enter your age (14-60)',
    eligHighestQual: 'Highest Qualification',
    eligSelectQual: 'Select qualification',
    eligQual10: '10th Pass',
    eligQual12: '12th Pass',
    eligQualDiploma: 'Diploma',
    eligQualGrad: 'Graduation',
    eligQualPG: 'Post Graduation',
    eligCatLabel: 'Category',
    eligCatGeneral: 'General',
    eligCatEWS: 'EWS (Economically Weaker Section)',
    eligCatOBC: 'OBC (Non-Creamy Layer)',
    eligCatSC: 'SC (Scheduled Caste)',
    eligCatST: 'ST (Scheduled Tribe)',
    eligCheckBtn: 'Check My Eligibility',
    eligResultsFor: 'Results for age',
    eligEligibleLabel: 'Eligible',
    eligAlmostLabel: 'Almost Eligible',
    eligNotEligibleLabel: 'Not Eligible',
    eligShowAllBtn: 'Show all',
    eligShowLess: 'Show less',
    eligNotEligibleExams: 'not eligible exams',
    eligGetRecommend: 'Get Personalized Exam Recommendations',
  },
  hi: {
    home: 'होम',
    exams: 'परीक्षाएं',
    tools: 'उपकरण',
    resources: 'संसाधन',
    currentAffairs: 'समसामयिकी',
    blog: 'ब्लॉग',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफाइल',
    bookmarks: 'बुकमार्क',
    notifications: 'सूचनाएं',
    logout: 'लॉगआउट',
    search: 'खोजें',
    searchExams: 'शीर्षक, श्रेणी से परीक्षा खोजें...',
    browseExams: 'परीक्षाएं ब्राउज़ करें',
    allExams: 'सभी परीक्षाएं',
    allCategories: 'सभी',
    openNow: 'अभी खुला है',
    viewAll: 'सभी देखें',
    exploreExams: 'परीक्षाएं देखें',
    careerGuide: 'करियर गाइड',
    eligibilityChecker: 'पात्रता जांचें',
    mindMaps: 'सिलेबस माइंड मैप',
    freeResources: 'मुफ्त संसाधन',
    examCalendar: 'परीक्षा कैलेंडर',
    examPriority: 'परीक्षा प्राथमिकता मैट्रिक्स',
    prepRoadmap: 'तैयारी रोडमैप',
    cutOff: 'कट-ऑफ अंक',
    compareExams: 'परीक्षाओं की तुलना',
    prepTime: 'तैयारी समय अनुमान',
    salaryCalc: 'वेतन कैलकुलेटर',
    about: 'हमारे बारे में',
    aboutUs: 'हमारे बारे में',
    contact: 'संपर्क',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    disclaimer: 'अस्वीकरण',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    getStarted: 'मुफ्त शुरू करें',
    subscribe: 'सदस्यता लें',
    readMore: 'और पढ़ें',
    latestExams: 'नवीनतम परीक्षाएं',
    successStories: 'सफलता की कहानियां',
    free: 'मुफ्त',
    students: 'छात्र',
    categories: 'श्रेणियां',
    examCategories: 'परीक्षा श्रेणियां',
    language: 'भाषा',
    hindi: 'हिन्दी',
    english: 'English',
    quickLinks: 'त्वरित लिंक',
    contactNewsletter: 'संपर्क और समाचार पत्र',
    weeklyUpdates: 'साप्ताहिक परीक्षा अपडेट पाएं',
    yourEmail: 'आपका ईमेल',
    subscribedSuccess: 'सफलतापूर्वक सदस्यता ली!',
    copyright: 'सर्वाधिकार सुरक्षित। भारत के भावी सिविल सेवकों के लिए बनाया गया।',
    adminPanel: 'एडमिन पैनल',
    policies: 'नीतियां',
    heroTag: 'सरकारी नौकरियों के लिए मुफ्त करियर मार्गदर्शन',
    heroTitle1: 'आपका रास्ता',
    heroTitle2: 'सफलता',
    heroSubtitle: '500+ सरकारी परीक्षाएं खोजें, पात्रता जांचें, और मुफ्त तैयारी संसाधन प्राप्त करें।',
    checkEligibility: 'पात्रता जांचें',
    whyChoose: 'क्यों चुनें',
    govtExamPath: 'GovtExamPath',
    whyChooseDesc: 'हम सरकारी परीक्षाओं को नेविगेट करने में आपकी मदद के लिए व्यापक, सटीक और अद्यतित जानकारी प्रदान करते हैं।',
    freeForever: 'हमेशा मुफ्त',
    freeForeverDesc: 'सभी सुविधाएं पूरी तरह मुफ्त। कोई छिपा शुल्क नहीं।',
    alwaysUpdated: 'हमेशा अपडेटेड',
    alwaysUpdatedDesc: 'परीक्षा तिथियों, परिणामों और सूचनाओं पर रीयल-टाइम अपडेट।',
    officialSources: 'आधिकारिक स्रोत',
    officialSourcesDesc: 'सभी जानकारी आधिकारिक सरकारी स्रोतों से सत्यापित।',
    multiLanguage: 'बहु-भाषा',
    multiLanguageDesc: 'अंग्रेजी, हिंदी और तेलुगु में उपलब्ध।',
    examsCovered: 'परीक्षाएं कवर',
    dailyUpdates: 'दैनिक अपडेट',
    activeStudents: 'सक्रिय छात्र',
    languages: 'भाषाएं',
    topExamCategories: 'शीर्ष परीक्षा श्रेणियां',
    whatStudentsSay: 'GovtExamPath क्यों चुनें',
    readyToStart: 'अपनी यात्रा शुरू करने के लिए तैयार?',
    readyToStartDesc: 'हजारों उम्मीदवारों से जुड़ें जो अपनी परीक्षा तैयारी के लिए GovtExamPath पर भरोसा करते हैं।',
    startExploring: 'खोजना शुरू करें',
    welcomeBack: 'वापसी पर स्वागत है',
    signInToContinue: 'अपनी परीक्षा तैयारी जारी रखने के लिए साइन इन करें',
    emailAddress: 'ईमेल पता',
    password: 'पासवर्ड',
    enterEmail: 'अपना ईमेल दर्ज करें',
    enterPassword: 'अपना पासवर्ड दर्ज करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signIn: 'साइन इन',
    signingIn: 'साइन इन हो रहा है...',
    orContinueWith: 'या इसके साथ जारी रखें',
    dontHaveAccount: 'खाता नहीं है?',
    createOneFree: 'मुफ्त बनाएं',
    loginBenefit1: 'व्यक्तिगत परीक्षा सिफारिशें प्राप्त करें',
    loginBenefit2: 'अपनी बुकमार्क की गई परीक्षाओं और डेडलाइन को ट्रैक करें',
    loginBenefit3: 'महत्वपूर्ण परीक्षा सूचनाएं प्राप्त करें',
    createAccount: 'खाता बनाएं',
    joinCommunity: 'सरकारी परीक्षा उम्मीदवारों के समुदाय से जुड़ें',
    fullName: 'पूरा नाम',
    enterFullName: 'अपना पूरा नाम दर्ज करें',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    reEnterPassword: 'पासवर्ड दोबारा दर्ज करें',
    agreeToTerms: 'मैं सहमत हूं',
    termsAndConditions: 'नियम और शर्तें',
    andThe: 'और',
    creatingAccount: 'खाता बनाया जा रहा है...',
    alreadyHaveAccount: 'पहले से खाता है?',
    signInHere: 'यहां साइन इन करें',
    regBenefit1: 'व्यक्तिगत करियर सिफारिशें',
    regBenefit2: 'रीयल-टाइम परीक्षा सूचनाएं',
    regBenefit3: 'मुफ्त अध्ययन संसाधन और माइंड मैप',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    savedExams: 'सहेजी गई परीक्षाएं',
    newNotifications: 'नई सूचनाएं',
    accountStatus: 'खाता स्थिति',
    activeAccount: 'सक्रिय',
    quickActions: 'त्वरित कार्य',
    recentBookmarks: 'हाल के बुकमार्क',
    latestExamsForYou: 'आपके लिए नवीनतम परीक्षाएं',
    noBookmarksYet: 'अभी तक कोई बुकमार्क नहीं',
    noExamsAvailable: 'कोई परीक्षा उपलब्ध नहीं',
    loading: 'लोड हो रहा है...',
    noDataFound: 'कोई डेटा नहीं मिला',
    tryAgain: 'पुनः प्रयास करें',
    goBack: 'वापस जाएं',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    submit: 'जमा करें',
    sending: 'भेजा जा रहा है...',
    send: 'भेजें',
    close: 'बंद करें',
    yes: 'हां',
    no: 'नहीं',
    pageNotFound: 'पेज नहीं मिला',
    pageNotFoundDesc: 'आप जो पेज खोज रहे हैं वह मौजूद नहीं है या विकास में है।',
    backToHome: 'होम पर वापस जाएं',
    blogTitle: 'ब्लॉग',
    blogTitleHighlight: 'परीक्षा तैयारी टिप्स और गाइड',
    blogSubtitle: 'सरकारी परीक्षा तैयारी के लिए विशेषज्ञ लेख और गाइड',
    blogSearchPlaceholder: 'लेख खोजें...',
    blogNoResults: 'कोई लेख नहीं मिला',
    blogFeatured: 'विशेष',
    blogCatAll: 'सभी',
    blogCatStrategy: 'रणनीति',
    blogCatExamGuide: 'परीक्षा गाइड',
    blogCatTips: 'टिप्स',
    blogCatCurrentAffairs: 'करंट अफेयर्स',
    blogCatCareer: 'करियर',
    ssHeroTitle: 'सफलता',
    ssHeroHighlight: 'की कहानियां',
    ssHeroSubtitle: 'हम अपने समुदाय से वास्तविक सफलता की कहानियां एकत्र कर रहे हैं',
    aboutHeroSub: 'भारत भर के सरकारी परीक्षा उम्मीदवारों के लिए मुफ्त करियर मार्गदर्शन मंच।',
    aboutFounded: '2026 में स्थापित',
    ourMission: 'हमारा मिशन',
    missionP1: 'GovtExamPath एक सरल लक्ष्य के साथ बनाया गया — भारत के हर उम्मीदवार के लिए सरकारी परीक्षा की जानकारी सुलभ, सटीक और मुफ्त बनाना।',
    missionP2: 'हम मानते हैं कि आर्थिक बाधाएं प्रतिभाशाली व्यक्तियों को गुणवत्तापूर्ण करियर मार्गदर्शन से वंचित नहीं करनी चाहिए।',
    whatWeOffer: 'हम क्या प्रदान करते हैं',
    whatWeOfferSub: 'सरकारी परीक्षा उम्मीदवारों के लिए व्यापक उपकरण और संसाधन।',
    learnMore: 'और जानें',
    expertBlog: 'विशेषज्ञ ब्लॉग',
    aboutFeat1Desc: 'आपकी प्रोफाइल से मेल खाने वाली सर्वोत्तम सरकारी परीक्षाओं को खोजने में AI-आधारित करियर मार्गदर्शन।',
    aboutFeat2Desc: 'अपनी योग्यताओं के आधार पर 500+ सरकारी परीक्षाओं के लिए तुरंत पात्रता जांचें।',
    aboutFeat3Desc: 'परीक्षा पाठ्यक्रम, तैयारी रणनीतियों और विषय संबंधों के लिए विज़ुअल माइंड मैप।',
    aboutFeat4Desc: 'सभी प्रमुख परीक्षाओं के लिए चयनित अध्ययन सामग्री, पिछले वर्ष के प्रश्न पत्र और तैयारी नोट्स।',
    aboutFeat5Desc: 'परीक्षा रणनीतियों, तैयारी सुझावों और करियर मार्गदर्शन पर विशेषज्ञ लेख।',
    aboutFeat6Desc: 'सरकारी परीक्षा तैयारी के लिए आवश्यक दैनिक करंट अफेयर्स अपडेट।',
    whyTrustUs: 'हम पर भरोसा क्यों',
    whyTrustUsSub: 'सटीकता, पारदर्शिता और सुलभता के सिद्धांतों पर निर्मित।',
    trustOfficialSources: 'आधिकारिक स्रोत',
    trustOfficialSourcesDesc: 'सभी जानकारी आधिकारिक सरकारी वेबसाइटों और अधिसूचनाओं से सत्यापित है।',
    trustAlwaysUpdated: 'हमेशा अपडेटेड',
    trustAlwaysUpdatedDesc: 'नवीनतम परीक्षा तिथियों, रिक्तियों और अधिसूचनाओं को प्रतिबिंबित करने के लिए नियमित रूप से अपडेट किया जाता है।',
    trustFreeForever: 'हमेशा मुफ्त',
    trustFreeForeverDesc: 'GovtExamPath पर हर सुविधा पूरी तरह मुफ्त है। कोई छिपे शुल्क नहीं।',
    trustPrivacy: 'गोपनीयता पहले',
    trustPrivacyDesc: 'हम आपका डेटा नहीं बेचते। कोई थर्ड-पार्टी ट्रैकर नहीं।',
    ourTeam: 'हमारी टीम',
    ourTeamSub: 'GovtExamPath के पीछे के लोग।',
    roleCEO: 'संस्थापक और CEO',
    roleTechLead: 'टेक लीड',
    roleContentHead: 'कंटेंट हेड',
    teamBio1: 'भारत भर के सभी उम्मीदवारों के लिए सरकारी परीक्षा तैयारी को सुलभ बनाने के प्रति समर्पित।',
    teamBio2: 'लाखों उम्मीदवारों की सेवा के लिए स्केलेबल और विश्वसनीय तकनीक का निर्माण।',
    teamBio3: 'प्लेटफॉर्म पर हर परीक्षा के लिए सटीक, अच्छी तरह से शोधित सामग्री सुनिश्चित करना।',
    connectWithUs: 'हमसे जुड़ें',
    connectWithUsSub: 'दैनिक अपडेट और परीक्षा सूचनाओं के लिए सोशल मीडिया पर फॉलो करें।',
    statStudentsGuided: 'छात्र मार्गदर्शित',
    statExamsCovered: 'परीक्षाएं कवर',
    statUpdates: 'अपडेट',
    dreamJobTitle: 'सरकारी करियर की ओर अपनी यात्रा शुरू करें',
    dreamJobSub: 'हजारों उम्मीदवारों के साथ जुड़ें जो अपनी परीक्षा तैयारी के लिए GovtExamPath पर भरोसा करते हैं।',
    unavailable: 'उपलब्ध नहीं',
    aboutFollowInsta: 'इंस्टाग्राम पर फॉलो करें',
    aboutSubYoutube: 'यूट्यूब पर सब्सक्राइब करें',
    aboutJoinTelegram: 'टेलीग्राम से जुड़ें',
    aboutFollowX: 'X पर फॉलो करें',
    contactUs: 'संपर्क करें',
    contactSubtitle: 'कोई सवाल या प्रतिक्रिया है? हमें सुनना अच्छा लगेगा।',
    yourName: 'आपका नाम',
    subject: 'विषय',
    message: 'संदेश',
    responseTime: 'प्रतिक्रिया समय',
    location: 'स्थान',
    within24Hours: '24 घंटे के अंदर',
    manageSubscriptions: 'सदस्यता प्रबंधित करें',
    subscribed: 'सदस्यता ली',
    unsubscribeAll: 'सभी से सदस्यता समाप्त करें',
    subscribeAll: 'सभी की सदस्यता लें',
    upcoming: 'आगामी',
    closed: 'बंद',
    showing: 'दिखा रहा है',
    noResultsFound: 'कोई परिणाम नहीं मिला',
    clearAllFilters: 'सभी फ़िल्टर हटाएं',
    visitOfficialSite: 'आधिकारिक साइट पर जाएं',
    downloadPDF: 'पीडीएफ डाउनलोड करें',
    print: 'प्रिंट',
    allStates: 'सभी राज्य',
    apply: 'आवेदन करें',
    applyNow: 'अभी आवेदन करें',
    examDate: 'परीक्षा तिथि',
    resultDate: 'परिणाम तिथि',
    viewDetails: 'विवरण देखें',
    status: 'स्थिति',
    category: 'श्रेणी',
    selectExam: 'परीक्षा चुनें',
    weeks: 'सप्ताह',
    week: 'सप्ताह',
    months: 'महीने',
    month: 'महीना',
    hours: 'घंटे',
    days: 'दिन',
    of: 'का',
    done: 'पूर्ण',
    browseExamsDesc: 'अपने करियर लक्ष्यों से मेल खाती सरकारी परीक्षा अधिसूचनाएं खोजें',
    examSearchPlaceholder: 'शीर्षक, श्रेणी, संचालन निकाय से खोजें...',
    examTabOverview: 'अवलोकन',
    examTabEligibility: 'पात्रता',
    examTabSyllabus: 'पाठ्यक्रम',
    examTabPattern: 'परीक्षा पैटर्न',
    examTabPYQ: 'पिछले वर्ष के प्रश्नपत्र',
    examTabSalary: 'वेतन और करियर',
    examTabApply: 'आवेदन कैसे करें',
    lastDateApply: 'आवेदन की अंतिम तिथि',
    examCalendarTitle: 'परीक्षा कैलेंडर',
    examCalendarDesc: 'आगामी सरकारी परीक्षा तिथियां, आवेदन की अंतिम तिथि और समय-सारणी',
    searchExamsByName: 'परीक्षा का नाम खोजें...',
    tentativeDatesNote: 'सभी तिथियां अस्थायी हैं और बदल सकती हैं। हमेशा आधिकारिक अधिसूचना से सत्यापित करें।',
    noExamsFound: 'कोई परीक्षा नहीं मिली',
    noExamsFoundDesc: 'आपके फ़िल्टर से मेल खाती कोई परीक्षा तिथि नहीं है। श्रेणी या खोज शब्द बदलें।',
    lastDateToApply: 'आवेदन की अंतिम तिथि',
    addToGoogleCal: 'Google कैलेंडर में जोड़ें',
    downloadICS: 'कैलेंडर फ़ाइल डाउनलोड करें',
    setReminder: 'रिमाइंडर सेट करें',
    removeReminder: 'रिमाइंडर हटाएं',
    stayUpdated: 'अपडेट रहें',
    studyResources: 'अध्ययन संसाधन केंद्र',
    studyResourcesDesc: 'तैयारी के लिए त्वरित संदर्भ नोट्स और चयनित लिंक',
    searchResources: 'शीर्षक, परीक्षा, कीवर्ड से खोजें...',
    currentAffairsDesc: 'नवीनतम घटनाओं और समाचारों से अपडेट रहें',
    dailyDigest: 'दैनिक डाइजेस्ट',
    searchCurrentAffairs: 'समसामयिकी खोजें...',
    today: 'आज',
    thisWeek: 'इस सप्ताह',
    thisMonth: 'इस महीने',
    downloadDigest: 'साप्ताहिक डाइजेस्ट डाउनलोड करें',
    careerGuideDesc: 'अपनी प्रोफ़ाइल के आधार पर व्यक्तिगत करियर मार्गदर्शन प्राप्त करें',
    latestResults: 'नवीनतम सरकारी परीक्षा परिणाम',
    latestResultsDesc: 'सभी प्रमुख परीक्षाओं के परिणाम की स्थिति और आधिकारिक लिंक देखें',
    howToCheckResult: 'परिणाम कैसे देखें',
    checkResult: 'परिणाम देखें',
    admitCards: 'सरकारी परीक्षा प्रवेश पत्र',
    admitCardsDesc: 'प्रवेश पत्र जारी होने की तिथि और डाउनलोड लिंक ट्रैक करें',
    howToDownload: 'कैसे डाउनलोड करें',
    examDayChecklist: 'परीक्षा दिवस चेकलिस्ट',
    downloadAdmitCard: 'प्रवेश पत्र डाउनलोड करें',
    answerKeysTitle: 'सरकारी परीक्षा उत्तर कुंजी',
    answerKeysDesc: 'उत्तर कुंजी जारी होने की तिथि और आपत्ति प्रक्रिया ट्रैक करें',
    cutOffTitle: 'कट-ऑफ अंक',
    cutOffDesc: 'सभी प्रमुख परीक्षाओं के पिछले वर्ष के कट-ऑफ अंक देखें',
    officialCutOff: 'आधिकारिक कट-ऑफ',
    syllabusMindMaps: 'सिलेबस माइंड मैप',
    mindMapsDesc: 'सभी प्रमुख सरकारी परीक्षाओं के लिए इंटरैक्टिव फ्लो-चार्ट',
    compareExamsTitle: 'सरकारी परीक्षाओं की तुलना करें',
    compareExamsDesc: 'पात्रता, वेतन, सिलेबस और अधिक की तुलना के लिए 2 या 3 परीक्षाएं चुनें',
    selectExamsToCompare: 'तुलना के लिए परीक्षाएं चुनें',
    popularComparisons: 'लोकप्रिय तुलनाएं',
    salaryCalcTitle: 'सरकारी नौकरी वेतन कैलकुलेटर',
    selectPost: 'पद चुनें',
    cityType: 'शहर का प्रकार (HRA के लिए)',
    monthlyBreakdown: 'मासिक वेतन विवरण',
    basicPay: 'मूल वेतन',
    dearnessAllowance: 'महंगाई भत्ता',
    houseRentAllowance: 'मकान किराया भत्ता',
    transportAllowance: 'परिवहन भत्ता (DA सहित)',
    grossSalary: 'कुल वेतन',
    npsDeduction: 'NPS कटौती (10%)',
    estimatedTax: 'अनुमानित कर',
    estimatedTakeHome: 'अनुमानित हाथ में वेतन',
    annualGrossCTC: 'वार्षिक सकल (CTC)',
    annualTakeHome: 'वार्षिक हाथ में वेतन',
    disclaimerTitle: 'अस्वीकरण',
    salaryDisclaimer: 'ये 7वें वेतन आयोग और अपेक्षित 8वें वेतन आयोग के फिटमेंट फैक्टर 2.57x पर आधारित अनुमानित आंकड़े हैं। वास्तविक वेतन पोस्टिंग स्थान, अतिरिक्त भत्तों और व्यक्तिगत कर स्लैब के आधार पर भिन्न हो सकता है।',
    prepTimeTitle: 'तैयारी समय अनुमानक',
    educationLevel: 'आपकी शिक्षा का स्तर',
    hoursAvailable: 'प्रतिदिन उपलब्ध घंटे',
    workingProfessional: 'कार्यरत पेशेवर?',
    estimateTime: 'तैयारी समय का अनुमान लगाएं',
    recommendedTime: 'महीने की केंद्रित तैयारी की सिफारिश',
    examPriorityTitle: 'परीक्षा प्राथमिकता मैट्रिक्स',
    examPriorityDesc: 'आपको कौन सी सरकारी परीक्षा लक्ष्य करनी चाहिए?',
    filterByQualification: 'योग्यता के अनुसार फ़िल्टर',
    allLevels: 'सभी स्तर',
    communityTitle: 'सामुदायिक चर्चा मंच',
    communityDesc: 'साथी उम्मीदवारों से जुड़ें, रणनीतियां साझा करें और परीक्षाओं पर चर्चा करें',
    searchDiscussions: 'चर्चाएं खोजें...',
    askQuestion: 'प्रश्न पूछें',
    discussions: 'चर्चाएं',
    prepRoadmapTitle: 'तैयारी रोडमैप जनरेटर',
    prepRoadmapDesc: 'अपनी परीक्षा के अनुसार व्यक्तिगत साप्ताहिक अध्ययन योजना प्राप्त करें',
    targetExam: 'लक्ष्य परीक्षा',
    selectTargetExam: 'अपनी लक्ष्य परीक्षा चुनें',
    monthsAvailable: 'उपलब्ध महीने',
    selectDuration: 'तैयारी अवधि चुनें',
    studyHoursPerDay: 'प्रतिदिन अध्ययन के घंटे',
    selectDailyHours: 'दैनिक अध्ययन घंटे चुनें',
    generateRoadmap: 'रोडमैप बनाएं',
    generateNewRoadmap: 'नया रोडमैप बनाएं',
    downloadPrint: 'डाउनलोड / प्रिंट',
    topics: 'विषय',
    dailyHours: 'दैनिक घंटे',
    markComplete: 'पूर्ण चिह्नित करें',
    completed: 'पूर्ण',
    weeksCompleted: 'सप्ताह पूरे हुए',
    howItWorks: 'यह कैसे काम करता है',
    setDuration: 'अवधि सेट करें',
    getRoadmap: 'रोडमैप पाएं',
    supportedExams: 'समर्थित परीक्षाएं',
    roadmapDisclaimer: 'यह रोडमैप एक दिशानिर्देश के रूप में बनाया गया है। अपनी ताकत, कमजोरियों और कोचिंग मार्गदर्शन के आधार पर योजना में बदलाव करें।',
    progressSavedLocally: 'प्रगति आपके ब्राउज़र में स्थानीय रूप से सहेजी गई है।',
    closingSoon: 'जल्द बंद होने वाला',
    browseByCategory: 'श्रेणी के अनुसार',
    categoryHighlight: 'ब्राउज़ करें',
    categoriesSubtext: '16 क्षेत्र, 500+ परीक्षाएं — अपना रास्ता खोजें',
    viewAllCategories: 'सभी श्रेणियां देखें',
    freeToolsTo: 'सफलता के लिए',
    succeed: 'मुफ्त उपकरण',
    freeToolsDesc: 'सरकारी परीक्षा की तैयारी के लिए सब कुछ',
    govtExamsCovered: 'सरकारी परीक्षाएं शामिल',
    dailyCAUpdates: 'दैनिक करंट अफेयर्स अपडेट',
    freeStudyResources: 'मुफ्त अध्ययन सामग्री',
    joinCTA: 'हजारों छात्रों के साथ जुड़ें जो GovtExamPath का उपयोग करके सरकारी परीक्षाएं पास कर रहे हैं।',
    subscribedMsg: 'सदस्यता ली! अपना इनबॉक्स जांचें।',
    emailPlaceholder: 'ईमेल से परीक्षा अपडेट प्राप्त करें',
    share: 'शेयर',
    tags: 'टैग:',
    relatedArticles: 'संबंधित लेख',
    relatedExams: 'संबंधित परीक्षाएं',
    relatedExamsDesc: 'इस लेख से संबंधित परीक्षा पृष्ठ देखें',
    updatedDaily: 'दैनिक अपडेट',
    articles: 'लेख',
    todayTopStories: 'परीक्षा अभ्यर्थियों के लिए आज की शीर्ष कहानियां',
    topStory: 'शीर्ष कहानी',
    trending: 'ट्रेंडिंग',
    newBadge: 'नया',
    importantFor: 'इसके लिए महत्वपूर्ण:',
    readOn: 'पढ़ें',
    showingArticles: 'दिखा रहा है',
    articleCount: 'लेख',
    articlesCount: 'लेख',
    inCategory: 'में',
    forPeriod: 'के लिए',
    noCAFound: 'आपके फ़िल्टर से कोई करंट अफेयर्स नहीं मिला।',
    weeklyDigest: 'साप्ताहिक डाइजेस्ट',
    cutOffDisclaimer: 'कट-ऑफ अंक पिछले वर्ष के आंकड़ों पर आधारित हैं और भिन्न हो सकते हैं। नवीनतम कट-ऑफ के लिए आधिकारिक वेबसाइट देखें।',
    searchCutOff: 'परीक्षा नाम या आयोजक संस्था से खोजें...',
    noExamsMatchSearch: 'आपकी खोज से कोई परीक्षा नहीं मिली।',
    previousYearCutOff: 'पिछले वर्ष कट-ऑफ (अनुमानित)',
    examsAcrossMonths: 'परीक्षाएं',
    monthsLabel: 'महीनों में',
    noUpcomingExams: 'इस समय प्रदर्शित करने के लिए कोई आगामी परीक्षा तिथियां नहीं हैं।',
    searchResultsPlaceholder: 'परीक्षा नाम या आयोजक संस्था से खोजें...',
    noExamsMatchResult: 'आपकी खोज से कोई परीक्षा नहीं मिली।',
    admitCardSearchPlaceholder: 'परीक्षा नाम से खोजें...',
    replies: 'जवाब',
    joinDiscussion: 'चर्चा में शामिल हों',
    comingSoon: 'जल्द आ रहा है',
    communityComingSoon: 'सामुदायिक सुविधाएं बनाई जा रही हैं। साथी अभ्यर्थियों के साथ रणनीतियां साझा करें।',
    selectExam1: 'परीक्षा 1 चुनें',
    selectExam2: 'परीक्षा 2 चुनें',
    noExamsToCompare: 'कोई परीक्षा नहीं मिली',
    salaryCalcDesc: '7वें और अपेक्षित 8वें वेतन आयोग के तहत किसी भी सरकारी पद के लिए अपने मासिक वेतन का अनुमान लगाएं',
    payCommission8th: '8वां वेतन आयोग (अपेक्षित)',
    payCommission7th: '7वां वेतन आयोग (वर्तमान)',
    payCommission8thExpected: '8वां वेतन आयोग (अपेक्षित)',
    fitmentFactor: 'फिटमेंट फैक्टर 2.57x — जनवरी 2027 से अपेक्षित',
    prepTimeDesc: 'पता लगाएं कि आपको अपनी लक्षित परीक्षा की तैयारी में कितना समय चाहिए',
    graduate: 'स्नातक',
    postGraduate: 'स्नातकोत्तर',
    twelfthPass: '12वीं पास',
    tenthPass: '10वीं पास',
    eligibilityCheckerDesc: 'तुरंत पता करें किन परीक्षाओं के लिए आप योग्य हैं',
    freeResourcesDesc: '60+ अध्ययन सामग्री, प्रश्नपत्र और पुस्तक सूची',
    aboutThisSection: 'इस अनुभाग के बारे में',
    onSiteNotes: 'ऑन-साइट नोट्स',
    officialGuidesAndPYQs: 'आधिकारिक गाइड और PYQ',
    allTypes: 'सभी प्रकार',
    noResourcesFound: 'आपके फ़िल्टर से मेल खाने वाले कोई संसाधन नहीं मिले।',
    collapseNotes: 'नोट्स बंद करें',
    readNotesHere: 'यहाँ नोट्स पढ़ें',
    viewOnGovtExamPath: 'GovtExamPath पर देखें',
    officialGuideLabel: 'आधिकारिक गाइड',
    prevYearPapers: 'पिछले वर्ष के पेपर',
    bookList: 'पुस्तक सूची',
    howToUseResources: 'इस संसाधन केंद्र का उपयोग कैसे करें',
    clickToExpand: 'विषयों को विस्तृत या संक्षिप्त करने के लिए किसी भी नोड पर क्लिक करें',
    howToUseMindMaps: 'सिलेबस माइंड मैप का उपयोग कैसे करें',
    joinAspirants: '10,000+ उम्मीदवारों से जुड़ें',
    discussionCategories: 'चर्चा श्रेणियां',
    popularDiscussions: 'लोकप्रिय चर्चाएं',
    showAll: 'सभी दिखाएं',
    noDiscussionsFound: 'कोई चर्चा नहीं मिली',
    tryDifferentFilter: 'कोई अन्य श्रेणी या खोज शब्द आज़माएं।',
    pinned: 'पिन किया गया',
    yourPost: 'आपकी पोस्ट',
    reply: 'उत्तर',
    joinOurCommunities: 'हमारे समुदायों से जुड़ें',
    members: 'सदस्य',
    joinNow: 'अभी जुड़ें',
    shareYourDoubt: 'अपना सवाल समुदाय के साथ साझा करें',
    yourQuestion: 'आपका प्रश्न',
    questionPlaceholder: 'अपना प्रश्न यहाँ टाइप करें...',
    postsSavedLocally: 'पोस्ट स्थानीय रूप से सहेजी गई हैं। सामुदायिक बैकएंड जल्द आ रहा है!',
    postQuestion: 'प्रश्न पोस्ट करें',
    startExamPrep: 'आज ही अपनी परीक्षा तैयारी शुरू करें',
    startExamPrepDesc: 'अपनी प्रोफ़ाइल से मिलती परीक्षाएं खोजने के लिए हमारे मुफ्त टूल्स का उपयोग करें।',
    showLess: 'कम दिखाएं',
    pdfDialogOpened: 'PDF प्रिंट डायलॉग खुला। डाउनलोड के लिए "PDF के रूप में सहेजें" चुनें।',
    popupBlocked: 'पॉप-अप ब्लॉक हो गया। कृपया पॉप-अप अनुमति दें और पुनः प्रयास करें।',
    downloadFailed: 'डाउनलोड विफल। कृपया पुनः प्रयास करें।',
    todaysTopStories: 'परीक्षा उम्मीदवारों के लिए आज की शीर्ष कहानियां',
    smartExamSelection: 'स्मार्ट परीक्षा चयन',
    examsCompared: 'परीक्षाओं की तुलना',
    priorityQuadrants: 'प्राथमिकता चतुर्भुज',
    hiddenGems: 'छिपे हुए रत्न',
    eyeOpener: 'आंखें खोलने वाला: संख्याएं झूठ नहीं बोलतीं',
    whatMostChoose: 'अधिकांश लोग क्या चुनते हैं',
    competitionRatio: 'प्रतिस्पर्धा अनुपात',
    insteadTry: 'इसके बजाय आज़माएं',
    whatSmartChoose: 'स्मार्ट उम्मीदवार क्या चुनते हैं',
    vacancies: 'रिक्तियां',
    applicants: 'आवेदक',
    competition: 'प्रतिस्पर्धा',
    startingSalary: 'प्रारंभिक वेतन',
    prepTimeLabel: 'तैयारी समय',
    whySkipped: 'अधिकांश उम्मीदवार इस परीक्षा को क्यों छोड़ देते हैं',
    realityCheck: 'वास्तविकता जांच',
    keyAdvantages: 'मुख्य लाभ',
    ourTake: 'हमारी राय',
    checkEligibilityBtn: 'पात्रता जांचें',
    estimatePrepTime: 'तैयारी समय अनुमान',
    viewFullDetails: 'पूर्ण विवरण देखें',
    noExamsMatch: 'इस योग्यता स्तर से मेल खाने वाली कोई परीक्षा नहीं',
    competitionLandscape: 'प्रतिस्पर्धा परिदृश्य',
    competitionLandscapeDesc: 'प्रमुख परीक्षाओं के लिए आवेदक-प्रति-सीट अनुपात (कम आपके लिए बेहतर)',
    bestSalaryRatio: 'सर्वश्रेष्ठ वेतन-से-प्रतिस्पर्धा अनुपात',
    bestSalaryRatioDesc: 'जहां सबसे कम प्रतिस्पर्धा में सबसे अधिक वेतन मिलता है',
    selectExamLabel: 'परीक्षा चुनें',
    searchExamsPlaceholder: 'नाम या श्रेणी से परीक्षा खोजें...',
    examCategoryLabel: 'परीक्षा श्रेणी',
    relevantBackground: 'प्रासंगिक पृष्ठभूमि',
    selectYourBackground: 'अपनी पृष्ठभूमि चुनें',
    selectEducationLevel: 'शिक्षा स्तर चुनें',
    estimatedTimeline: 'आपकी प्रोफ़ाइल के आधार पर अनुमानित तैयारी समयरेखा',
    focusedPrep: 'केंद्रित तैयारी की सिफारिश',
    confidenceLabel: 'विश्वास',
    prepTimeline: 'तैयारी समयरेखा',
    tipsFor: 'के लिए सुझाव',
    examsLabel: 'परीक्षाएं',
    startPreparing: 'तैयारी शुरू करें',
    avgPrepTime: 'औसत तैयारी समय',
    popularExams: 'लोकप्रिय परीक्षाएं',
    prepDisclaimer: 'ये अनुमान सांकेतिक हैं और सामान्य तैयारी पैटर्न पर आधारित हैं।',
    noExamsFoundDropdown: 'कोई परीक्षा नहीं मिली',
    // EligibilityChecker extras
    eligTitle: 'पात्रता',
    eligTitleHighlight: 'जांचकर्ता',
    eligOutOf: 'कुल',
    eligExamsChecked: 'सरकारी परीक्षाओं की जांच में, आप पात्र हैं',
    eligExamsLabel: 'परीक्षाओं के लिए',
    eligAgeLabel: 'आयु',
    eligQualLabel: 'योग्यता',
    eligAttemptsLabel: 'प्रयास',
    eligNationalityLabel: 'राष्ट्रीयता',
    eligRelaxationLabel: 'छूट',
    eligPhysicalLabel: 'शारीरिक',
    eligUnderstandingTitle: 'सरकारी परीक्षाओं के लिए पात्रता मानदंड को समझें',
    eligAgeLimitsTitle: 'प्रमुख परीक्षाओं में आयु सीमा',
    eligExamSector: 'परीक्षा क्षेत्र',
    eligRepExam: 'प्रतिनिधि परीक्षा',
    eligMinAge: 'न्यूनतम आयु',
    eligMaxAgeGen: 'अधिकतम आयु (सामान्य)',
    eligKeyNotes: 'मुख्य नोट्स',
    eligEduQualTitle: 'शैक्षिक योग्यता आवश्यकताएं',
    eligAgeRelaxTitle: 'आयु छूट नियम',
    eligMythsTitle: 'पात्रता से जुड़ी आम भ्रांतियां',
    // PrepRoadmap extras
    phaseTipFoundation: 'अभी मजबूत नींव बनाएं — ये आगे हर चरण में लाभ देगी। अवधारणाओं को समझने पर ध्यान दें, रटने पर नहीं।',
    phaseTipAdvanced: 'आपके पास बुनियाद है — अब गहराई में जाएं। विषयों को आपस में जोड़ें और अनुप्रयोग-स्तरीय प्रश्नों का अभ्यास करें।',
    phaseTipRevision: 'व्यवस्थित रूप से सब कुछ दोहराएं। कमजोर क्षेत्रों की पहचान करने के लिए पिछले वर्ष के प्रश्नपत्रों का उपयोग करें।',
    phaseTipSprint: 'अपनी तैयारी पर भरोसा रखें। समय प्रबंधन पर ध्यान दें, शांत रहें, और उच्च-प्राथमिकता विषयों का लक्षित पुनरावलोकन करें।',
    monthLabel: 'महीना',
    hoursLabel: 'घंटे',
    printBtn: 'प्रिंट',
    downloadPdfBtn: 'PDF डाउनलोड',
    weeksLabel: 'सप्ताह',
    weekLabel: 'सप्ताह',
    doneLabel: 'पूर्ण',
    ofTotalTime: 'कुल समय का',
    milestoneLabel: 'मील का पत्थर',
    resourcesLabel: 'संसाधन',
    selectExamDesc: '13+ सरकारी परीक्षाओं में से विस्तृत पाठ्यक्रम डेटा के साथ चुनें',
    setDurationDesc: '1 से 24 महीने तक अपना उपलब्ध तैयारी समय चुनें',
    dailyHoursDesc: 'बताएं कि आप प्रतिदिन कितने घंटे दे सकते हैं',
    getRoadmapDesc: 'विषयों, संसाधनों और ट्रैकिंग के साथ साप्ताहिक योजना प्राप्त करें',
    // AIGuide extras
    enterYourAge: 'अपनी आयु दर्ज करें...',
    typeYourMessage: 'अपना संदेश टाइप करें...',
    eligCheckerLink: 'पात्रता जांचकर्ता',
    checkEligibilityLink: 'परीक्षा पात्रता जांचें',
    mindMapsLink: 'माइंड मैप्स',
    exploreSyllabiLink: 'परीक्षा पाठ्यक्रम देखें',
    resourcesLink: 'संसाधन',
    studyMaterialsLink: 'अध्ययन सामग्री',
    // Profile page
    profileTitle: 'मेरी प्रोफाइल',
    profileFullName: 'पूरा नाम',
    profileEditProfile: 'प्रोफाइल संपादित करें',
    profileSaveChanges: 'परिवर्तन सहेजें',
    profileCancel: 'रद्द करें',
    contactEmailAddress: 'ईमेल पता',
    // ForgotPassword
    forgotPwdTitle: 'पासवर्ड भूल गए',
    forgotPwdSubtitle: 'अपना ईमेल दर्ज करें, हम आपको रीसेट लिंक भेजेंगे',
    // EligibilityChecker form
    eligCheckerDesc: 'अपनी आयु, शिक्षा और श्रेणी के आधार पर जांचें कि आप किन सरकारी परीक्षाओं के लिए पात्र हैं',
    eligYourAge: 'आपकी आयु',
    eligEnterAge: 'अपनी आयु दर्ज करें (14-60)',
    eligHighestQual: 'उच्चतम योग्यता',
    eligSelectQual: 'योग्यता चुनें',
    eligQual10: '10वीं पास',
    eligQual12: '12वीं पास',
    eligQualDiploma: 'डिप्लोमा',
    eligQualGrad: 'स्नातक',
    eligQualPG: 'स्नातकोत्तर',
    eligCatLabel: 'श्रेणी',
    eligCatGeneral: 'सामान्य',
    eligCatEWS: 'EWS (आर्थिक रूप से कमजोर वर्ग)',
    eligCatOBC: 'OBC (नॉन-क्रीमी लेयर)',
    eligCatSC: 'SC (अनुसूचित जाति)',
    eligCatST: 'ST (अनुसूचित जनजाति)',
    eligCheckBtn: 'मेरी पात्रता जांचें',
    eligResultsFor: 'आयु के लिए परिणाम',
    eligEligibleLabel: 'पात्र',
    eligAlmostLabel: 'लगभग पात्र',
    eligNotEligibleLabel: 'अपात्र',
    eligShowAllBtn: 'सभी दिखाएं',
    eligShowLess: 'कम दिखाएं',
    eligNotEligibleExams: 'अपात्र परीक्षाएं',
    eligGetRecommend: 'व्यक्तिगत परीक्षा सिफारिशें प्राप्त करें',
  },
  te: {
    home: 'హోమ్',
    exams: 'పరీక్షలు',
    tools: 'సాధనాలు',
    resources: 'వనరులు',
    currentAffairs: 'కరెంట్ అఫైర్స్',
    blog: 'బ్లాగ్',
    login: 'లాగిన్',
    register: 'రిజిస్టర్',
    dashboard: 'డాష్‌బోర్డ్',
    profile: 'ప్రొఫైల్',
    bookmarks: 'బుక్‌మార్క్‌లు',
    notifications: 'నోటిఫికేషన్లు',
    logout: 'లాగ్ అవుట్',
    search: 'వెతకండి',
    searchExams: 'శీర్షిక, వర్గం ద్వారా పరీక్షలు వెతకండి...',
    browseExams: 'పరీక్షలు బ్రౌజ్ చేయండి',
    allExams: 'అన్ని పరీక్షలు',
    allCategories: 'అన్ని',
    openNow: 'ఇప్పుడు తెరిచి ఉంది',
    viewAll: 'అన్నీ చూడండి',
    exploreExams: 'పరీక్షలు అన్వేషించండి',
    careerGuide: 'కెరీర్ గైడ్',
    eligibilityChecker: 'అర్హత తనిఖీ',
    mindMaps: 'మైండ్ మ్యాప్స్',
    freeResources: 'ఉచిత వనరులు',
    examCalendar: 'పరీక్ష క్యాలెండర్',
    examPriority: 'పరీక్ష ప్రాధాన్యత మాతృక',
    prepRoadmap: 'తయారీ రోడ్‌మ్యాప్',
    cutOff: 'కట్-ఆఫ్ మార్కులు',
    compareExams: 'పరీక్షలు పోల్చండి',
    prepTime: 'తయారీ సమయ అంచనా',
    salaryCalc: 'జీతం కాల్క్యులేటర్',
    about: 'గురించి',
    aboutUs: 'మా గురించి',
    contact: 'సంప్రదించండి',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'సేవా నిబంధనలు',
    disclaimer: 'నిరాకరణ',
    faq: 'తరచుగా అడిగే ప్రశ్నలు',
    getStarted: 'ఉచితంగా ప్రారంభించండి',
    subscribe: 'సబ్‌స్క్రైబ్',
    readMore: 'మరింత చదవండి',
    latestExams: 'తాజా పరీక్షలు',
    successStories: 'విజయ గాథలు',
    free: 'ఉచితం',
    students: 'విద్యార్థులు',
    categories: 'వర్గాలు',
    examCategories: 'పరీక్ష వర్గాలు',
    language: 'భాష',
    hindi: 'హిందీ',
    english: 'English',
    quickLinks: 'త్వరిత లింకులు',
    contactNewsletter: 'సంప్రదింపు & న్యూస్‌లెటర్',
    weeklyUpdates: 'వారపు పరీక్ష అప్‌డేట్‌లు పొందండి',
    yourEmail: 'మీ ఇమెయిల్',
    subscribedSuccess: 'విజయవంతంగా సబ్‌స్క్రైబ్ చేయబడింది!',
    copyright: 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి. భారతదేశ భావి సివిల్ సర్వెంట్ల కోసం నిర్మించబడింది.',
    adminPanel: 'అడ్మిన్ ప్యానల్',
    policies: 'విధానాలు',
    heroTag: 'ప్రభుత్వ ఉద్యోగాల కోసం ఉచిత కెరీర్ మార్గదర్శకత్వం',
    heroTitle1: 'మీ మార్గం',
    heroTitle2: 'విజయం',
    heroSubtitle: '500+ ప్రభుత్వ పరీక్షలు అన్వేషించండి, అర్హత తనిఖీ చేయండి, మరియు ఉచిత తయారీ వనరులు పొందండి.',
    checkEligibility: 'అర్హత తనిఖీ చేయండి',
    whyChoose: 'ఎందుకు ఎంచుకోవాలి',
    govtExamPath: 'GovtExamPath',
    whyChooseDesc: 'ప్రభుత్వ పరీక్షలలో మీకు సహాయం చేయడానికి మేము సమగ్ర, ఖచ్చితమైన మరియు తాజా సమాచారం అందిస్తాము.',
    freeForever: 'ఎల్లప్పుడూ ఉచితం',
    freeForeverDesc: 'అన్ని ఫీచర్లు పూర్తిగా ఉచితం. దాచిన ఛార్జీలు లేవు.',
    alwaysUpdated: 'ఎల్లప్పుడూ అప్‌డేట్',
    alwaysUpdatedDesc: 'పరీక్ష తేదీలు, ఫలితాలు మరియు నోటిఫికేషన్లపై రియల్-టైమ్ అప్‌డేట్లు.',
    officialSources: 'అధికారిక మూలాలు',
    officialSourcesDesc: 'అన్ని సమాచారం అధికారిక ప్రభుత్వ మూలాల నుండి ధృవీకరించబడింది.',
    multiLanguage: 'బహుభాష',
    multiLanguageDesc: 'ఆంగ్లం, హిందీ మరియు తెలుగులో అందుబాటులో ఉంది.',
    examsCovered: 'పరీక్షలు కవర్',
    dailyUpdates: 'రోజువారీ అప్‌డేట్లు',
    activeStudents: 'యాక్టివ్ విద్యార్థులు',
    languages: 'భాషలు',
    topExamCategories: 'టాప్ పరీక్ష వర్గాలు',
    whatStudentsSay: 'GovtExamPath ఎందుకు ఎంచుకోవాలి',
    readyToStart: 'మీ ప్రయాణం ప్రారంభించడానికి సిద్ధంగా ఉన్నారా?',
    readyToStartDesc: 'వేలాది అభ్యర్థులతో చేరండి, వారు తమ పరీక్ష తయారీ కోసం GovtExamPath ను విశ్వసిస్తారు.',
    startExploring: 'అన్వేషించడం ప్రారంభించండి',
    welcomeBack: 'తిరిగి స్వాగతం',
    signInToContinue: 'మీ పరీక్ష తయారీ కొనసాగించడానికి సైన్ ఇన్ చేయండి',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    enterEmail: 'మీ ఇమెయిల్ నమోదు చేయండి',
    enterPassword: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    rememberMe: 'నన్ను గుర్తుంచుకో',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    signIn: 'సైన్ ఇన్',
    signingIn: 'సైన్ ఇన్ అవుతోంది...',
    orContinueWith: 'లేదా దీనితో కొనసాగించండి',
    dontHaveAccount: 'ఖాతా లేదా?',
    createOneFree: 'ఉచితంగా సృష్టించండి',
    loginBenefit1: 'వ్యక్తిగత పరీక్ష సిఫార్సులు పొందండి',
    loginBenefit2: 'మీ బుక్‌మార్క్ చేసిన పరీక్షలు మరియు గడువులను ట్రాక్ చేయండి',
    loginBenefit3: 'ముఖ్యమైన పరీక్ష నోటిఫికేషన్లు అందుకోండి',
    createAccount: 'ఖాతా సృష్టించండి',
    joinCommunity: 'ప్రభుత్వ పరీక్ష అభ్యర్థుల సమాజంలో చేరండి',
    fullName: 'పూర్తి పేరు',
    enterFullName: 'మీ పూర్తి పేరు నమోదు చేయండి',
    confirmPassword: 'పాస్‌వర్డ్ నిర్ధారించండి',
    reEnterPassword: 'పాస్‌వర్డ్ మళ్ళీ నమోదు చేయండి',
    agreeToTerms: 'నేను అంగీకరిస్తున్నాను',
    termsAndConditions: 'నిబంధనలు & షరతులు',
    andThe: 'మరియు',
    creatingAccount: 'ఖాతా సృష్టించబడుతోంది...',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    signInHere: 'ఇక్కడ సైన్ ఇన్ చేయండి',
    regBenefit1: 'వ్యక్తిగత కెరీర్ సిఫార్సులు',
    regBenefit2: 'రియల్-టైమ్ పరీక్ష నోటిఫికేషన్లు',
    regBenefit3: 'ఉచిత అధ్యయన వనరులు మరియు మైండ్ మ్యాప్‌లు',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    savedExams: 'సేవ్ చేసిన పరీక్షలు',
    newNotifications: 'కొత్త నోటిఫికేషన్లు',
    accountStatus: 'ఖాతా స్థితి',
    activeAccount: 'యాక్టివ్',
    quickActions: 'త్వరిత చర్యలు',
    recentBookmarks: 'ఇటీవలి బుక్‌మార్క్‌లు',
    latestExamsForYou: 'మీ కోసం తాజా పరీక్షలు',
    noBookmarksYet: 'ఇంకా బుక్‌మార్క్‌లు లేవు',
    noExamsAvailable: 'పరీక్షలు అందుబాటులో లేవు',
    loading: 'లోడ్ అవుతోంది...',
    noDataFound: 'డేటా కనుగొనబడలేదు',
    tryAgain: 'మళ్ళీ ప్రయత్నించండి',
    goBack: 'వెనక్కి వెళ్ళండి',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    delete: 'తొలగించండి',
    edit: 'సవరించండి',
    submit: 'సమర్పించండి',
    sending: 'పంపబడుతోంది...',
    send: 'పంపండి',
    close: 'మూసివేయండి',
    yes: 'అవును',
    no: 'కాదు',
    pageNotFound: 'పేజీ కనుగొనబడలేదు',
    pageNotFoundDesc: 'మీరు వెతుకుతున్న పేజీ ఉనికిలో లేదు లేదా అభివృద్ధిలో ఉంది.',
    backToHome: 'హోమ్‌కి తిరిగి వెళ్ళండి',
    blogTitle: 'బ్లాగ్',
    blogTitleHighlight: 'పరీక్ష తయారీ చిట్కాలు & గైడ్‌లు',
    blogSubtitle: 'ప్రభుత్వ పరీక్ష తయారీ కోసం నిపుణుల వ్యాసాలు మరియు గైడ్‌లు',
    blogSearchPlaceholder: 'వ్యాసాలు వెతకండి...',
    blogNoResults: 'వ్యాసాలు కనుగొనబడలేదు',
    blogFeatured: 'ఫీచర్డ్',
    blogCatAll: 'అన్నీ',
    blogCatStrategy: 'వ్యూహం',
    blogCatExamGuide: 'పరీక్ష గైడ్',
    blogCatTips: 'చిట్కాలు',
    blogCatCurrentAffairs: 'కరెంట్ అఫైర్స్',
    blogCatCareer: 'కెరీర్',
    ssHeroTitle: 'విజయ',
    ssHeroHighlight: 'గాథలు',
    ssHeroSubtitle: 'మా సమాజం నుండి నిజమైన విజయ గాథలను సేకరిస్తున్నాము',
    aboutHeroSub: 'భారతదేశం అంతటా ప్రభుత్వ పరీక్ష అభ్యర్థులకు ఉచిత కెరీర్ మార్గదర్శక వేదిక.',
    aboutFounded: '2026లో స్థాపించబడింది',
    ourMission: 'మా లక్ష్యం',
    missionP1: 'GovtExamPath భారతదేశంలోని ప్రతి అభ్యర్థికి ప్రభుత్వ పరీక్ష సమాచారాన్ని అందుబాటులో, ఖచ్చితంగా మరియు ఉచితంగా అందించడం కోసం సృష్టించబడింది.',
    missionP2: 'ఆర్థిక అడ్డంకులు ప్రతిభావంతుల్ని నాణ్యమైన కెరీర్ మార్గదర్శకత్వం పొందకుండా నిరోధించకూడదని మేము నమ్ముతాము.',
    whatWeOffer: 'మేము అందించేవి',
    whatWeOfferSub: 'ప్రభుత్వ పరీక్ష అభ్యర్థుల కోసం సమగ్ర సాధనాలు మరియు వనరులు.',
    learnMore: 'మరింత తెలుసుకోండి',
    expertBlog: 'నిపుణుల బ్లాగ్',
    aboutFeat1Desc: 'మీ ప్రొఫైల్‌కు సరిపోయే ఉత్తమ ప్రభుత్వ పరీక్షలను కనుగొనడంలో AI-ఆధారిత కెరీర్ మార్గదర్శకత్వం.',
    aboutFeat2Desc: 'మీ అర్హతల ఆధారంగా 500+ ప్రభుత్వ పరీక్షలకు తక్షణ అర్హత తనిఖీ.',
    aboutFeat3Desc: 'పరీక్ష సిలబస్, సన్నాహ వ్యూహాలు మరియు విషయ అనుసంధానాల కోసం విజువల్ మైండ్ మ్యాప్‌లు.',
    aboutFeat4Desc: 'అన్ని ప్రధాన పరీక్షల కోసం ఎంపిక చేసిన అధ్యయన సామగ్రి, గత సంవత్సర ప్రశ్న పత్రాలు.',
    aboutFeat5Desc: 'పరీక్ష వ్యూహాలు, సన్నాహ చిట్కాలు మరియు కెరీర్ మార్గదర్శకత్వంపై నిపుణుల వ్యాసాలు.',
    aboutFeat6Desc: 'ప్రభుత్వ పరీక్ష సన్నాహానికి అవసరమైన రోజువారీ కరెంట్ అఫైర్స్ నవీకరణలు.',
    whyTrustUs: 'మమ్మల్ని ఎందుకు నమ్మాలి',
    whyTrustUsSub: 'ఖచ్చితత్వం, పారదర్శకత మరియు అందుబాటు సూత్రాలపై నిర్మించబడింది.',
    trustOfficialSources: 'అధికారిక మూలాలు',
    trustOfficialSourcesDesc: 'అన్ని సమాచారం అధికారిక ప్రభుత్వ వెబ్‌సైట్ల నుండి ధృవీకరించబడింది.',
    trustAlwaysUpdated: 'ఎల్లప్పుడూ నవీకరించబడుతుంది',
    trustAlwaysUpdatedDesc: 'తాజా పరీక్ష తేదీలు, ఖాళీలు మరియు నోటిఫికేషన్లను ప్రతిబింబించడానికి క్రమం తప్పకుండా నవీకరించబడుతుంది.',
    trustFreeForever: 'ఎల్లప్పుడూ ఉచితం',
    trustFreeForeverDesc: 'GovtExamPath లోని ప్రతి ఫీచర్ పూర్తిగా ఉచితం. దాచిన ఛార్జీలు లేవు.',
    trustPrivacy: 'గోప్యత మొదట',
    trustPrivacyDesc: 'మేము మీ డేటాను అమ్మము. థర్డ్-పార్టీ ట్రాకర్లు లేవు.',
    ourTeam: 'మా బృందం',
    ourTeamSub: 'GovtExamPath వెనుక ఉన్న వ్యక్తులు.',
    roleCEO: 'వ్యవస్థాపకురాలు & CEO',
    roleTechLead: 'టెక్ లీడ్',
    roleContentHead: 'కంటెంట్ హెడ్',
    teamBio1: 'భారతదేశం అంతటా అన్ని అభ్యర్థులకు ప్రభుత్వ పరీక్ష సన్నాహాన్ని అందుబాటులోకి తీసుకురావడంలో అభిరుచి.',
    teamBio2: 'లక్షలాది అభ్యర్థులకు సేవ చేయడానికి స్కేలబుల్ మరియు విశ్వసనీయ సాంకేతికతను నిర్మించడం.',
    teamBio3: 'ప్లాట్‌ఫారమ్‌లోని ప్రతి పరీక్ష కోసం ఖచ్చితమైన, బాగా పరిశోధించిన కంటెంట్‌ను నిర్ధారించడం.',
    connectWithUs: 'మాతో అనుసంధానం',
    connectWithUsSub: 'రోజువారీ అప్‌డేట్‌లు మరియు పరీక్ష నోటిఫికేషన్‌ల కోసం సోషల్ మీడియాలో ఫాలో అవ్వండి.',
    statStudentsGuided: 'విద్యార్థులకు మార్గదర్శకత్వం',
    statExamsCovered: 'పరీక్షలు కవర్',
    statUpdates: 'అప్‌డేట్‌లు',
    dreamJobTitle: 'ప్రభుత్వ కెరీర్ వైపు మీ ప్రయాణాన్ని ప్రారంభించండి',
    dreamJobSub: 'తమ పరీక్ష సన్నాహానికి GovtExamPath ను నమ్ముకునే వేలాది అభ్యర్థులతో చేరండి.',
    unavailable: 'అందుబాటులో లేదు',
    aboutFollowInsta: 'ఇన్‌స్టాగ్రామ్‌లో ఫాలో అవ్వండి',
    aboutSubYoutube: 'యూట్యూబ్‌లో సబ్‌స్క్రైబ్ చేయండి',
    aboutJoinTelegram: 'టెలిగ్రామ్‌లో చేరండి',
    aboutFollowX: 'X లో ఫాలో అవ్వండి',
    contactUs: 'మమ్మల్ని సంప్రదించండి',
    contactSubtitle: 'ప్రశ్న లేదా ఫీడ్‌బ్యాక్ ఉందా? మీ నుండి వినాలనుకుంటున్నాము.',
    yourName: 'మీ పేరు',
    subject: 'విషయం',
    message: 'సందేశం',
    responseTime: 'ప్రతిస్పందన సమయం',
    location: 'ప్రదేశం',
    within24Hours: '24 గంటల్లో',
    manageSubscriptions: 'సబ్‌స్క్రిప్షన్లు నిర్వహించండి',
    subscribed: 'సబ్‌స్క్రైబ్ చేయబడింది',
    unsubscribeAll: 'అన్నిటి నుండి అన్‌సబ్‌స్క్రైబ్',
    subscribeAll: 'అన్నింటికి సబ్‌స్క్రైబ్',
    upcoming: 'రాబోయే',
    closed: 'ముగిసింది',
    showing: 'చూపిస్తోంది',
    noResultsFound: 'ఫలితాలు కనుగొనబడలేదు',
    clearAllFilters: 'అన్ని ఫిల్టర్లు తీసివేయండి',
    visitOfficialSite: 'అధికారిక సైట్ సందర్శించండి',
    downloadPDF: 'PDF డౌన్‌లోడ్ చేయండి',
    print: 'ప్రింట్',
    allStates: 'అన్ని రాష్ట్రాలు',
    apply: 'దరఖాస్తు చేయండి',
    applyNow: 'ఇప్పుడు దరఖాస్తు చేయండి',
    examDate: 'పరీక్ష తేదీ',
    resultDate: 'ఫలితం తేదీ',
    viewDetails: 'వివరాలు చూడండి',
    status: 'స్థితి',
    category: 'వర్గం',
    selectExam: 'పరీక్ష ఎంచుకోండి',
    weeks: 'వారాలు',
    week: 'వారం',
    months: 'నెలలు',
    month: 'నెల',
    hours: 'గంటలు',
    days: 'రోజులు',
    of: 'లో',
    done: 'పూర్తయింది',
    browseExamsDesc: 'మీ కెరీర్ లక్ష్యాలకు సరిపోయే ప్రభుత్వ పరీక్ష నోటిఫికేషన్లు కనుగొనండి',
    examSearchPlaceholder: 'శీర్షిక, వర్గం, నిర్వహణ సంస్థ ద్వారా వెతకండి...',
    examTabOverview: 'అవలోకనం',
    examTabEligibility: 'అర్హత',
    examTabSyllabus: 'సిలబస్',
    examTabPattern: 'పరీక్ష పద్ధతి',
    examTabPYQ: 'గత సంవత్సరం ప్రశ్నపత్రాలు',
    examTabSalary: 'జీతం & కెరీర్',
    examTabApply: 'దరఖాస్తు ఎలా చేయాలి',
    lastDateApply: 'దరఖాస్తు చివరి తేదీ',
    examCalendarTitle: 'పరీక్ష క్యాలెండర్',
    examCalendarDesc: 'రాబోయే ప్రభుత్వ పరీక్ష తేదీలు, దరఖాస్తు గడువులు మరియు షెడ్యూల్‌లు',
    searchExamsByName: 'పరీక్ష పేరు వెతకండి...',
    tentativeDatesNote: 'అన్ని తేదీలు తాత్కాలికం మరియు మారవచ్చు. ఎల్లప్పుడూ అధికారిక నోటిఫికేషన్ నుండి ధృవీకరించండి.',
    noExamsFound: 'పరీక్షలు కనుగొనబడలేదు',
    noExamsFoundDesc: 'మీ ఫిల్టర్లకు సరిపోయే పరీక్ష తేదీలు లేవు. వర్గం లేదా శోధన పదాన్ని మార్చండి.',
    lastDateToApply: 'దరఖాస్తు చివరి తేదీ',
    addToGoogleCal: 'Google క్యాలెండర్‌కు జోడించండి',
    downloadICS: 'క్యాలెండర్ ఫైల్ డౌన్‌లోడ్ చేయండి',
    setReminder: 'రిమైండర్ సెట్ చేయండి',
    removeReminder: 'రిమైండర్ తీసివేయండి',
    stayUpdated: 'అప్‌డేట్‌గా ఉండండి',
    studyResources: 'అధ్యయన వనరుల కేంద్రం',
    studyResourcesDesc: 'తయారీ కోసం త్వరిత సూచన నోట్లు మరియు ఎంపిక చేసిన లింకులు',
    searchResources: 'శీర్షిక, పరీక్ష, కీవర్డ్ ద్వారా వెతకండి...',
    currentAffairsDesc: 'తాజా సంఘటనలు మరియు వార్తలతో అప్‌డేట్‌గా ఉండండి',
    dailyDigest: 'రోజువారీ డైజెస్ట్',
    searchCurrentAffairs: 'కరెంట్ అఫైర్స్ వెతకండి...',
    today: 'ఈరోజు',
    thisWeek: 'ఈ వారం',
    thisMonth: 'ఈ నెల',
    downloadDigest: 'వారపు డైజెస్ట్ డౌన్‌లోడ్ చేయండి',
    careerGuideDesc: 'మీ ప్రొఫైల్ ఆధారంగా వ్యక్తిగత కెరీర్ మార్గదర్శకత్వం పొందండి',
    latestResults: 'తాజా ప్రభుత్వ పరీక్ష ఫలితాలు',
    latestResultsDesc: 'అన్ని ప్రధాన పరీక్షల ఫలితాల స్థితి మరియు అధికారిక లింకులు చూడండి',
    howToCheckResult: 'ఫలితం ఎలా చూడాలి',
    checkResult: 'ఫలితం చూడండి',
    admitCards: 'ప్రభుత్వ పరీక్ష అడ్మిట్ కార్డులు',
    admitCardsDesc: 'అడ్మిట్ కార్డ్ విడుదల తేదీలు మరియు డౌన్‌లోడ్ లింకులు ట్రాక్ చేయండి',
    howToDownload: 'ఎలా డౌన్‌లోడ్ చేయాలి',
    examDayChecklist: 'పరీక్ష రోజు చెక్‌లిస్ట్',
    downloadAdmitCard: 'అడ్మిట్ కార్డ్ డౌన్‌లోడ్ చేయండి',
    answerKeysTitle: 'ప్రభుత్వ పరీక్ష ఆన్సర్ కీలు',
    answerKeysDesc: 'ఆన్సర్ కీ విడుదల తేదీలు మరియు అభ్యంతర ప్రక్రియ ట్రాక్ చేయండి',
    cutOffTitle: 'కట్-ఆఫ్ మార్కులు',
    cutOffDesc: 'అన్ని ప్రధాన పరీక్షల గత సంవత్సరం కట్-ఆఫ్ మార్కులు చూడండి',
    officialCutOff: 'అధికారిక కట్-ఆఫ్',
    syllabusMindMaps: 'సిలబస్ మైండ్ మ్యాప్‌లు',
    mindMapsDesc: 'అన్ని ప్రధాన ప్రభుత్వ పరీక్షలకు ఇంటరాక్టివ్ ఫ్లో-చార్ట్‌లు',
    compareExamsTitle: 'ప్రభుత్వ పరీక్షలను పోల్చండి',
    compareExamsDesc: 'అర్హత, జీతం, సిలబస్ మరియు మరిన్ని పోల్చడానికి 2 లేదా 3 పరీక్షలను ఎంచుకోండి',
    selectExamsToCompare: 'పోల్చడానికి పరీక్షలు ఎంచుకోండి',
    popularComparisons: 'ప్రాచుర్యం పొందిన పోలికలు',
    salaryCalcTitle: 'ప్రభుత్వ ఉద్యోగ జీతం కాల్క్యులేటర్',
    selectPost: 'పదవి ఎంచుకోండి',
    cityType: 'నగరం రకం (HRA కోసం)',
    monthlyBreakdown: 'నెలవారీ జీతం వివరాలు',
    basicPay: 'ప్రాథమిక వేతనం',
    dearnessAllowance: 'కరువు భత్యం',
    houseRentAllowance: 'ఇంటి అద్దె భత్యం',
    transportAllowance: 'రవాణా భత్యం (DA తో)',
    grossSalary: 'మొత్తం వేతనం',
    npsDeduction: 'NPS తగ్గింపు (10%)',
    estimatedTax: 'అంచనా పన్ను',
    estimatedTakeHome: 'అంచనా నికర వేతనం',
    annualGrossCTC: 'వార్షిక మొత్తం (CTC)',
    annualTakeHome: 'వార్షిక నికర వేతనం',
    disclaimerTitle: 'నిరాకరణ',
    salaryDisclaimer: 'ఇవి 7వ వేతన సంఘం మరియు అంచనా 8వ వేతన సంఘం ఫిట్‌మెంట్ ఫ్యాక్టర్ 2.57x ఆధారంగా అంచనా సంఖ్యలు. వాస్తవ వేతనం పోస్టింగ్ ప్రదేశం, అదనపు భత్యాలు మరియు వ్యక్తిగత పన్ను స్లాబుల ఆధారంగా మారవచ్చు.',
    prepTimeTitle: 'తయారీ సమయ అంచనాకర్త',
    educationLevel: 'మీ విద్యా స్థాయి',
    hoursAvailable: 'రోజుకు అందుబాటులో ఉన్న గంటలు',
    workingProfessional: 'ఉద్యోగస్తులా?',
    estimateTime: 'తయారీ సమయాన్ని అంచనా వేయండి',
    recommendedTime: 'నెలల కేంద్రీకృత తయారీ సిఫారసు',
    examPriorityTitle: 'పరీక్ష ప్రాధాన్యత మాతృక',
    examPriorityDesc: 'మీరు ఏ ప్రభుత్వ పరీక్షను లక్ష్యంగా పెట్టుకోవాలి?',
    filterByQualification: 'అర్హత ప్రకారం ఫిల్టర్ చేయండి',
    allLevels: 'అన్ని స్థాయిలు',
    communityTitle: 'సామాజిక చర్చా వేదిక',
    communityDesc: 'తోటి అభ్యర్థులతో కనెక్ట్ అవ్వండి, వ్యూహాలు పంచుకోండి మరియు పరీక్షల గురించి చర్చించండి',
    searchDiscussions: 'చర్చలు వెతకండి...',
    askQuestion: 'ప్రశ్న అడగండి',
    discussions: 'చర్చలు',
    prepRoadmapTitle: 'తయారీ రోడ్‌మ్యాప్ జనరేటర్',
    prepRoadmapDesc: 'మీ పరీక్షకు అనుగుణంగా వ్యక్తిగత వారానికి ఒక అధ్యయన ప్రణాళిక పొందండి',
    targetExam: 'లక్ష్య పరీక్ష',
    selectTargetExam: 'మీ లక్ష్య పరీక్ష ఎంచుకోండి',
    monthsAvailable: 'అందుబాటులో ఉన్న నెలలు',
    selectDuration: 'తయారీ వ్యవధి ఎంచుకోండి',
    studyHoursPerDay: 'రోజుకు అధ్యయన గంటలు',
    selectDailyHours: 'రోజువారీ అధ్యయన గంటలు ఎంచుకోండి',
    generateRoadmap: 'రోడ్‌మ్యాప్ రూపొందించండి',
    generateNewRoadmap: 'కొత్త రోడ్‌మ్యాప్ రూపొందించండి',
    downloadPrint: 'డౌన్‌లోడ్ / ప్రింట్',
    topics: 'అంశాలు',
    dailyHours: 'రోజువారీ గంటలు',
    markComplete: 'పూర్తయినట్లు గుర్తించండి',
    completed: 'పూర్తయింది',
    weeksCompleted: 'వారాలు పూర్తయ్యాయి',
    howItWorks: 'ఇది ఎలా పని చేస్తుంది',
    setDuration: 'వ్యవధి సెట్ చేయండి',
    getRoadmap: 'రోడ్‌మ్యాప్ పొందండి',
    supportedExams: 'మద్దతు ఉన్న పరీక్షలు',
    roadmapDisclaimer: 'ఈ రోడ్‌మ్యాప్ మార్గదర్శకంగా రూపొందించబడింది. మీ బలాలు, బలహీనతలు మరియు కోచింగ్ మార్గదర్శకత్వం ఆధారంగా ప్రణాళికను సర్దుబాటు చేయండి.',
    progressSavedLocally: 'ప్రగతి మీ బ్రౌజర్‌లో స్థానికంగా సేవ్ చేయబడింది.',
    closingSoon: 'త్వరలో ముగుస్తోంది',
    browseByCategory: 'వర్గం వారీగా',
    categoryHighlight: 'బ్రౌజ్ చేయండి',
    categoriesSubtext: '16 రంగాలు, 500+ పరీక్షలు — మీ మార్గం కనుగొనండి',
    viewAllCategories: 'అన్ని వర్గాలు చూడండి',
    freeToolsTo: 'విజయానికి ఉచిత',
    succeed: 'సాధనాలు',
    freeToolsDesc: 'ప్రభుత్వ పరీక్ష తయారీకి అవసరమైన అన్నీ',
    govtExamsCovered: 'ప్రభుత్వ పరీక్షలు కవర్ చేయబడ్డాయి',
    dailyCAUpdates: 'రోజువారీ కరెంట్ అఫైర్స్ అప్‌డేట్‌లు',
    freeStudyResources: 'ఉచిత అధ్యయన వనరులు',
    joinCTA: 'GovtExamPath ఉపయోగించి ప్రభుత్వ పరీక్షలు పాస్ చేస్తున్న వేలాది విద్యార్థులతో చేరండి.',
    subscribedMsg: 'సబ్‌స్క్రైబ్ చేశారు! మీ ఇన్‌బాక్స్ చెక్ చేయండి.',
    emailPlaceholder: 'ఇమెయిల్ ద్వారా పరీక్ష అప్‌డేట్‌లు పొందండి',
    share: 'షేర్',
    tags: 'ట్యాగ్‌లు:',
    relatedArticles: 'సంబంధిత వ్యాసాలు',
    relatedExams: 'సంబంధిత పరీక్షలు',
    relatedExamsDesc: 'ఈ వ్యాసానికి సంబంధించిన పరీక్ష పేజీలను అన్వేషించండి',
    updatedDaily: 'రోజువారీ అప్‌డేట్',
    articles: 'వ్యాసాలు',
    todayTopStories: 'పరీక్ష అభ్యర్థుల కోసం ఈ రోజు టాప్ స్టోరీలు',
    topStory: 'టాప్ స్టోరీ',
    trending: 'ట్రెండింగ్',
    newBadge: 'కొత్త',
    importantFor: 'దీనికి ముఖ్యమైనది:',
    readOn: 'చదవండి',
    showingArticles: 'చూపిస్తోంది',
    articleCount: 'వ్యాసం',
    articlesCount: 'వ్యాసాలు',
    inCategory: 'లో',
    forPeriod: 'కోసం',
    noCAFound: 'మీ ఫిల్టర్‌లకు సరిపోయే కరెంట్ అఫైర్స్ కనుగొనబడలేదు.',
    weeklyDigest: 'వారపు డైజెస్ట్',
    cutOffDisclaimer: 'కట్-ఆఫ్ మార్కులు గత సంవత్సరం డేటా ఆధారంగా ఉన్నాయి మరియు మారవచ్చు. తాజా కట్-ఆఫ్‌ల కోసం అధికారిక వెబ్‌సైట్‌లు చూడండి.',
    searchCutOff: 'పరీక్ష పేరు లేదా నిర్వహణ సంస్థ ద్వారా వెతకండి...',
    noExamsMatchSearch: 'మీ శోధనకు సరిపోయే పరీక్షలు కనుగొనబడలేదు.',
    previousYearCutOff: 'గత సంవత్సరం కట్-ఆఫ్ (అంచనా)',
    examsAcrossMonths: 'పరీక్షలు',
    monthsLabel: 'నెలల్లో',
    noUpcomingExams: 'ప్రస్తుతం ప్రదర్శించడానికి రాబోయే పరీక్ష తేదీలు లేవు.',
    searchResultsPlaceholder: 'పరీక్ష పేరు లేదా నిర్వహణ సంస్థ ద్వారా వెతకండి...',
    noExamsMatchResult: 'మీ శోధనకు సరిపోయే పరీక్షలు కనుగొనబడలేదు.',
    admitCardSearchPlaceholder: 'పరీక్ష పేరుతో వెతకండి...',
    replies: 'జవాబులు',
    joinDiscussion: 'చర్చలో చేరండి',
    comingSoon: 'త్వరలో వస్తోంది',
    communityComingSoon: 'కమ్యూనిటీ ఫీచర్లు నిర్మించబడుతున్నాయి. తోటి అభ్యర్థులతో వ్యూహాలు పంచుకోండి.',
    selectExam1: 'పరీక్ష 1 ఎంచుకోండి',
    selectExam2: 'పరీక్ష 2 ఎంచుకోండి',
    noExamsToCompare: 'పరీక్షలు కనుగొనబడలేదు',
    salaryCalcDesc: '7వ మరియు అంచనా 8వ వేతన సంఘం కింద ఏదైనా ప్రభుత్వ పదవికి మీ నెలవారీ జీతం అంచనా వేయండి',
    payCommission8th: '8వ వేతన సంఘం (అంచనా)',
    payCommission7th: '7వ వేతన సంఘం (ప్రస్తుత)',
    payCommission8thExpected: '8వ వేతన సంఘం (అంచనా)',
    fitmentFactor: 'ఫిట్‌మెంట్ ఫ్యాక్టర్ 2.57x — జనవరి 2027 నుండి అంచనా',
    prepTimeDesc: 'మీ లక్ష్య పరీక్ష కోసం ఎంత సమయం తయారీ చేయాలో తెలుసుకోండి',
    graduate: 'గ్రాడ్యుయేట్',
    postGraduate: 'పోస్ట్ గ్రాడ్యుయేట్',
    twelfthPass: '12వ తరగతి పాస్',
    tenthPass: '10వ తరగతి పాస్',
    eligibilityCheckerDesc: 'మీకు అర్హత ఉన్న పరీక్షలను తక్షణమే కనుగొనండి',
    freeResourcesDesc: '60+ అధ్యయన సామగ్రి, పేపర్లు & పుస్తక జాబితాలు',
    aboutThisSection: 'ఈ విభాగం గురించి',
    onSiteNotes: 'ఆన్-సైట్ నోట్స్',
    officialGuidesAndPYQs: 'అధికారిక గైడ్‌లు & PYQలు',
    allTypes: 'అన్ని రకాలు',
    noResourcesFound: 'మీ ఫిల్టర్‌లకు సరిపోయే వనరులు కనుగొనబడలేదు.',
    collapseNotes: 'నోట్స్ మూసివేయండి',
    readNotesHere: 'ఇక్కడ నోట్స్ చదవండి',
    viewOnGovtExamPath: 'GovtExamPath లో చూడండి',
    officialGuideLabel: 'అధికారిక గైడ్',
    prevYearPapers: 'గత సంవత్సరం పేపర్లు',
    bookList: 'పుస్తకాల జాబితా',
    howToUseResources: 'ఈ వనరుల కేంద్రాన్ని ఎలా ఉపయోగించాలి',
    clickToExpand: 'అంశాలను విస్తరించడానికి లేదా కుదించడానికి ఏదైనా నోడ్‌పై క్లిక్ చేయండి',
    howToUseMindMaps: 'సిలబస్ మైండ్ మ్యాప్‌లను ఎలా ఉపయోగించాలి',
    joinAspirants: '10,000+ అభ్యర్థులతో చేరండి',
    discussionCategories: 'చర్చా విభాగాలు',
    popularDiscussions: 'జనాదరణ పొందిన చర్చలు',
    showAll: 'అన్నీ చూపించు',
    noDiscussionsFound: 'చర్చలు కనుగొనబడలేదు',
    tryDifferentFilter: 'వేరే విభాగం లేదా శోధన పదం ప్రయత్నించండి.',
    pinned: 'పిన్ చేయబడింది',
    yourPost: 'మీ పోస్ట్',
    reply: 'సమాధానం',
    joinOurCommunities: 'మా సమాజాల్లో చేరండి',
    members: 'సభ్యులు',
    joinNow: 'ఇప్పుడే చేరండి',
    shareYourDoubt: 'మీ సందేహాన్ని సమాజంతో పంచుకోండి',
    yourQuestion: 'మీ ప్రశ్న',
    questionPlaceholder: 'మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...',
    postsSavedLocally: 'పోస్ట్‌లు స్థానికంగా సేవ్ చేయబడ్డాయి. కమ్యూనిటీ బ్యాకెండ్ త్వరలో!',
    postQuestion: 'ప్రశ్న పోస్ట్ చేయండి',
    startExamPrep: 'ఈరోజే మీ పరీక్ష తయారీ ప్రారంభించండి',
    startExamPrepDesc: 'మీ ప్రొఫైల్‌కు సరిపోయే పరీక్షలను కనుగొనడానికి మా ఉచిత టూల్స్ ఉపయోగించండి.',
    showLess: 'తక్కువ చూపించు',
    pdfDialogOpened: 'PDF ప్రింట్ డైలాగ్ తెరిచింది. డౌన్‌లోడ్ కోసం "PDF గా సేవ్" ఎంచుకోండి.',
    popupBlocked: 'పాప్-అప్ బ్లాక్ చేయబడింది. దయచేసి పాప్-అప్‌లను అనుమతించి మళ్ళీ ప్రయత్నించండి.',
    downloadFailed: 'డౌన్‌లోడ్ విఫలమైంది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    todaysTopStories: 'పరీక్ష అభ్యర్థుల కోసం నేటి ముఖ్య కథనాలు',
    smartExamSelection: 'స్మార్ట్ పరీక్ష ఎంపిక',
    examsCompared: 'పరీక్షలు పోల్చబడ్డాయి',
    priorityQuadrants: 'ప్రాధాన్యత చతుర్భుజాలు',
    hiddenGems: 'దాగి ఉన్న రత్నాలు',
    eyeOpener: 'కళ్ళు తెరిపించే విషయం: సంఖ్యలు అబద్ధం చెప్పవు',
    whatMostChoose: 'చాలా మంది ఏమి ఎంచుకుంటారు',
    competitionRatio: 'పోటీ నిష్పత్తి',
    insteadTry: 'బదులుగా ప్రయత్నించండి',
    whatSmartChoose: 'తెలివైన అభ్యర్థులు ఏమి ఎంచుకుంటారు',
    vacancies: 'ఖాళీలు',
    applicants: 'దరఖాస్తుదారులు',
    competition: 'పోటీ',
    startingSalary: 'ప్రారంభ జీతం',
    prepTimeLabel: 'తయారీ సమయం',
    whySkipped: 'చాలా మంది అభ్యర్థులు ఈ పరీక్షను ఎందుకు వదిలేస్తారు',
    realityCheck: 'వాస్తవ పరీక్ష',
    keyAdvantages: 'ప్రధాన ప్రయోజనాలు',
    ourTake: 'మా అభిప్రాయం',
    checkEligibilityBtn: 'అర్హత తనిఖీ',
    estimatePrepTime: 'తయారీ సమయం అంచనా',
    viewFullDetails: 'పూర్తి వివరాలు చూడండి',
    noExamsMatch: 'ఈ అర్హత స్థాయికి సరిపోయే పరీక్షలు లేవు',
    competitionLandscape: 'పోటీ ల్యాండ్‌స్కేప్',
    competitionLandscapeDesc: 'ప్రధాన పరీక్షల కోసం దరఖాస్తుదారుల-ప్రతి-సీటు నిష్పత్తి',
    bestSalaryRatio: 'ఉత్తమ జీతం-పోటీ నిష్పత్తి',
    bestSalaryRatioDesc: 'తక్కువ పోటీలో అత్యధిక జీతం పొందే పరీక్షలు',
    selectExamLabel: 'పరీక్ష ఎంచుకోండి',
    searchExamsPlaceholder: 'పేరు లేదా విభాగం ద్వారా పరీక్షలు వెతకండి...',
    examCategoryLabel: 'పరీక్ష విభాగం',
    relevantBackground: 'సంబంధిత నేపథ్యం',
    selectYourBackground: 'మీ నేపథ్యాన్ని ఎంచుకోండి',
    selectEducationLevel: 'విద్యా స్థాయి ఎంచుకోండి',
    estimatedTimeline: 'మీ ప్రొఫైల్ ఆధారంగా అంచనా తయారీ సమయరేఖ',
    focusedPrep: 'కేంద్రీకృత తయారీ సిఫార్సు',
    confidenceLabel: 'విశ్వాసం',
    prepTimeline: 'తయారీ సమయరేఖ',
    tipsFor: 'కోసం చిట్కాలు',
    examsLabel: 'పరీక్షలు',
    startPreparing: 'తయారీ ప్రారంభించండి',
    avgPrepTime: 'సగటు తయారీ సమయం',
    popularExams: 'జనాదరణ పొందిన పరీక్షలు',
    prepDisclaimer: 'ఈ అంచనాలు సూచనాత్మకం మరియు సాధారణ తయారీ నమూనాల ఆధారంగా ఉన్నాయి.',
    noExamsFoundDropdown: 'పరీక్షలు కనుగొనబడలేదు',
    // EligibilityChecker extras
    eligTitle: 'అర్హత',
    eligTitleHighlight: 'తనిఖీ',
    eligOutOf: 'మొత్తం',
    eligExamsChecked: 'ప్రభుత్వ పరీక్షల తనిఖీలో, మీరు అర్హులు',
    eligExamsLabel: 'పరీక్షలకు',
    eligAgeLabel: 'వయసు',
    eligQualLabel: 'అర్హత',
    eligAttemptsLabel: 'ప్రయత్నాలు',
    eligNationalityLabel: 'జాతీయత',
    eligRelaxationLabel: 'సడలింపు',
    eligPhysicalLabel: 'శారీరక',
    eligUnderstandingTitle: 'ప్రభుత్వ పరీక్షల అర్హత ప్రమాణాలను అర్థం చేసుకోండి',
    eligAgeLimitsTitle: 'ప్రధాన పరీక్షల్లో వయసు పరిమితులు',
    eligExamSector: 'పరీక్ష రంగం',
    eligRepExam: 'ప్రతినిధి పరీక్ష',
    eligMinAge: 'కనిష్ట వయసు',
    eligMaxAgeGen: 'గరిష్ట వయసు (సాధారణ)',
    eligKeyNotes: 'కీలక గమనికలు',
    eligEduQualTitle: 'విద్యార్హత అవసరాలు',
    eligAgeRelaxTitle: 'వయసు సడలింపు నియమాలు',
    eligMythsTitle: 'అర్హత గురించి సాధారణ అపోహలు',
    // PrepRoadmap extras
    phaseTipFoundation: 'ఇప్పుడు బలమైన పునాదిని నిర్మించండి — ఇవి ప్రతి దశలో లాభాలను ఇస్తాయి. భావనలను అర్థం చేసుకోవడంపై దృష్టి పెట్టండి.',
    phaseTipAdvanced: 'మీకు బేసిక్స్ ఉన్నాయి — ఇప్పుడు లోతుగా వెళ్ళండి. విషయాలను అనుసంధానం చేయండి మరియు అనువర్తన-స్థాయి ప్రశ్నలు ప్రాక్టీస్ చేయండి.',
    phaseTipRevision: 'ప్రతిదీ క్రమబద్ధంగా సమీక్షించండి. బలహీన ప్రాంతాలను గుర్తించడానికి గత సంవత్సర పేపర్లను ఉపయోగించండి.',
    phaseTipSprint: 'మీ తయారీపై నమ్మకం ఉంచండి. సమయ నిర్వహణపై దృష్టి పెట్టండి, ప్రశాంతంగా ఉండండి.',
    monthLabel: 'నెల',
    hoursLabel: 'గంటలు',
    printBtn: 'ప్రింట్',
    downloadPdfBtn: 'PDF డౌన్‌లోడ్',
    weeksLabel: 'వారాలు',
    weekLabel: 'వారం',
    doneLabel: 'పూర్తి',
    ofTotalTime: 'మొత్తం సమయంలో',
    milestoneLabel: 'మైలురాయి',
    resourcesLabel: 'వనరులు',
    selectExamDesc: '13+ ప్రభుత్వ పరీక్షల నుండి వివరమైన సిలబస్ డేటాతో ఎంచుకోండి',
    setDurationDesc: '1 నుండి 24 నెలల వరకు మీ అందుబాటులో ఉన్న తయారీ సమయాన్ని ఎంచుకోండి',
    dailyHoursDesc: 'మీరు రోజుకు ఎన్ని గంటలు కేటాయించగలరో చెప్పండి',
    getRoadmapDesc: 'టాపిక్‌లు, వనరులు & ట్రాకింగ్‌తో వారవారీ ప్లాన్ పొందండి',
    // AIGuide extras
    enterYourAge: 'మీ వయసు నమోదు చేయండి...',
    typeYourMessage: 'మీ సందేశాన్ని టైప్ చేయండి...',
    eligCheckerLink: 'అర్హత తనిఖీ',
    checkEligibilityLink: 'పరీక్ష అర్హత తనిఖీ చేయండి',
    mindMapsLink: 'మైండ్ మ్యాప్‌లు',
    exploreSyllabiLink: 'పరీక్ష సిలబస్ చూడండి',
    resourcesLink: 'వనరులు',
    studyMaterialsLink: 'అధ్యయన సామగ్రి',
    // Profile page
    profileTitle: 'నా ప్రొఫైల్',
    profileFullName: 'పూర్తి పేరు',
    profileEditProfile: 'ప్రొఫైల్ సవరించండి',
    profileSaveChanges: 'మార్పులు సేవ్ చేయండి',
    profileCancel: 'రద్దు చేయండి',
    contactEmailAddress: 'ఇమెయిల్ చిరునామా',
    // ForgotPassword
    forgotPwdTitle: 'పాస్‌వర్డ్ మర్చిపోయారా',
    forgotPwdSubtitle: 'మీ ఇమెయిల్ నమోదు చేయండి, మేము మీకు రీసెట్ లింక్ పంపుతాము',
    // EligibilityChecker form
    eligCheckerDesc: 'మీ వయసు, విద్య మరియు వర్గం ఆధారంగా మీరు ఏ ప్రభుత్వ పరీక్షలకు అర్హులో తనిఖీ చేయండి',
    eligYourAge: 'మీ వయసు',
    eligEnterAge: 'మీ వయసు నమోదు చేయండి (14-60)',
    eligHighestQual: 'అత్యధిక అర్హత',
    eligSelectQual: 'అర్హత ఎంచుకోండి',
    eligQual10: '10వ తరగతి పాస్',
    eligQual12: '12వ తరగతి పాస్',
    eligQualDiploma: 'డిప్లొమా',
    eligQualGrad: 'గ్రాడ్యుయేషన్',
    eligQualPG: 'పోస్ట్ గ్రాడ్యుయేషన్',
    eligCatLabel: 'వర్గం',
    eligCatGeneral: 'జనరల్',
    eligCatEWS: 'EWS (ఆర్థికంగా బలహీన వర్గం)',
    eligCatOBC: 'OBC (నాన్-క్రీమీ లేయర్)',
    eligCatSC: 'SC (షెడ్యూల్డ్ కాస్ట్)',
    eligCatST: 'ST (షెడ్యూల్డ్ ట్రైబ్)',
    eligCheckBtn: 'నా అర్హత తనిఖీ చేయండి',
    eligResultsFor: 'వయసు కోసం ఫలితాలు',
    eligEligibleLabel: 'అర్హులు',
    eligAlmostLabel: 'దాదాపు అర్హులు',
    eligNotEligibleLabel: 'అనర్హులు',
    eligShowAllBtn: 'అన్నీ చూపించు',
    eligShowLess: 'తక్కువ చూపించు',
    eligNotEligibleExams: 'అనర్హ పరీక్షలు',
    eligGetRecommend: 'వ్యక్తిగత పరీక్ష సిఫార్సులు పొందండి',
  },
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('lang', language);
  }, [language]);

  const toggleLanguage = useCallback(() => {
    const languages = ['en', 'hi', 'te'];
    setLanguage((prev) => {
      const idx = languages.indexOf(prev);
      return languages[(idx + 1) % languages.length];
    });
  }, []);

  const t = useCallback((key) => {
    const dict = translations[language] || translations.en;
    return dict[key] || translations.en[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
