import React from 'react';
import SEO from '../components/common/SEO';

const Disclaimer = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <SEO title="Disclaimer" path="/disclaimer" description="GovtExamPath disclaimer. Important information about the accuracy of exam data, AI recommendations, and content on our platform." />

      <h1 className="text-3xl font-extrabold text-gray-900 dark:text-gray-100 mb-8">
        <span className="gradient-text">Disclaimer</span>
      </h1>

      <div className="prose prose-lg dark:prose-invert max-w-none">
        <p className="text-gray-500"><strong>Last updated:</strong> April 24, 2026</p>
        <p>The information provided on GovtExamPath (<strong>govtexampath.com</strong>) is for general informational and educational purposes only. Please read this disclaimer carefully before using our platform.</p>

        <h2>1. General Information Disclaimer</h2>
        <p>GovtExamPath is an independent educational platform that provides information about Indian government examinations. We are <strong>not affiliated with, endorsed by, or officially connected to</strong> any government body, public service commission, recruitment board, or exam conducting organization including but not limited to:</p>
        <ul>
          <li>Union Public Service Commission (UPSC)</li>
          <li>Staff Selection Commission (SSC)</li>
          <li>Institute of Banking Personnel Selection (IBPS)</li>
          <li>Reserve Bank of India (RBI)</li>
          <li>Railway Recruitment Boards (RRBs)</li>
          <li>State Public Service Commissions (PSCs)</li>
          <li>Securities and Exchange Board of India (SEBI)</li>
          <li>National Testing Agency (NTA)</li>
          <li>Any other government or semi-government recruitment organization</li>
        </ul>
        <p>All logos, trademarks, and organization names mentioned on this platform belong to their respective owners.</p>

        <h2>2. Exam Information Accuracy</h2>
        <p>We make every effort to ensure the accuracy and timeliness of exam information displayed on our platform, including eligibility criteria, age limits, application fees, important dates, syllabus, exam patterns, and vacancy details. However:</p>
        <ul>
          <li>Exam conducting bodies may change rules, criteria, dates, or other details at any time without prior notice.</li>
          <li>There may be a delay between official updates and our platform updates.</li>
          <li>Information on our platform may contain inadvertent errors or omissions.</li>
          <li><strong>We strongly recommend that users always refer to the official notification and website of the respective exam conducting body for the most current and authoritative information before submitting applications or making decisions.</strong></li>
        </ul>
        <p>GovtExamPath shall not be held responsible for any loss, damage, or inconvenience caused by reliance on information provided on this platform.</p>

        <h2>3. AI Career Guide Disclaimer</h2>
        <p>Our AI-powered Career Guide provides personalized exam recommendations based on the information you provide (age, education, preferences, etc.). Please understand that:</p>
        <ul>
          <li>AI recommendations are generated by algorithms and are <strong>suggestions only</strong>, not professional career counseling or advice.</li>
          <li>The AI system may not account for all individual circumstances, recent policy changes, or specific state-level variations.</li>
          <li>Recommendations should be used as a starting point for your own research, not as a definitive career plan.</li>
          <li>We do not guarantee that pursuing any recommended exam will result in selection or employment.</li>
          <li>For comprehensive career guidance, we recommend consulting qualified career counselors and official exam authorities.</li>
        </ul>

        <h2>4. Eligibility Checker Disclaimer</h2>
        <p>Our Eligibility Checker tool provides <strong>indicative results</strong> based on the general eligibility criteria in our database matched against the information you provide. Important caveats:</p>
        <ul>
          <li>Results are approximate and should not be considered as official eligibility confirmation.</li>
          <li>Eligibility criteria can vary by specific post, department, and year of examination.</li>
          <li>Reservation category relaxations (age, fee, attempts) are applied based on general government norms and may differ for specific exams.</li>
          <li>Official eligibility is determined solely by the respective exam conducting body during the application review process.</li>
          <li>Always check the official notification for the exact eligibility requirements before applying.</li>
        </ul>

        <h2>5. Study Resources and External Links</h2>
        <p>GovtExamPath provides curated links to free study materials, previous year question papers, book recommendations, and external educational resources. Regarding these resources:</p>
        <ul>
          <li>We do not host or own most external study materials; we link to officially available or widely recognized free resources.</li>
          <li>External websites have their own terms of service and privacy policies that are beyond our control.</li>
          <li>We do not guarantee the availability, accuracy, or quality of content on external websites.</li>
          <li>Links are provided for convenience and do not imply endorsement of the linked site or its content.</li>
          <li>If you find any broken link or inappropriate content, please report it to us.</li>
        </ul>

        <h2>6. Blog and Article Content</h2>
        <p>Articles, preparation strategies, study timetables, book recommendations, exam comparisons, and tips published on our blog are:</p>
        <ul>
          <li>Based on general best practices, publicly available topper strategies, and educational research.</li>
          <li>Written for educational and informational purposes only.</li>
          <li>Not guaranteed to produce specific results in any examination.</li>
          <li>General in nature and may need to be adapted to your individual learning style, available time, and current preparation level.</li>
        </ul>
        <p>Every aspirant's journey is different. What works for one candidate may not work for another. Use our content as guidance while developing your own personalized preparation strategy.</p>

        <h2>7. No Professional Advice</h2>
        <p>Nothing on GovtExamPath constitutes:</p>
        <ul>
          <li>Professional career counseling or advice</li>
          <li>Legal advice regarding government employment regulations</li>
          <li>Financial advice regarding exam fees, coaching investments, or career earnings</li>
          <li>Medical advice regarding fitness criteria for specific posts (e.g., Defence, Police)</li>
        </ul>
        <p>For professional advice in these areas, please consult qualified professionals.</p>

        <h2>8. No Guarantee of Results</h2>
        <p>GovtExamPath provides tools and information to assist in your preparation journey. However, we do not guarantee:</p>
        <ul>
          <li>Selection in any government examination</li>
          <li>Achievement of specific scores or ranks</li>
          <li>Employment in any government position</li>
          <li>That our preparation strategies will be effective for every individual</li>
        </ul>
        <p>Success in government examinations depends on numerous factors including individual effort, preparation quality, competition level, and official selection criteria.</p>

        <h2>9. Advertising Disclaimer</h2>
        <p>GovtExamPath may display advertisements served by third-party advertising networks, including Google AdSense. These advertisements help us maintain and improve our free platform. Please note:</p>
        <ul>
          <li>Advertisements are served by third-party networks and their content is not controlled, reviewed, or endorsed by GovtExamPath.</li>
          <li>We are not responsible for the accuracy, content, or practices of advertisers.</li>
          <li>Clicking on advertisements and any subsequent transactions are entirely at your own risk and discretion.</li>
          <li>Third-party advertisers may use cookies and tracking technologies subject to their own privacy policies.</li>
          <li>The presence of an advertisement on our platform does not constitute a recommendation or endorsement of the advertised product or service.</li>
        </ul>

        <h2>10. User-Generated Content</h2>
        <p>If users submit any content through our platform (such as comments, queries through the contact form, or feedback), they grant GovtExamPath a non-exclusive, royalty-free right to use, display, and distribute that content. Users are solely responsible for the content they submit and must ensure it does not violate any laws or third-party rights.</p>

        <h2>11. Limitation of Liability</h2>
        <p>To the maximum extent permitted by applicable Indian law, GovtExamPath, its founders, team members, contributors, and affiliates shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages, including but not limited to:</p>
        <ul>
          <li>Loss arising from missed application deadlines based on dates displayed on our platform</li>
          <li>Incorrect eligibility assessment leading to wasted application fees</li>
          <li>Reliance on outdated exam information</li>
          <li>Any decision made based on AI recommendations or eligibility checker results</li>
          <li>Technical errors, server downtime, or data loss</li>
          <li>Actions taken based on blog articles or preparation advice</li>
        </ul>

        <h2>12. Changes to This Disclaimer</h2>
        <p>We reserve the right to update or modify this Disclaimer at any time without prior notice. Changes will be posted on this page with an updated revision date. Your continued use of GovtExamPath after any changes constitutes acceptance of the updated Disclaimer.</p>

        <h2>13. Contact Us</h2>
        <p>If you have any questions or concerns about this Disclaimer, please contact us at:</p>
        <ul>
          <li>Email: <a href="mailto:govtexampath@gmail.com">govtexampath@gmail.com</a></li>
          <li>Address: New Delhi, India</li>
        </ul>
        <p>By using GovtExamPath, you acknowledge that you have read and understood this Disclaimer.</p>
      </div>
    </div>
  );
};

export default Disclaimer;
