const mongoose = require('mongoose');
const Exam = require('../models/Exam');
const User = require('../models/User');

const examsSeedData = [
  {
    title: 'SSC CGL 2026',
    category: 'SSC',
    conductingBody: 'Staff Selection Commission',
    description: 'Combined Graduate Level Examination for recruitment to Group B and Group C posts in central government ministries and departments.',
    eligibility: "Bachelor's Degree from a recognized University",
    qualifications: "Bachelor's Degree from a recognized University",
    lastDate: '2026-07-30',
    salary: '₹25,500 - ₹1,51,100',
    ageLimit: '18-32 years',
    applicationFee: 'General/OBC: ₹100, SC/ST/Female/PwD: Nil',
    vacancies: '15,000+',
    attempts: 'No limit (within age)',
    officialWebsite: 'https://ssc.nic.in',
    applicationLink: 'https://ssc.nic.in',
    importantDates: [
      { event: 'Application Start Date', date: '2026-07-01' },
      { event: 'Application End Date', date: '2026-07-30' },
      { event: 'Tier-I Exam Date', date: '2026-10-15' },
    ],
    syllabus: 'Tier-I: General Intelligence & Reasoning, General Awareness, Quantitative Aptitude, English. Tier-II: Math, Reasoning, English, GK, Computer Knowledge. Tier-III: Descriptive Paper.',
    examPattern: 'Tier-I: 100 questions, 200 marks, 60 min. Tier-II: 390 marks, 2.5 hours. Tier-III: Descriptive, 100 marks.',
    selectionProcess: 'Tier-I → Tier-II → Tier-III → Document Verification → Final Selection',
    jobRole: 'Income Tax Inspector, Assistant Audit Officer, Sub-Inspector CBI, Assistant Section Officer, Tax Assistant',
    careerGrowth: 'Can rise to Commissioner/Director level through promotions.',
    applicationProcess: '1. Visit ssc.nic.in 2. Register and fill form 3. Upload documents 4. Pay fee 5. Submit',
    salaryRange: { min: 25500, max: 151100, description: 'Pay Level 4 to Pay Level 7 (7th CPC)' },
    perks: 'DA, HRA, Transport Allowance, Medical Benefits, Pension, LTC',
    ageLimitDetails: { min: 18, max: 32, relaxation: 'OBC: 3 years, SC/ST: 5 years, PwD: 10 years' },
    posts: ['Income Tax Inspector', 'Assistant Audit Officer', 'Sub-Inspector CBI', 'Assistant Section Officer', 'Tax Assistant'],
  },
  {
    title: 'SSC CHSL 2026',
    category: 'SSC',
    conductingBody: 'Staff Selection Commission',
    description: 'Combined Higher Secondary Level exam for LDC, JSA, Postal Assistant, Sorting Assistant, and DEO posts.',
    eligibility: '12th Standard pass from a recognized Board',
    qualifications: '12th Standard (Higher Secondary) pass',
    lastDate: '2026-05-31',
    salary: '₹19,900 - ₹81,100',
    ageLimit: '18-27 years',
    applicationFee: 'General/OBC: ₹100, SC/ST/Female/PwD: Nil',
    vacancies: '5,000+',
    attempts: 'No limit (within age)',
    officialWebsite: 'https://ssc.nic.in',
    applicationLink: 'https://ssc.nic.in',
    importantDates: [
      { event: 'Application End Date', date: '2026-05-31' },
      { event: 'Exam Date', date: '2026-09-15' },
    ],
    syllabus: 'Tier-I: General Intelligence, English Language, Quantitative Aptitude, General Awareness. Tier-II: Math, Reasoning, English, GK + Typing/Data Entry.',
    examPattern: 'Tier-I: 100 questions, 200 marks, 60 min. Tier-II: 120 questions, 360 marks, 2 hours + Skill Test.',
    selectionProcess: 'Tier-I → Tier-II + Skill Test → Document Verification',
    jobRole: 'Lower Division Clerk, Postal Assistant, Sorting Assistant, Data Entry Operator',
    salaryRange: { min: 19900, max: 81100, description: 'Pay Level 2 to Pay Level 5' },
    ageLimitDetails: { min: 18, max: 27, relaxation: 'OBC: 3 years, SC/ST: 5 years, PwD: 10 years' },
    posts: ['LDC', 'JSA', 'Postal Assistant', 'Sorting Assistant', 'DEO'],
  },
  {
    title: 'SSC MTS 2026',
    category: 'SSC',
    conductingBody: 'Staff Selection Commission',
    description: 'Multi Tasking Staff exam for Group C non-technical posts in various central government departments.',
    eligibility: '10th pass from a recognized Board',
    lastDate: '2026-07-15',
    salary: '₹18,000 - ₹56,900',
    ageLimit: '18-25 years',
    vacancies: '8,000+',
    officialWebsite: 'https://ssc.nic.in',
    applicationLink: 'https://ssc.nic.in',
    importantDates: [
      { event: 'Application End Date', date: '2026-05-10' },
      { event: 'Exam Date', date: '2026-06-25' },
    ],
    selectionProcess: 'CBT Session-I → Session-II (Descriptive) → Document Verification',
    jobRole: 'Peon, Daftary, Jamadar, Chowkidar in government offices',
    salaryRange: { min: 18000, max: 56900, description: 'Pay Level 1 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 25, relaxation: 'OBC: 3 years, SC/ST: 5 years, PwD: 10 years' },
  },
  {
    title: 'SSC GD Constable 2026',
    category: 'SSC',
    conductingBody: 'Staff Selection Commission',
    description: 'GD Constable recruitment for BSF, CISF, CRPF, SSB, ITBP, AR, NIA, and SSF.',
    eligibility: '10th pass from a recognized Board',
    lastDate: '2026-08-15',
    salary: '₹21,700 - ₹69,100',
    ageLimit: '18-23 years',
    vacancies: '25,000+',
    officialWebsite: 'https://ssc.nic.in',
    importantDates: [
      { event: 'Application End Date', date: '2026-08-15' },
      { event: 'CBT Date', date: '2026-11-01' },
    ],
    selectionProcess: 'CBT → PET/PST → Medical → Document Verification',
    jobRole: 'Constable (GD) in BSF, CISF, CRPF, SSB, ITBP, AR, NIA, SSF',
    salaryRange: { min: 21700, max: 69100, description: 'Pay Level 3 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 23, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'SSC JE 2026',
    category: 'SSC',
    conductingBody: 'Staff Selection Commission',
    description: 'Junior Engineer exam for Civil, Mechanical, Electrical, and Quantity Surveying posts.',
    eligibility: 'Diploma/B.E./B.Tech in relevant engineering discipline',
    lastDate: '2026-09-30',
    salary: '₹35,400 - ₹1,12,400',
    ageLimit: '18-32 years',
    vacancies: '1,000+',
    officialWebsite: 'https://ssc.nic.in',
    selectionProcess: 'Paper-I (CBT) → Paper-II (CBT) → Document Verification',
    jobRole: 'Junior Engineer in CPWD, CWC, BRO, MES and other govt departments',
    salaryRange: { min: 35400, max: 112400, description: 'Pay Level 6 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 32, relaxation: 'OBC: 3 years, SC/ST: 5 years, PwD: 10 years' },
  },
  {
    title: 'SSC Stenographer Grade C & D 2026',
    category: 'SSC',
    conductingBody: 'Staff Selection Commission',
    description: 'Stenographer Grade C and D exam for central government ministries and departments.',
    eligibility: '12th Standard pass + Stenography skills',
    lastDate: '2026-08-30',
    salary: '₹25,500 - ₹81,100',
    ageLimit: '18-30 years',
    officialWebsite: 'https://ssc.nic.in',
    selectionProcess: 'CBT → Skill Test (Stenography) → Document Verification',
    salaryRange: { min: 25500, max: 81100, description: 'Pay Level 4 (Grade D) / Pay Level 5 (Grade C)' },
    ageLimitDetails: { min: 18, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // UPSC
  {
    title: 'UPSC Civil Services 2026',
    category: 'UPSC',
    conductingBody: 'Union Public Service Commission',
    description: 'Civil Services Examination (IAS/IPS/IFS) for recruitment to All India Services and Central Services Group A and B.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-03-15',
    salary: '₹56,100 - ₹2,50,000',
    ageLimit: '21-32 years',
    vacancies: '1,000+',
    officialWebsite: 'https://upsc.gov.in',
    applicationLink: 'https://upsconline.nic.in',
    importantDates: [
      { event: 'Prelims Exam Date', date: '2026-06-01' },
      { event: 'Mains Exam Date', date: '2026-09-20' },
    ],
    selectionProcess: 'Prelims (Objective) → Mains (Descriptive) → Interview/Personality Test',
    jobRole: 'IAS, IPS, IFS, IRS and other Group A & B services',
    salaryRange: { min: 56100, max: 250000, description: 'Pay Level 10 to Pay Level 17 (7th CPC)' },
    ageLimitDetails: { min: 21, max: 32, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
    posts: ['IAS', 'IPS', 'IFS', 'IRS', 'IRAS', 'IAAS', 'IRTS'],
  },
  {
    title: 'UPSC NDA 2026',
    category: 'UPSC',
    conductingBody: 'Union Public Service Commission',
    description: 'National Defence Academy exam for admission to Army, Navy and Air Force wings of NDA and Naval Academy.',
    eligibility: '12th pass (Physics & Maths for Air Force/Navy, any stream for Army)',
    lastDate: '2026-04-20',
    salary: '₹56,100 - ₹1,77,500',
    ageLimit: '16.5-19.5 years',
    vacancies: '400+',
    officialWebsite: 'https://upsc.gov.in',
    selectionProcess: 'Written Exam → SSB Interview (5 days) → Medical',
    jobRole: 'Officer in Indian Army/Navy/Air Force',
    salaryRange: { min: 56100, max: 177500, description: 'Pay Level 10 onwards' },
    ageLimitDetails: { min: 16, max: 19, relaxation: 'As per notification' },
  },
  {
    title: 'UPSC CDS 2026',
    category: 'UPSC',
    conductingBody: 'Union Public Service Commission',
    description: 'Combined Defence Services exam for IMA, INA, AFA and OTA recruitment.',
    eligibility: "Bachelor's Degree (Engineering for some entries)",
    lastDate: '2026-05-15',
    salary: '₹56,100 - ₹1,77,500',
    ageLimit: '19-25 years',
    officialWebsite: 'https://upsc.gov.in',
    selectionProcess: 'Written Exam → SSB Interview → Medical',
    jobRole: 'Officer in Indian Army/Navy/Air Force',
    salaryRange: { min: 56100, max: 177500, description: 'Pay Level 10 onwards' },
    ageLimitDetails: { min: 19, max: 25, relaxation: 'As per notification' },
  },
  {
    title: 'UPSC CAPF 2026',
    category: 'UPSC',
    conductingBody: 'Union Public Service Commission',
    description: 'Central Armed Police Forces exam for Assistant Commandant in BSF, CRPF, CISF, ITBP, SSB.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-06-10',
    salary: '₹56,100 - ₹1,77,500',
    ageLimit: '20-25 years',
    officialWebsite: 'https://upsc.gov.in',
    selectionProcess: 'Written → Physical/Medical → Interview',
    jobRole: 'Assistant Commandant in CAPF',
    salaryRange: { min: 56100, max: 177500, description: 'Pay Level 10' },
    ageLimitDetails: { min: 20, max: 25, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'UPSC EPFO 2026',
    category: 'UPSC',
    conductingBody: 'Union Public Service Commission',
    description: 'Enforcement Officer/Accounts Officer recruitment for EPFO.',
    eligibility: "Bachelor's Degree with knowledge of labour laws",
    lastDate: '2026-07-20',
    salary: '₹47,600 - ₹1,51,100',
    ageLimit: '21-30 years',
    officialWebsite: 'https://upsc.gov.in',
    selectionProcess: 'Written Exam → Interview',
    jobRole: 'Enforcement Officer / Accounts Officer in EPFO',
    salaryRange: { min: 47600, max: 151100, description: 'Pay Level 8 (7th CPC)' },
    ageLimitDetails: { min: 21, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Banking
  {
    title: 'IBPS PO 2026',
    category: 'Banking',
    conductingBody: 'IBPS',
    description: 'Probationary Officer/Management Trainee exam for 11 participating public sector banks.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-08-20',
    salary: '₹36,000 - ₹63,840 (starting)',
    ageLimit: '20-30 years',
    vacancies: '4,000+',
    officialWebsite: 'https://www.ibps.in',
    applicationLink: 'https://www.ibps.in',
    importantDates: [
      { event: 'Application End Date', date: '2026-08-20' },
      { event: 'Prelims Date', date: '2026-10-10' },
      { event: 'Mains Date', date: '2026-11-20' },
    ],
    selectionProcess: 'Prelims → Mains → Interview → Provisional Allotment',
    jobRole: 'Probationary Officer/Management Trainee in Public Sector Banks',
    salaryRange: { min: 36000, max: 63840, description: 'Basic pay ₹36,000 + DA, HRA' },
    ageLimitDetails: { min: 20, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'IBPS Clerk 2026',
    category: 'Banking',
    conductingBody: 'IBPS',
    description: 'Clerical cadre recruitment exam for 11 participating public sector banks.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-07-15',
    salary: '₹19,900 - ₹47,920',
    ageLimit: '20-28 years',
    vacancies: '6,000+',
    officialWebsite: 'https://www.ibps.in',
    selectionProcess: 'Prelims → Mains → Provisional Allotment',
    jobRole: 'Clerk/Cashier in Public Sector Banks',
    salaryRange: { min: 19900, max: 47920, description: 'Basic pay ₹19,900 + allowances' },
    ageLimitDetails: { min: 20, max: 28, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'IBPS SO 2026',
    category: 'Banking',
    conductingBody: 'IBPS',
    description: 'Specialist Officer recruitment for IT Officer, Agricultural Field Officer, HR, Law, Marketing Officer in banks.',
    eligibility: "Bachelor's/Master's Degree in relevant specialization",
    lastDate: '2026-11-15',
    salary: '₹36,000 - ₹63,840',
    ageLimit: '20-30 years',
    officialWebsite: 'https://www.ibps.in',
    selectionProcess: 'Prelims → Mains → Interview',
    jobRole: 'IT Officer, Agricultural Field Officer, HR/Personnel Officer, Marketing Officer',
    salaryRange: { min: 36000, max: 63840, description: 'Scale I Officer Pay' },
    ageLimitDetails: { min: 20, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'SBI PO 2026',
    category: 'Banking',
    conductingBody: 'State Bank of India',
    description: 'Probationary Officer recruitment for State Bank of India.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-04-30',
    salary: '₹41,960 - ₹63,840 (starting)',
    ageLimit: '21-30 years',
    vacancies: '2,000+',
    officialWebsite: 'https://www.sbi.co.in/web/careers',
    selectionProcess: 'Prelims → Mains → Interview/GE/PI',
    jobRole: 'Probationary Officer in SBI',
    salaryRange: { min: 41960, max: 63840, description: 'Basic + DA + City Allowance' },
    ageLimitDetails: { min: 21, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'SBI Clerk 2026',
    category: 'Banking',
    conductingBody: 'State Bank of India',
    description: 'Junior Associate (Customer Support & Sales) recruitment for SBI.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-02-28',
    salary: '₹22,405 - ₹45,000',
    ageLimit: '20-28 years',
    vacancies: '8,000+',
    officialWebsite: 'https://www.sbi.co.in/web/careers',
    selectionProcess: 'Prelims → Mains → Local Language Test',
    jobRole: 'Junior Associate (Clerk) in SBI',
    salaryRange: { min: 22405, max: 45000, description: 'Basic + Special Allowance' },
    ageLimitDetails: { min: 20, max: 28, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'RBI Grade B 2026',
    category: 'Banking',
    conductingBody: 'Reserve Bank of India',
    description: 'Grade B Officer recruitment for the Reserve Bank of India.',
    eligibility: "Bachelor's Degree with 60% or Master's Degree with 55%",
    lastDate: '2026-08-10',
    salary: '₹55,200 - ₹1,10,400',
    ageLimit: '21-30 years',
    officialWebsite: 'https://www.rbi.org.in',
    selectionProcess: 'Phase-I → Phase-II → Interview',
    jobRole: 'Grade B Officer in RBI',
    salaryRange: { min: 55200, max: 110400, description: 'RBI Scale' },
    ageLimitDetails: { min: 21, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'RBI Assistant 2026',
    category: 'Banking',
    conductingBody: 'Reserve Bank of India',
    description: 'Assistant recruitment for RBI offices across India.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-09-05',
    salary: '₹36,091 (starting gross)',
    ageLimit: '20-28 years',
    officialWebsite: 'https://www.rbi.org.in',
    selectionProcess: 'Prelims → Mains → Language Proficiency Test',
    jobRole: 'Assistant in RBI',
    salaryRange: { min: 20700, max: 55700, description: 'Pay in time scale + allowances' },
    ageLimitDetails: { min: 20, max: 28, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Railways
  {
    title: 'RRB NTPC 2026',
    category: 'Railways',
    conductingBody: 'Railway Recruitment Boards',
    description: 'Non-Technical Popular Categories exam for various clerical and commercial posts in Indian Railways.',
    eligibility: '12th pass / Graduation (varies by post)',
    lastDate: '2026-09-30',
    salary: '₹19,900 - ₹92,300',
    ageLimit: '18-33 years',
    vacancies: '35,000+',
    officialWebsite: 'https://www.rrbcdg.gov.in',
    importantDates: [
      { event: 'Application End Date', date: '2026-09-30' },
      { event: 'CBT-1 Date', date: '2026-12-15' },
    ],
    selectionProcess: 'CBT-1 → CBT-2 → Typing/CBAT → Document Verification → Medical',
    jobRole: 'Station Master, Goods Guard, Commercial Apprentice, Clerk, Traffic Assistant',
    salaryRange: { min: 19900, max: 92300, description: 'Pay Level 2 to Pay Level 6' },
    ageLimitDetails: { min: 18, max: 33, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'RRB Group D 2026',
    category: 'Railways',
    conductingBody: 'Railway Recruitment Boards',
    description: 'Group D Level 1 recruitment for Track Maintainer, Helper, and other posts in Indian Railways.',
    eligibility: '10th pass + ITI (for some posts)',
    lastDate: '2026-10-15',
    salary: '₹18,000 - ₹56,900',
    ageLimit: '18-33 years',
    vacancies: '100,000+',
    officialWebsite: 'https://www.rrbcdg.gov.in',
    selectionProcess: 'CBT → PET → Document Verification → Medical',
    jobRole: 'Track Maintainer, Helper, Porter, Pointsman in Railways',
    salaryRange: { min: 18000, max: 56900, description: 'Pay Level 1 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 33, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'RRB JE 2026',
    category: 'Railways',
    conductingBody: 'Railway Recruitment Boards',
    description: 'Junior Engineer recruitment for Civil, Mechanical, Electrical, Electronics & IT posts in Railways.',
    eligibility: 'Diploma/B.E./B.Tech in relevant engineering',
    lastDate: '2026-08-31',
    salary: '₹35,400 - ₹1,12,400',
    ageLimit: '18-36 years',
    officialWebsite: 'https://www.rrbcdg.gov.in',
    selectionProcess: 'CBT-1 → CBT-2 → Document Verification → Medical',
    jobRole: 'Junior Engineer in various railway departments',
    salaryRange: { min: 35400, max: 112400, description: 'Pay Level 6 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 36, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'RRB ALP 2026',
    category: 'Railways',
    conductingBody: 'Railway Recruitment Boards',
    description: 'Assistant Loco Pilot and Technician recruitment for Indian Railways.',
    eligibility: '10th + ITI or Diploma in relevant trade',
    lastDate: '2026-07-31',
    salary: '₹19,900 - ₹63,200',
    ageLimit: '18-30 years',
    vacancies: '5,000+',
    officialWebsite: 'https://www.rrbcdg.gov.in',
    selectionProcess: 'CBT-1 → CBT-2 → CBAT → Document Verification → Medical',
    jobRole: 'Assistant Loco Pilot, Technician in Railways',
    salaryRange: { min: 19900, max: 63200, description: 'Pay Level 2 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Defence
  {
    title: 'AFCAT 2026',
    category: 'Defence',
    conductingBody: 'Indian Air Force',
    description: 'Air Force Common Admission Test for Flying, Technical, and Ground Duty branches.',
    eligibility: "Bachelor's Degree (60% in Physics & Maths for technical)",
    lastDate: '2026-06-30',
    salary: '₹56,100 - ₹1,77,500',
    ageLimit: '20-26 years',
    officialWebsite: 'https://afcat.cdac.in',
    selectionProcess: 'AFCAT Exam → AFSB Interview (5 days) → Medical',
    jobRole: 'Flying Officer in Indian Air Force',
    salaryRange: { min: 56100, max: 177500, description: 'Pay Level 10 onwards' },
    ageLimitDetails: { min: 20, max: 26, relaxation: 'As per IAF norms' },
  },
  {
    title: 'Indian Navy SSR/AA 2026',
    category: 'Defence',
    conductingBody: 'Indian Navy',
    description: 'Sailor recruitment (Senior Secondary Recruit & Artificer Apprentice) for Indian Navy.',
    eligibility: '12th pass with Science (Physics, Chemistry, Maths)',
    lastDate: '2026-07-15',
    salary: '₹21,700 - ₹69,100',
    ageLimit: '17-20 years',
    officialWebsite: 'https://www.joinindiannavy.gov.in',
    selectionProcess: 'Written Exam → PFT → Medical',
    jobRole: 'Sailor in Indian Navy',
    salaryRange: { min: 21700, max: 69100, description: 'Pay Level 3 + Naval allowances' },
    ageLimitDetails: { min: 17, max: 20, relaxation: 'As per notification' },
  },
  {
    title: 'Indian Coast Guard GD 2026',
    category: 'Defence',
    conductingBody: 'Indian Coast Guard',
    description: 'Navik (General Duty) and Yantrik recruitment for Indian Coast Guard.',
    eligibility: '10th/12th pass with Maths & Science',
    lastDate: '2026-08-10',
    salary: '₹21,700 - ₹69,100',
    ageLimit: '18-22 years',
    officialWebsite: 'https://joinindiancoastguard.cdac.in',
    selectionProcess: 'Written → PFT → Medical → Training',
    jobRole: 'Navik GD / Yantrik in Coast Guard',
    salaryRange: { min: 21700, max: 69100, description: 'Pay Level 3' },
    ageLimitDetails: { min: 18, max: 22, relaxation: 'As per ICG norms' },
  },
  // State PSC
  {
    title: 'APPSC Group 1 2026',
    category: 'State PSC',
    conductingBody: 'Andhra Pradesh Public Service Commission',
    description: 'Group 1 Services exam for gazetted officer posts in AP state government.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-07-30',
    salary: '₹37,100 - ₹1,24,400',
    ageLimit: '21-42 years',
    officialWebsite: 'https://psc.ap.gov.in',
    selectionProcess: 'Prelims → Mains → Interview',
    jobRole: 'Deputy Collector, DSP, Commercial Tax Officer, Municipal Commissioner',
    salaryRange: { min: 37100, max: 124400, description: 'AP State Pay Scale' },
    ageLimitDetails: { min: 21, max: 42, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'TSPSC Group 1 2026',
    category: 'State PSC',
    conductingBody: 'Telangana State Public Service Commission',
    description: 'Group 1 Services exam for gazetted officer posts in Telangana state government.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-08-15',
    salary: '₹37,100 - ₹1,24,400',
    ageLimit: '18-44 years',
    officialWebsite: 'https://www.tspsc.gov.in',
    selectionProcess: 'Prelims → Mains → Interview',
    jobRole: 'Deputy Collector, DSP, Commercial Tax Officer',
    salaryRange: { min: 37100, max: 124400, description: 'TS State Pay Scale' },
    ageLimitDetails: { min: 18, max: 44, relaxation: 'As per TS Govt rules' },
  },
  {
    title: 'KPSC KAS 2026',
    category: 'State PSC',
    conductingBody: 'Karnataka Public Service Commission',
    description: 'Karnataka Administrative Service exam for gazetted posts.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-09-15',
    salary: '₹36,300 - ₹1,20,000',
    ageLimit: '21-35 years',
    officialWebsite: 'https://kpsc.kar.nic.in',
    selectionProcess: 'Prelims → Mains → Interview',
    jobRole: 'Deputy Commissioner, ASP, Commercial Tax Officer, Tahsildar',
    salaryRange: { min: 36300, max: 120000, description: 'Karnataka State Pay Scale' },
    ageLimitDetails: { min: 21, max: 35, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'TNPSC Group 1 2026',
    category: 'State PSC',
    conductingBody: 'Tamil Nadu Public Service Commission',
    description: 'Group 1 exam for Tamil Nadu Civil Services.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-08-30',
    salary: '₹36,900 - ₹1,16,600',
    ageLimit: '21-37 years',
    officialWebsite: 'https://www.tnpsc.gov.in',
    selectionProcess: 'Prelims → Mains → Interview',
    jobRole: 'Deputy Collector, DSP, District Registrar',
    salaryRange: { min: 36900, max: 116600, description: 'TN State Pay Scale' },
    ageLimitDetails: { min: 21, max: 37, relaxation: 'As per TN Govt rules' },
  },
  // Teaching
  {
    title: 'CTET 2026',
    category: 'Teaching',
    conductingBody: 'CBSE',
    description: 'Central Teacher Eligibility Test for teachers of Classes I-V (Paper 1) and VI-VIII (Paper 2).',
    eligibility: 'D.El.Ed / B.Ed / Diploma in Education',
    lastDate: '2026-04-15',
    salary: '₹35,400 - ₹1,12,400 (as per school)',
    ageLimit: 'No upper age limit',
    officialWebsite: 'https://ctet.nic.in',
    selectionProcess: 'Qualify CTET → Apply to schools → Interview/Demo',
    jobRole: 'Primary Teacher (I-V) / Upper Primary Teacher (VI-VIII)',
    salaryRange: { min: 35400, max: 112400, description: 'Varies by school/state' },
    ageLimitDetails: { min: 18, max: 65, relaxation: 'No upper age limit for CTET' },
  },
  {
    title: 'UGC NET 2026',
    category: 'Teaching',
    conductingBody: 'NTA',
    description: 'National Eligibility Test for Assistant Professorship and Junior Research Fellowship.',
    eligibility: "Master's Degree with 55% marks",
    lastDate: '2026-05-30',
    salary: '₹57,700 - ₹2,18,200 (Professor scale)',
    ageLimit: 'JRF: 30 years, Lecturership: No limit',
    officialWebsite: 'https://ugcnet.nta.ac.in',
    selectionProcess: 'Computer Based Test (2 Papers in single session)',
    jobRole: 'Assistant Professor / Junior Research Fellow',
    salaryRange: { min: 57700, max: 218200, description: 'Academic Pay Level' },
    ageLimitDetails: { min: 18, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years (JRF only)' },
  },
  {
    title: 'DSSSB TGT/PGT 2026',
    category: 'Teaching',
    conductingBody: 'Delhi SSSB',
    description: 'Trained Graduate Teacher and Post Graduate Teacher recruitment for Delhi government schools.',
    eligibility: 'Graduation + B.Ed (TGT) / Post Graduation + B.Ed (PGT)',
    lastDate: '2026-06-20',
    salary: '₹44,900 - ₹1,42,400',
    ageLimit: '21-32 years',
    officialWebsite: 'https://dsssb.delhi.gov.in',
    selectionProcess: 'One Tier / Two Tier CBT → Document Verification',
    jobRole: 'TGT/PGT in Delhi Government Schools',
    salaryRange: { min: 44900, max: 142400, description: 'Pay Level 7 (TGT) / Level 8 (PGT)' },
    ageLimitDetails: { min: 21, max: 32, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Police
  {
    title: 'Delhi Police Constable 2026',
    category: 'Police',
    conductingBody: 'SSC / Delhi Police',
    description: 'Constable (Executive) recruitment for Delhi Police.',
    eligibility: '12th pass from a recognized Board',
    lastDate: '2026-07-10',
    salary: '₹21,700 - ₹69,100',
    ageLimit: '18-25 years',
    vacancies: '5,000+',
    officialWebsite: 'https://ssc.nic.in',
    selectionProcess: 'CBT → PET/PST → Medical → Document Verification',
    jobRole: 'Constable (Executive) in Delhi Police',
    salaryRange: { min: 21700, max: 69100, description: 'Pay Level 3 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 25, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'Delhi Police SI 2026',
    category: 'Police',
    conductingBody: 'SSC / Delhi Police',
    description: 'Sub-Inspector recruitment for Delhi Police, CAPF, and CISF.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-08-25',
    salary: '₹35,400 - ₹1,12,400',
    ageLimit: '20-25 years',
    officialWebsite: 'https://ssc.nic.in',
    selectionProcess: 'Paper-I → Paper-II → PET/PST → Medical',
    jobRole: 'Sub-Inspector in Delhi Police / CAPF / CISF',
    salaryRange: { min: 35400, max: 112400, description: 'Pay Level 6 (7th CPC)' },
    ageLimitDetails: { min: 20, max: 25, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Insurance
  {
    title: 'LIC AAO 2026',
    category: 'Insurance',
    conductingBody: 'Life Insurance Corporation of India',
    description: 'Assistant Administrative Officer recruitment for LIC.',
    eligibility: "Bachelor's Degree with 60% or equivalent CGPA",
    lastDate: '2026-06-15',
    salary: '₹53,600 - ₹1,07,000',
    ageLimit: '21-30 years',
    officialWebsite: 'https://www.licindia.in',
    selectionProcess: 'Prelims → Mains → Interview',
    jobRole: 'Assistant Administrative Officer in LIC',
    salaryRange: { min: 53600, max: 107000, description: 'LIC Pay Scale' },
    ageLimitDetails: { min: 21, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'NIACL AO 2026',
    category: 'Insurance',
    conductingBody: 'New India Assurance Company',
    description: 'Administrative Officer recruitment for NIACL.',
    eligibility: "Bachelor's Degree from a recognized University",
    lastDate: '2026-09-10',
    salary: '₹50,925 - ₹96,765',
    ageLimit: '21-30 years',
    officialWebsite: 'https://www.newindia.co.in',
    selectionProcess: 'Prelims → Mains → Interview',
    jobRole: 'Administrative Officer in NIACL',
    salaryRange: { min: 50925, max: 96765, description: 'NIACL Scale I' },
    ageLimitDetails: { min: 21, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Regulatory Bodies
  {
    title: 'SEBI Grade A 2026',
    category: 'Regulatory Bodies',
    conductingBody: 'SEBI',
    description: 'Grade A Officer (Assistant Manager) recruitment for SEBI.',
    eligibility: "Bachelor's Degree with 60% or Master's with 55%",
    lastDate: '2026-07-25',
    salary: '₹44,500 - ₹89,150',
    ageLimit: '21-30 years',
    officialWebsite: 'https://www.sebi.gov.in',
    selectionProcess: 'Phase-I → Phase-II → Interview',
    jobRole: 'Assistant Manager (Grade A) in SEBI',
    salaryRange: { min: 44500, max: 89150, description: 'SEBI Scale + allowances (effective CTC ~₹22 LPA)' },
    ageLimitDetails: { min: 21, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'NABARD Grade A 2026',
    category: 'Regulatory Bodies',
    conductingBody: 'NABARD',
    description: 'Grade A (Assistant Manager) recruitment for NABARD.',
    eligibility: "Bachelor's Degree with 60% or Post Graduation with 55%",
    lastDate: '2026-08-05',
    salary: '₹44,500 - ₹89,150',
    ageLimit: '21-30 years',
    officialWebsite: 'https://www.nabard.org',
    selectionProcess: 'Prelims → Mains → Interview',
    jobRole: 'Assistant Manager in NABARD',
    salaryRange: { min: 44500, max: 89150, description: 'NABARD Scale + DA + allowances' },
    ageLimitDetails: { min: 21, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Judiciary
  {
    title: 'Judicial Services Exam 2026',
    category: 'Judiciary',
    conductingBody: 'Various State High Courts',
    description: 'Civil Judge (Junior Division) / Judicial Magistrate recruitment conducted by state High Courts.',
    eligibility: 'LLB/BL Degree + Enrolled as Advocate',
    lastDate: '2026-10-30',
    salary: '₹51,550 - ₹1,23,070',
    ageLimit: '21-35 years',
    officialWebsite: 'https://highcourtchd.gov.in',
    selectionProcess: 'Prelims → Mains → Interview/Viva',
    jobRole: 'Civil Judge (Junior Division) / Judicial Magistrate First Class',
    salaryRange: { min: 51550, max: 123070, description: 'State Judicial Pay Scale' },
    ageLimitDetails: { min: 21, max: 35, relaxation: 'As per state rules' },
  },
  // PSU
  {
    title: 'ONGC Recruitment 2026',
    category: 'PSU',
    conductingBody: 'ONGC',
    description: 'Graduate Trainee (GT) recruitment through GATE for various engineering disciplines.',
    eligibility: 'B.E./B.Tech with valid GATE score',
    lastDate: '2026-04-30',
    salary: '₹60,000 - ₹1,80,000',
    ageLimit: '18-28 years',
    officialWebsite: 'https://www.ongcindia.com',
    selectionProcess: 'GATE Score → GD/Interview → Medical',
    jobRole: 'Graduate Trainee (E1 level) in ONGC',
    salaryRange: { min: 60000, max: 180000, description: 'E1 Pay Scale + perks (CTC ~₹15 LPA)' },
    ageLimitDetails: { min: 18, max: 28, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'NTPC Executive Trainee 2026',
    category: 'PSU',
    conductingBody: 'NTPC Limited',
    description: 'Executive Trainee recruitment through GATE for Engineering and Finance disciplines.',
    eligibility: 'B.E./B.Tech with valid GATE score',
    lastDate: '2026-05-15',
    salary: '₹60,000 - ₹1,80,000',
    ageLimit: '18-27 years',
    officialWebsite: 'https://www.ntpc.co.in',
    selectionProcess: 'GATE Score → GD → Interview',
    jobRole: 'Executive Trainee in NTPC',
    salaryRange: { min: 60000, max: 180000, description: 'E2 Pay Scale (CTC ~₹16 LPA)' },
    ageLimitDetails: { min: 18, max: 27, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'IOCL Apprentice 2026',
    category: 'PSU',
    conductingBody: 'Indian Oil Corporation Limited',
    description: 'Trade and Technician Apprentice recruitment for IOCL refineries and marketing divisions.',
    eligibility: '10th + ITI / Diploma in relevant trade',
    lastDate: '2026-06-30',
    salary: '₹9,000 - ₹15,000 (stipend)',
    ageLimit: '18-24 years',
    officialWebsite: 'https://www.iocl.com',
    selectionProcess: 'Written Test → Trade Test → Document Verification → Medical',
    jobRole: 'Trade Apprentice / Technician Apprentice in IOCL',
    salaryRange: { min: 9000, max: 15000, description: 'Monthly stipend during training' },
    ageLimitDetails: { min: 18, max: 24, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Agriculture
  {
    title: 'ICAR NET 2026',
    category: 'Agriculture',
    conductingBody: 'ASRB/ICAR',
    description: 'National Eligibility Test for Lectureship/Assistant Professorship in Agricultural Sciences.',
    eligibility: "Master's Degree in Agriculture/Allied Sciences with 55%",
    lastDate: '2026-06-20',
    salary: '₹57,700 - ₹2,18,200',
    ageLimit: 'No upper age limit',
    officialWebsite: 'https://asrb.org.in',
    selectionProcess: 'Computer Based Test → Qualify for lecturership/JRF',
    jobRole: 'Assistant Professor / Junior Research Fellow in Agricultural Universities',
    salaryRange: { min: 57700, max: 218200, description: 'Academic Pay Level' },
    ageLimitDetails: { min: 18, max: 65, relaxation: 'No upper age limit for NET' },
  },
  {
    title: 'FCI Manager 2026',
    category: 'Agriculture',
    conductingBody: 'Food Corporation of India',
    description: 'Manager (General/Depot/Movement/Technical) recruitment for FCI.',
    eligibility: "Bachelor's Degree in relevant discipline",
    lastDate: '2026-08-20',
    salary: '₹40,000 - ₹1,40,000',
    ageLimit: '21-28 years',
    officialWebsite: 'https://fci.gov.in',
    selectionProcess: 'Phase-I → Phase-II → Interview/Skill Test',
    jobRole: 'Manager (General/Depot/Movement/Accounts/Technical) in FCI',
    salaryRange: { min: 40000, max: 140000, description: 'IDA Pay Scale + allowances' },
    ageLimitDetails: { min: 21, max: 28, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Postal
  {
    title: 'India Post GDS 2026',
    category: 'Postal',
    conductingBody: 'Department of Posts',
    description: 'Gramin Dak Sevak recruitment for Branch Postmaster, Dak Sevak posts across India.',
    eligibility: '10th pass from a recognized Board',
    lastDate: '2026-07-31',
    salary: '₹12,000 - ₹14,500 (TRCA)',
    ageLimit: '18-40 years',
    vacancies: '40,000+',
    officialWebsite: 'https://indiapostgdsonline.gov.in',
    selectionProcess: 'Merit based on 10th marks → Document Verification',
    jobRole: 'Branch Postmaster, Assistant BPM, Dak Sevak',
    salaryRange: { min: 12000, max: 14500, description: 'Time Related Continuity Allowance' },
    ageLimitDetails: { min: 18, max: 40, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'India Post MTS 2026',
    category: 'Postal',
    conductingBody: 'Department of Posts',
    description: 'Multi Tasking Staff recruitment for postal circles across India.',
    eligibility: '10th pass from a recognized Board',
    lastDate: '2026-08-15',
    salary: '₹18,000 - ₹56,900',
    ageLimit: '18-25 years',
    officialWebsite: 'https://www.indiapost.gov.in',
    selectionProcess: 'Through SSC MTS exam → Allotment to postal circles',
    jobRole: 'MTS/Postman/Mail Guard',
    salaryRange: { min: 18000, max: 56900, description: 'Pay Level 1 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 25, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  // Healthcare
  {
    title: 'AIIMS Nursing Officer 2026',
    category: 'Healthcare',
    conductingBody: 'AIIMS',
    description: 'Nursing Officer recruitment for AIIMS hospitals across India.',
    eligibility: 'B.Sc Nursing / GNM with registration',
    lastDate: '2026-05-20',
    salary: '₹44,900 - ₹1,42,400',
    ageLimit: '18-30 years',
    vacancies: '3,000+',
    officialWebsite: 'https://www.aiimsexams.ac.in',
    selectionProcess: 'Computer Based Test → Document Verification',
    jobRole: 'Nursing Officer at AIIMS hospitals',
    salaryRange: { min: 44900, max: 142400, description: 'Pay Level 7 (7th CPC)' },
    ageLimitDetails: { min: 18, max: 30, relaxation: 'OBC: 3 years, SC/ST: 5 years' },
  },
  {
    title: 'NEET UG 2026',
    category: 'Healthcare',
    conductingBody: 'NTA',
    description: 'National Eligibility cum Entrance Test for admission to MBBS, BDS, AYUSH and other medical courses.',
    eligibility: '12th pass with Physics, Chemistry, Biology (50%)',
    lastDate: '2026-03-10',
    salary: 'Varies by specialization (₹60,000 - ₹3,00,000+)',
    ageLimit: '17+ (no upper limit)',
    officialWebsite: 'https://neet.nta.nic.in',
    selectionProcess: 'Pen & Paper Test → Counselling (AIQ + State)',
    jobRole: 'MBBS/BDS/AYUSH admission to medical colleges',
    salaryRange: { min: 60000, max: 300000, description: 'After completing MBBS' },
    ageLimitDetails: { min: 17, max: 65, relaxation: 'No upper age limit' },
  },
  // Miscellaneous
  {
    title: 'GATE 2026',
    category: 'Miscellaneous',
    conductingBody: 'IITs',
    description: 'Graduate Aptitude Test in Engineering for M.Tech admissions and PSU recruitment.',
    eligibility: 'B.E./B.Tech or equivalent in relevant discipline',
    lastDate: '2026-10-15',
    salary: 'PSU: ₹40,000 - ₹1,80,000+',
    ageLimit: 'No age limit',
    officialWebsite: 'https://gate.iitb.ac.in',
    selectionProcess: 'CBT → Score used for M.Tech admission / PSU recruitment',
    jobRole: 'M.Tech/MS admission + PSU recruitment (ONGC, IOCL, NTPC, etc.)',
    salaryRange: { min: 40000, max: 180000, description: 'Varies by PSU / admission' },
    ageLimitDetails: { min: 18, max: 65, relaxation: 'No age limit for GATE' },
  },
  {
    title: 'CAT 2026',
    category: 'Miscellaneous',
    conductingBody: 'IIMs',
    description: 'Common Admission Test for MBA/PGDM admissions to IIMs and top B-schools.',
    eligibility: "Bachelor's Degree with 50%",
    lastDate: '2026-09-20',
    salary: '₹10,00,000 - ₹50,00,000+ (post MBA placement)',
    ageLimit: 'No age limit',
    officialWebsite: 'https://iimcat.ac.in',
    selectionProcess: 'CAT Score → WAT/GD/PI at IIMs → Final Selection',
    jobRole: 'MBA/PGDM admission → Corporate careers, Consulting, Finance, Marketing',
    salaryRange: { min: 1000000, max: 5000000, description: 'Average placement at top IIMs' },
    ageLimitDetails: { min: 18, max: 65, relaxation: 'No age limit' },
  },
  {
    title: 'CLAT 2026',
    category: 'Miscellaneous',
    conductingBody: 'Consortium of NLUs',
    description: 'Common Law Admission Test for undergraduate and postgraduate law programs at NLUs.',
    eligibility: '12th pass with 45% (UG) / LLB with 50% (PG)',
    lastDate: '2026-04-15',
    salary: 'Varies (Lawyers: ₹5,00,000 - ₹50,00,000+)',
    ageLimit: 'No age limit',
    officialWebsite: 'https://consortiumofnlus.ac.in',
    selectionProcess: 'CLAT Score → Counselling → Admission to NLUs',
    jobRole: 'LLB/LLM admission → Legal career in judiciary, corporate law, litigation',
    salaryRange: { min: 500000, max: 5000000, description: 'Varies by specialization and experience' },
    ageLimitDetails: { min: 16, max: 65, relaxation: 'No upper age limit' },
  },
];

async function seedExams() {
  try {
    const existingCount = await Exam.countDocuments();
    if (existingCount >= 30) {
      console.log(`[Exam Seed] Database already has ${existingCount} exams. Skipping seed.`);
      return;
    }

    const adminUser = await User.findOne({ role: 'admin' });
    if (!adminUser) {
      console.log('[Exam Seed] No admin user found. Register and promote an admin first.');
      return;
    }

    const existingTitles = new Set(
      (await Exam.find({}, 'title').lean()).map(e => e.title)
    );

    const newExams = examsSeedData
      .filter(e => !existingTitles.has(e.title))
      .map(exam => ({
        ...exam,
        lastDate: exam.lastDate ? new Date(exam.lastDate) : undefined,
        importantDates: (exam.importantDates || []).map(d => ({
          event: d.event,
          date: new Date(d.date),
        })),
        postedBy: adminUser._id,
        isActive: true,
        postedDate: new Date(),
        createdAt: new Date(),
      }));

    if (newExams.length === 0) {
      console.log('[Exam Seed] All exams already exist. Nothing to seed.');
      return;
    }

    await Exam.insertMany(newExams);
    console.log(`[Exam Seed] Successfully seeded ${newExams.length} exams.`);
  } catch (error) {
    console.error('[Exam Seed] Error seeding exams:', error.message);
  }
}

module.exports = { seedExams };
